// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const changeOwnPasswordBySk = `-- name: ChangeOwnPasswordBySk :execrows
UPDATE detall.person
SET person_password_hash = $1, person_password_must_change = false
WHERE person_sk = $2
`

type ChangeOwnPasswordBySkParams struct {
	PersonPasswordHash *string `json:"person_password_hash"`
	PersonSk           int32   `json:"person_sk"`
}

// Cambio de contraseña por el propio usuario de sesión: fija el hash y limpia
// el flag de "debe cambiar". Person-centric (por person_sk de la propia sesión).
func (q *Queries) ChangeOwnPasswordBySk(ctx context.Context, arg ChangeOwnPasswordBySkParams) (int64, error) {
	result, err := q.db.Exec(ctx, changeOwnPasswordBySk, arg.PersonPasswordHash, arg.PersonSk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createSession = `-- name: CreateSession :exec
INSERT INTO detall.session (token_hash, person_fk, ip_address, expires_at)
VALUES ($1, $2, NULLIF($3::varchar, ''), $4)
`

type CreateSessionParams struct {
	TokenHash []byte             `json:"token_hash"`
	PersonFk  int32              `json:"person_fk"`
	IpAddress string             `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.PersonFk,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM detall.session WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const getLoginPerson = `-- name: GetLoginPerson :one

SELECT p.person_sk, p.person_user, p.person_name, p.person_last_name_1, p.person_last_name_2,
       p.person_nk, p.person_escuadrilla_fk, e.escuadrilla_code, e.escuadrilla_name,
       p.person_permission_level, p.person_password_hash, p.person_password_must_change
FROM detall.person p
JOIN detall.escuadrilla e ON e.escuadrilla_sk = p.person_escuadrilla_fk
WHERE p.person_user = $1 AND p.person_current_flag = TRUE
`

type GetLoginPersonRow struct {
	PersonSk                 int32   `json:"person_sk"`
	PersonUser               string  `json:"person_user"`
	PersonName               string  `json:"person_name"`
	PersonLastName1          string  `json:"person_last_name_1"`
	PersonLastName2          string  `json:"person_last_name_2"`
	PersonNk                 *string `json:"person_nk"`
	PersonEscuadrillaFk      int32   `json:"person_escuadrilla_fk"`
	EscuadrillaCode          string  `json:"escuadrilla_code"`
	EscuadrillaName          string  `json:"escuadrilla_name"`
	PersonPermissionLevel    string  `json:"person_permission_level"`
	PersonPasswordHash       *string `json:"person_password_hash"`
	PersonPasswordMustChange bool    `json:"person_password_must_change"`
}

// Queries de autenticación y sesiones (internal/auth).
func (q *Queries) GetLoginPerson(ctx context.Context, personUser string) (GetLoginPersonRow, error) {
	row := q.db.QueryRow(ctx, getLoginPerson, personUser)
	var i GetLoginPersonRow
	err := row.Scan(
		&i.PersonSk,
		&i.PersonUser,
		&i.PersonName,
		&i.PersonLastName1,
		&i.PersonLastName2,
		&i.PersonNk,
		&i.PersonEscuadrillaFk,
		&i.EscuadrillaCode,
		&i.EscuadrillaName,
		&i.PersonPermissionLevel,
		&i.PersonPasswordHash,
		&i.PersonPasswordMustChange,
	)
	return i, err
}

const getPersonPasswordHashBySk = `-- name: GetPersonPasswordHashBySk :one
SELECT person_password_hash FROM detall.person WHERE person_sk = $1
`

// Hash de la persona de la sesión, para verificar la contraseña actual en el
// autoservicio de cambio. Person-centric (por person_sk de la propia sesión).
func (q *Queries) GetPersonPasswordHashBySk(ctx context.Context, personSk int32) (*string, error) {
	row := q.db.QueryRow(ctx, getPersonPasswordHashBySk, personSk)
	var person_password_hash *string
	err := row.Scan(&person_password_hash)
	return person_password_hash, err
}

const purgeExpiredSessions = `-- name: PurgeExpiredSessions :execrows
DELETE FROM detall.session WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) PurgeExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPersonPassword = `-- name: SetPersonPassword :execrows
UPDATE detall.person SET person_password_hash = $1 WHERE person_user = $2
`

type SetPersonPasswordParams struct {
	PersonPasswordHash *string `json:"person_password_hash"`
	PersonUser         string  `json:"person_user"`
}

func (q *Queries) SetPersonPassword(ctx context.Context, arg SetPersonPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPersonPassword, arg.PersonPasswordHash, arg.PersonUser)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPersonPermissionLevelByUser = `-- name: SetPersonPermissionLevelByUser :execrows
UPDATE detall.person SET person_permission_level = $1 WHERE person_user = $2
`

type SetPersonPermissionLevelByUserParams struct {
	PersonPermissionLevel string `json:"person_permission_level"`
	PersonUser            string `json:"person_user"`
}

// Usado por cmd/bootstrap para fijar el nivel (p. ej. crear el primer Superusuario).
func (q *Queries) SetPersonPermissionLevelByUser(ctx context.Context, arg SetPersonPermissionLevelByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPersonPermissionLevelByUser, arg.PersonPermissionLevel, arg.PersonUser)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSessionAndGetUser = `-- name: TouchSessionAndGetUser :one
UPDATE detall.session s
SET last_seen_at = CURRENT_TIMESTAMP
FROM detall.person p
JOIN detall.escuadrilla e ON e.escuadrilla_sk = p.person_escuadrilla_fk
WHERE s.token_hash = $1
  AND s.expires_at > CURRENT_TIMESTAMP
  AND p.person_sk = s.person_fk
  AND p.person_current_flag = TRUE
RETURNING p.person_sk, p.person_user, p.person_name, p.person_last_name_1, p.person_last_name_2,
          p.person_nk, p.person_escuadrilla_fk, e.escuadrilla_code, e.escuadrilla_name,
          p.person_permission_level, p.person_password_must_change
`

type TouchSessionAndGetUserRow struct {
	PersonSk                 int32   `json:"person_sk"`
	PersonUser               string  `json:"person_user"`
	PersonName               string  `json:"person_name"`
	PersonLastName1          string  `json:"person_last_name_1"`
	PersonLastName2          string  `json:"person_last_name_2"`
	PersonNk                 *string `json:"person_nk"`
	PersonEscuadrillaFk      int32   `json:"person_escuadrilla_fk"`
	EscuadrillaCode          string  `json:"escuadrilla_code"`
	EscuadrillaName          string  `json:"escuadrilla_name"`
	PersonPermissionLevel    string  `json:"person_permission_level"`
	PersonPasswordMustChange bool    `json:"person_password_must_change"`
}

// Valida la sesión, actualiza last_seen_at y devuelve el usuario en un solo
// round-trip (antes eran un UPDATE + un SELECT separados).
func (q *Queries) TouchSessionAndGetUser(ctx context.Context, tokenHash []byte) (TouchSessionAndGetUserRow, error) {
	row := q.db.QueryRow(ctx, touchSessionAndGetUser, tokenHash)
	var i TouchSessionAndGetUserRow
	err := row.Scan(
		&i.PersonSk,
		&i.PersonUser,
		&i.PersonName,
		&i.PersonLastName1,
		&i.PersonLastName2,
		&i.PersonNk,
		&i.PersonEscuadrillaFk,
		&i.EscuadrillaCode,
		&i.EscuadrillaName,
		&i.PersonPermissionLevel,
		&i.PersonPasswordMustChange,
	)
	return i, err
}
