// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: availability.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const availabilityAbsences = `-- name: AvailabilityAbsences :many
SELECT
    a.absence_sk,
    a.absence_start_date,
    a.absence_end_date,
    (a.absence_end_date - a.absence_start_date + 1)::int AS absence_dias,
    a.absence_person_fk,
    r.absence_reason,
    a.absence_remark
FROM detall.absence a
JOIN detall.absence_reason r ON a.absence_reason_fk = r.absence_reason_sk
WHERE a.absence_start_date <= $1
  AND a.absence_end_date   >= $2
  AND a.absence_escuadrilla_fk = $3
`

type AvailabilityAbsencesParams struct {
	MonthEnd      pgtype.Date `json:"month_end"`
	MonthStart    pgtype.Date `json:"month_start"`
	EscuadrillaFk int32       `json:"escuadrilla_fk"`
}

type AvailabilityAbsencesRow struct {
	AbsenceSk        int32       `json:"absence_sk"`
	AbsenceStartDate pgtype.Date `json:"absence_start_date"`
	AbsenceEndDate   pgtype.Date `json:"absence_end_date"`
	AbsenceDias      int32       `json:"absence_dias"`
	AbsencePersonFk  int32       `json:"absence_person_fk"`
	AbsenceReason    string      `json:"absence_reason"`
	AbsenceRemark    *string     `json:"absence_remark"`
}

// Filtra ausencias que se solapan con el mes [month_start, month_end].
// sqlc.arg() fuerza nombres semánticos: sin él, sqlc nombraba los params por
// la columna del WHERE y quedaban invertidos respecto a su significado.
func (q *Queries) AvailabilityAbsences(ctx context.Context, arg AvailabilityAbsencesParams) ([]AvailabilityAbsencesRow, error) {
	rows, err := q.db.Query(ctx, availabilityAbsences, arg.MonthEnd, arg.MonthStart, arg.EscuadrillaFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AvailabilityAbsencesRow
	for rows.Next() {
		var i AvailabilityAbsencesRow
		if err := rows.Scan(
			&i.AbsenceSk,
			&i.AbsenceStartDate,
			&i.AbsenceEndDate,
			&i.AbsenceDias,
			&i.AbsencePersonFk,
			&i.AbsenceReason,
			&i.AbsenceRemark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const availabilityComisiones = `-- name: AvailabilityComisiones :many
SELECT
    jpc.person_comision_sk,
    jpc.person_fk,
    c.comision_start_date,
    c.comision_end_date,
    (c.comision_end_date - c.comision_start_date + 1)::int AS comision_dias,
    l.comision_name AS comision_lugar
FROM detall.person_comision jpc
JOIN detall.comision c       ON jpc.comision_fk = c.comision_sk
JOIN detall.comision_lugar l ON c.comision_lugar_fk = l.comision_lugar_sk
WHERE c.comision_start_date <= $1
  AND c.comision_end_date   >= $2
  AND c.comision_escuadrilla_fk = $3
`

type AvailabilityComisionesParams struct {
	MonthEnd      pgtype.Date `json:"month_end"`
	MonthStart    pgtype.Date `json:"month_start"`
	EscuadrillaFk int32       `json:"escuadrilla_fk"`
}

type AvailabilityComisionesRow struct {
	PersonComisionSk  int32       `json:"person_comision_sk"`
	PersonFk          int32       `json:"person_fk"`
	ComisionStartDate pgtype.Date `json:"comision_start_date"`
	ComisionEndDate   pgtype.Date `json:"comision_end_date"`
	ComisionDias      int32       `json:"comision_dias"`
	ComisionLugar     string      `json:"comision_lugar"`
}

// Comisiones que se solapan con el mes [month_start, month_end].
func (q *Queries) AvailabilityComisiones(ctx context.Context, arg AvailabilityComisionesParams) ([]AvailabilityComisionesRow, error) {
	rows, err := q.db.Query(ctx, availabilityComisiones, arg.MonthEnd, arg.MonthStart, arg.EscuadrillaFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AvailabilityComisionesRow
	for rows.Next() {
		var i AvailabilityComisionesRow
		if err := rows.Scan(
			&i.PersonComisionSk,
			&i.PersonFk,
			&i.ComisionStartDate,
			&i.ComisionEndDate,
			&i.ComisionDias,
			&i.ComisionLugar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const availabilityPersons = `-- name: AvailabilityPersons :many

SELECT
    p.person_sk,
    BTRIM(p.person_rank || ' ' || p.person_name || ' ' || p.person_last_name_1 || ' ' || p.person_last_name_2)::text AS full_name,
    p.person_rol,
    p.rank_category AS escala
FROM detall.v_person_ordered p
WHERE p.person_current_flag = TRUE
  AND p.person_escuadrilla_fk = $1
ORDER BY p.order_position
`

type AvailabilityPersonsRow struct {
	PersonSk  int32  `json:"person_sk"`
	FullName  string `json:"full_name"`
	PersonRol string `json:"person_rol"`
	Escala    string `json:"escala"`
}

// ============================================================
// Availability (Hito 4, lote 3)
//
// Reimplementa sp_get_availability + CRUD de detall.absence.
// Devuelve 3 listas (persons, absenses, person_comisions) filtradas
// por mes/año recibido como parámetro.
// ============================================================
func (q *Queries) AvailabilityPersons(ctx context.Context, personEscuadrillaFk int32) ([]AvailabilityPersonsRow, error) {
	rows, err := q.db.Query(ctx, availabilityPersons, personEscuadrillaFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AvailabilityPersonsRow
	for rows.Next() {
		var i AvailabilityPersonsRow
		if err := rows.Scan(
			&i.PersonSk,
			&i.FullName,
			&i.PersonRol,
			&i.Escala,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAbsence = `-- name: DeleteAbsence :execrows
DELETE FROM detall.absence
WHERE absence_sk = $1
  AND absence_escuadrilla_fk = $2
`

type DeleteAbsenceParams struct {
	AbsenceSk            int32 `json:"absence_sk"`
	AbsenceEscuadrillaFk int32 `json:"absence_escuadrilla_fk"`
}

func (q *Queries) DeleteAbsence(ctx context.Context, arg DeleteAbsenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAbsence, arg.AbsenceSk, arg.AbsenceEscuadrillaFk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAbsence = `-- name: InsertAbsence :one
INSERT INTO detall.absence (
    absence_start_date, absence_end_date, absence_person_fk,
    absence_reason_fk, absence_remark, absence_escuadrilla_fk
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING absence_sk
`

type InsertAbsenceParams struct {
	AbsenceStartDate     pgtype.Date `json:"absence_start_date"`
	AbsenceEndDate       pgtype.Date `json:"absence_end_date"`
	AbsencePersonFk      int32       `json:"absence_person_fk"`
	AbsenceReasonFk      int32       `json:"absence_reason_fk"`
	AbsenceRemark        *string     `json:"absence_remark"`
	AbsenceEscuadrillaFk int32       `json:"absence_escuadrilla_fk"`
}

func (q *Queries) InsertAbsence(ctx context.Context, arg InsertAbsenceParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertAbsence,
		arg.AbsenceStartDate,
		arg.AbsenceEndDate,
		arg.AbsencePersonFk,
		arg.AbsenceReasonFk,
		arg.AbsenceRemark,
		arg.AbsenceEscuadrillaFk,
	)
	var absence_sk int32
	err := row.Scan(&absence_sk)
	return absence_sk, err
}

const resolveAbsenceReason = `-- name: ResolveAbsenceReason :one
SELECT absence_reason_sk
FROM detall.absence_reason
WHERE absence_reason = $1
`

// absence_reason del request puede venir como nombre o como id numérico.
// Para el nombre, hacemos lookup. El handler trata el caso numérico antes de llamar.
func (q *Queries) ResolveAbsenceReason(ctx context.Context, absenceReason string) (int32, error) {
	row := q.db.QueryRow(ctx, resolveAbsenceReason, absenceReason)
	var absence_reason_sk int32
	err := row.Scan(&absence_reason_sk)
	return absence_reason_sk, err
}

const updateAbsence = `-- name: UpdateAbsence :execrows
UPDATE detall.absence
SET absence_start_date = $1,
    absence_end_date = $2,
    absence_reason_fk = $3,
    absence_remark = $4
WHERE absence_sk = $5
  AND absence_escuadrilla_fk = $6
`

type UpdateAbsenceParams struct {
	AbsenceStartDate     pgtype.Date `json:"absence_start_date"`
	AbsenceEndDate       pgtype.Date `json:"absence_end_date"`
	AbsenceReasonFk      int32       `json:"absence_reason_fk"`
	AbsenceRemark        *string     `json:"absence_remark"`
	AbsenceSk            int32       `json:"absence_sk"`
	AbsenceEscuadrillaFk int32       `json:"absence_escuadrilla_fk"`
}

func (q *Queries) UpdateAbsence(ctx context.Context, arg UpdateAbsenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAbsence,
		arg.AbsenceStartDate,
		arg.AbsenceEndDate,
		arg.AbsenceReasonFk,
		arg.AbsenceRemark,
		arg.AbsenceSk,
		arg.AbsenceEscuadrillaFk,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
