// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comisiones.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countComisiones = `-- name: CountComisiones :one
SELECT COUNT(*)::int
FROM detall.comision c
WHERE c.comision_escuadrilla_fk = $1
  AND ($2 = 0     OR c.comision_sk          = $2)
  AND ($3::date IS NULL OR c.comision_start_date >= $3)
  AND ($4::date IS NULL OR c.comision_end_date   <= $4)
`

type CountComisionesParams struct {
	ComisionEscuadrillaFk int32       `json:"comision_escuadrilla_fk"`
	Column2               interface{} `json:"column_2"`
	Column3               pgtype.Date `json:"column_3"`
	Column4               pgtype.Date `json:"column_4"`
}

func (q *Queries) CountComisiones(ctx context.Context, arg CountComisionesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countComisiones,
		arg.ComisionEscuadrillaFk,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteComision = `-- name: DeleteComision :execrows
DELETE FROM detall.comision
WHERE comision_sk = $1 AND comision_escuadrilla_fk = $2
`

type DeleteComisionParams struct {
	ComisionSk            int32 `json:"comision_sk"`
	ComisionEscuadrillaFk int32 `json:"comision_escuadrilla_fk"`
}

func (q *Queries) DeleteComision(ctx context.Context, arg DeleteComisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteComision, arg.ComisionSk, arg.ComisionEscuadrillaFk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteComisionLugar = `-- name: DeleteComisionLugar :execrows
DELETE FROM detall.comision_lugar WHERE comision_lugar_sk = $1
`

func (q *Queries) DeleteComisionLugar(ctx context.Context, comisionLugarSk int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteComisionLugar, comisionLugarSk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePersonComisionBySk = `-- name: DeletePersonComisionBySk :execrows
DELETE FROM detall.person_comision
WHERE person_comision_sk = $1
  AND comision_fk IN (
      SELECT comision_sk FROM detall.comision WHERE comision_escuadrilla_fk = $2
  )
`

type DeletePersonComisionBySkParams struct {
	PersonComisionSk      int32 `json:"person_comision_sk"`
	ComisionEscuadrillaFk int32 `json:"comision_escuadrilla_fk"`
}

func (q *Queries) DeletePersonComisionBySk(ctx context.Context, arg DeletePersonComisionBySkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePersonComisionBySk, arg.PersonComisionSk, arg.ComisionEscuadrillaFk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePersonFromComision = `-- name: DeletePersonFromComision :execrows
DELETE FROM detall.person_comision
WHERE comision_fk = $1 AND person_fk = $2
`

type DeletePersonFromComisionParams struct {
	ComisionFk int32 `json:"comision_fk"`
	PersonFk   int32 `json:"person_fk"`
}

func (q *Queries) DeletePersonFromComision(ctx context.Context, arg DeletePersonFromComisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePersonFromComision, arg.ComisionFk, arg.PersonFk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const diasComision = `-- name: DiasComision :many

WITH ventana AS (
    SELECT $1::date AS fecha_fin, ($1::date - 365) AS fecha_inicio
)
SELECT
    p.person_sk,
    p.person_rank,
    BTRIM(p.person_name || ' ' || p.person_last_name_1 || ' ' || p.person_last_name_2)::text AS full_name,
    p.person_rol,
    p.rank_category AS escala,
    EXISTS (
        SELECT 1 FROM detall.notcrew_qualification fnr
        JOIN detall.notcrew_rating_type dnr ON fnr.notcrew_rating_fk = dnr.notcrew_rating_sk
        WHERE fnr.person_fk = p.person_sk AND dnr.notcrew_rating_abrv = 'B1'
    ) AS b1,
    EXISTS (
        SELECT 1 FROM detall.notcrew_qualification fnr
        JOIN detall.notcrew_rating_type dnr ON fnr.notcrew_rating_fk = dnr.notcrew_rating_sk
        WHERE fnr.person_fk = p.person_sk AND dnr.notcrew_rating_abrv = 'B2'
    ) AS b2,
    EXISTS (
        SELECT 1 FROM detall.notcrew_qualification fnr
        JOIN detall.notcrew_rating_type dnr ON fnr.notcrew_rating_fk = dnr.notcrew_rating_sk
        WHERE fnr.person_fk = p.person_sk AND dnr.notcrew_rating_abrv = 'LV'
    ) AS lv,
    COALESCE((
        SELECT SUM((fc.comision_end_date - fc.comision_start_date + 1))::int
        FROM detall.person_comision jpc
        JOIN detall.comision fc       ON jpc.comision_fk = fc.comision_sk
        JOIN detall.comision_type dct ON fc.comision_type_fk = dct.comision_type_sk
        WHERE jpc.person_fk = p.person_sk
          AND dct.name = 'Base o de Corta duración ordenadas por COMFLOAN'
    ), 0)::int AS dias_base_corta_duracion,
    COALESCE((
        SELECT SUM((fc.comision_end_date - fc.comision_start_date + 1))::int
        FROM detall.person_comision jpc
        JOIN detall.comision fc       ON jpc.comision_fk = fc.comision_sk
        JOIN detall.comision_type dct ON fc.comision_type_fk = dct.comision_type_sk
        WHERE jpc.person_fk = p.person_sk
          AND dct.name = 'Despliegues ordenados por COMFLOAN'
    ), 0)::int AS dias_despliegues,
    COALESCE((
        SELECT SUM((fc.comision_end_date - fc.comision_start_date + 1))::int
        FROM detall.person_comision jpc
        JOIN detall.comision fc       ON jpc.comision_fk = fc.comision_sk
        JOIN detall.comision_type dct ON fc.comision_type_fk = dct.comision_type_sk
        WHERE jpc.person_fk = p.person_sk
          AND dct.name = 'Ofertadas por otros mandos y de carácter voluntario'
    ), 0)::int AS dias_voluntarias,
    COALESCE((
        SELECT SUM(
            (LEAST(fc.comision_end_date, w.fecha_fin)
             - GREATEST(fc.comision_start_date, w.fecha_inicio) + 1)
        )::int
        FROM detall.person_comision jpc
        JOIN detall.comision fc       ON jpc.comision_fk = fc.comision_sk
        JOIN detall.comision_type dct ON fc.comision_type_fk = dct.comision_type_sk
        CROSS JOIN ventana w
        WHERE jpc.person_fk = p.person_sk
          AND dct.name = 'OMP como UNAEMB o UNADEST'
          AND fc.comision_start_date <= w.fecha_fin
          AND fc.comision_end_date   >= w.fecha_inicio
    ), 0)::int AS dias_omp,
    COALESCE((
        SELECT SUM(
            (LEAST(fc.comision_end_date, w.fecha_fin)
             - GREATEST(fc.comision_start_date, w.fecha_inicio) + 1)
        )::int
        FROM detall.person_comision jpc
        JOIN detall.comision fc       ON jpc.comision_fk = fc.comision_sk
        JOIN detall.comision_type dct ON fc.comision_type_fk = dct.comision_type_sk
        CROSS JOIN ventana w
        WHERE jpc.person_fk = p.person_sk
          AND dct.name = 'UNADEST nacionales o extranjero'
          AND fc.comision_start_date <= w.fecha_fin
          AND fc.comision_end_date   >= w.fecha_inicio
    ), 0)::int AS dias_unadest,
    COALESCE((
        SELECT SUM(
            (LEAST(fc.comision_end_date, w.fecha_fin)
             - GREATEST(fc.comision_start_date, w.fecha_inicio) + 1)
        )::int
        FROM detall.person_comision jpc
        JOIN detall.comision fc       ON jpc.comision_fk = fc.comision_sk
        JOIN detall.comision_type dct ON fc.comision_type_fk = dct.comision_type_sk
        CROSS JOIN ventana w
        WHERE jpc.person_fk = p.person_sk
          AND dct.name = 'UNAEMB nacionales o extranjero'
          AND fc.comision_start_date <= w.fecha_fin
          AND fc.comision_end_date   >= w.fecha_inicio
    ), 0)::int AS dias_unaemb,
    COALESCE((
        SELECT SUM(r.dias)::int
        FROM detall.person_comision jpc
        JOIN detall.person_comision_rancheria r ON r.person_comision_fk = jpc.person_comision_sk
        WHERE jpc.person_fk = p.person_sk
    ), 0)::int AS dias_rancheria
FROM detall.v_person_ordered p
WHERE p.person_current_flag = TRUE
  AND p.person_escuadrilla_fk = $2
ORDER BY p.order_position, p.person_last_name_1, p.person_last_name_2
`

type DiasComisionParams struct {
	Column1             pgtype.Date `json:"column_1"`
	PersonEscuadrillaFk int32       `json:"person_escuadrilla_fk"`
}

type DiasComisionRow struct {
	PersonSk              int32  `json:"person_sk"`
	PersonRank            string `json:"person_rank"`
	FullName              string `json:"full_name"`
	PersonRol             string `json:"person_rol"`
	Escala                string `json:"escala"`
	B1                    bool   `json:"b1"`
	B2                    bool   `json:"b2"`
	Lv                    bool   `json:"lv"`
	DiasBaseCortaDuracion int32  `json:"dias_base_corta_duracion"`
	DiasDespliegues       int32  `json:"dias_despliegues"`
	DiasVoluntarias       int32  `json:"dias_voluntarias"`
	DiasOmp               int32  `json:"dias_omp"`
	DiasUnadest           int32  `json:"dias_unadest"`
	DiasUnaemb            int32  `json:"dias_unaemb"`
	DiasRancheria         int32  `json:"dias_rancheria"`
}

// =============== sp_get_dias_comision ===============
// $1 = fechaFin (NULL → CURRENT_DATE en handler). fechaInicio = fechaFin - 365.
// Devuelve per-persona días totales por categoría de comisión:
//   - Categorías "no caducan": SUMA días totales históricos.
//   - Categorías "sí caducan" (OMP/UNADEST/UNAEMB): SUMA solapamiento con [fechaInicio, fechaFin].
func (q *Queries) DiasComision(ctx context.Context, arg DiasComisionParams) ([]DiasComisionRow, error) {
	rows, err := q.db.Query(ctx, diasComision, arg.Column1, arg.PersonEscuadrillaFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiasComisionRow
	for rows.Next() {
		var i DiasComisionRow
		if err := rows.Scan(
			&i.PersonSk,
			&i.PersonRank,
			&i.FullName,
			&i.PersonRol,
			&i.Escala,
			&i.B1,
			&i.B2,
			&i.Lv,
			&i.DiasBaseCortaDuracion,
			&i.DiasDespliegues,
			&i.DiasVoluntarias,
			&i.DiasOmp,
			&i.DiasUnadest,
			&i.DiasUnaemb,
			&i.DiasRancheria,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComisionDates = `-- name: GetComisionDates :one

SELECT comision_start_date, comision_end_date
FROM detall.comision
WHERE comision_sk = $1 AND comision_escuadrilla_fk = $2
`

type GetComisionDatesParams struct {
	ComisionSk            int32 `json:"comision_sk"`
	ComisionEscuadrillaFk int32 `json:"comision_escuadrilla_fk"`
}

type GetComisionDatesRow struct {
	ComisionStartDate pgtype.Date `json:"comision_start_date"`
	ComisionEndDate   pgtype.Date `json:"comision_end_date"`
}

// =============== person_comision (assign + delete) ===============
// Devuelve las fechas y comprueba que la comisión existe en la escuadrilla.
func (q *Queries) GetComisionDates(ctx context.Context, arg GetComisionDatesParams) (GetComisionDatesRow, error) {
	row := q.db.QueryRow(ctx, getComisionDates, arg.ComisionSk, arg.ComisionEscuadrillaFk)
	var i GetComisionDatesRow
	err := row.Scan(&i.ComisionStartDate, &i.ComisionEndDate)
	return i, err
}

const insertComision = `-- name: InsertComision :one

INSERT INTO detall.comision (
    comision_start_date, comision_end_date,
    comision_type_fk, comision_lugar_fk,
    comision_escuadrilla_fk, comision_esfuerzo,
    comision_departure_time, comision_arrival_time, comision_code
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING comision_sk
`

type InsertComisionParams struct {
	ComisionStartDate     pgtype.Date `json:"comision_start_date"`
	ComisionEndDate       pgtype.Date `json:"comision_end_date"`
	ComisionTypeFk        int32       `json:"comision_type_fk"`
	ComisionLugarFk       int32       `json:"comision_lugar_fk"`
	ComisionEscuadrillaFk int32       `json:"comision_escuadrilla_fk"`
	ComisionEsfuerzo      bool        `json:"comision_esfuerzo"`
	ComisionDepartureTime pgtype.Time `json:"comision_departure_time"`
	ComisionArrivalTime   pgtype.Time `json:"comision_arrival_time"`
	ComisionCode          *string     `json:"comision_code"`
}

// =============== Comisión CRUD ===============
func (q *Queries) InsertComision(ctx context.Context, arg InsertComisionParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertComision,
		arg.ComisionStartDate,
		arg.ComisionEndDate,
		arg.ComisionTypeFk,
		arg.ComisionLugarFk,
		arg.ComisionEscuadrillaFk,
		arg.ComisionEsfuerzo,
		arg.ComisionDepartureTime,
		arg.ComisionArrivalTime,
		arg.ComisionCode,
	)
	var comision_sk int32
	err := row.Scan(&comision_sk)
	return comision_sk, err
}

const insertComisionLugar = `-- name: InsertComisionLugar :one
INSERT INTO detall.comision_lugar (comision_name)
VALUES ($1)
RETURNING comision_lugar_sk, comision_name
`

func (q *Queries) InsertComisionLugar(ctx context.Context, comisionName string) (DetallComisionLugar, error) {
	row := q.db.QueryRow(ctx, insertComisionLugar, comisionName)
	var i DetallComisionLugar
	err := row.Scan(&i.ComisionLugarSk, &i.ComisionName)
	return i, err
}

const insertPersonComisionRancheria = `-- name: InsertPersonComisionRancheria :exec
INSERT INTO detall.person_comision_rancheria (person_comision_fk, dias)
SELECT pc.person_comision_sk, $1::int
FROM detall.person_comision pc
WHERE pc.comision_fk = $2 AND pc.person_fk = $3
`

type InsertPersonComisionRancheriaParams struct {
	Dias       int32 `json:"dias"`
	ComisionFk int32 `json:"comision_fk"`
	PersonFk   int32 `json:"person_fk"`
}

// Marca con días de ranchería a un participante ya insertado, resolviendo su
// person_comision_sk desde (comision_fk, person_fk).
func (q *Queries) InsertPersonComisionRancheria(ctx context.Context, arg InsertPersonComisionRancheriaParams) error {
	_, err := q.db.Exec(ctx, insertPersonComisionRancheria, arg.Dias, arg.ComisionFk, arg.PersonFk)
	return err
}

const insertPersonToComision = `-- name: InsertPersonToComision :exec
INSERT INTO detall.person_comision (comision_fk, person_fk) VALUES ($1, $2)
`

type InsertPersonToComisionParams struct {
	ComisionFk int32 `json:"comision_fk"`
	PersonFk   int32 `json:"person_fk"`
}

func (q *Queries) InsertPersonToComision(ctx context.Context, arg InsertPersonToComisionParams) error {
	_, err := q.db.Exec(ctx, insertPersonToComision, arg.ComisionFk, arg.PersonFk)
	return err
}

const listComisionPeople = `-- name: ListComisionPeople :many
SELECT
    pc.comision_fk,
    pc.person_comision_sk,
    BTRIM(p.person_rank || ' ' || p.person_last_name_1 || ' ' || p.person_last_name_2)::text AS nombre,
    p.order_position AS orden,
    COALESCE(pcr.dias, 0)::int AS rancheria_dias
FROM detall.person_comision pc
JOIN detall.v_person_ordered p ON pc.person_fk = p.person_sk
LEFT JOIN detall.person_comision_rancheria pcr ON pcr.person_comision_fk = pc.person_comision_sk
WHERE pc.comision_fk = ANY($1::int[])
ORDER BY pc.comision_fk, p.order_position
`

type ListComisionPeopleRow struct {
	ComisionFk       int32  `json:"comision_fk"`
	PersonComisionSk int32  `json:"person_comision_sk"`
	Nombre           string `json:"nombre"`
	Orden            int64  `json:"orden"`
	RancheriaDias    int32  `json:"rancheria_dias"`
}

// Personas asignadas a las comisiones de una página, en una sola query (bulk,
// como las tablas hijas de flights); Go agrupa por comision_fk. Ordenadas por
// la vista canónica. rancheria_dias = 0 si la persona no hizo ranchería.
func (q *Queries) ListComisionPeople(ctx context.Context, dollar_1 []int32) ([]ListComisionPeopleRow, error) {
	rows, err := q.db.Query(ctx, listComisionPeople, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListComisionPeopleRow
	for rows.Next() {
		var i ListComisionPeopleRow
		if err := rows.Scan(
			&i.ComisionFk,
			&i.PersonComisionSk,
			&i.Nombre,
			&i.Orden,
			&i.RancheriaDias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComisionPeopleExpanded = `-- name: ListComisionPeopleExpanded :many
SELECT
    pc.comision_fk,
    p.person_sk,
    p.person_nk,
    p.person_rank,
    p.person_name,
    p.person_last_name_1,
    p.person_last_name_2
FROM detall.person_comision pc
JOIN detall.person p ON pc.person_fk = p.person_sk
WHERE pc.comision_fk = ANY($1::int[])
ORDER BY pc.comision_fk, p.person_rank, p.person_name
`

type ListComisionPeopleExpandedRow struct {
	ComisionFk      int32   `json:"comision_fk"`
	PersonSk        int32   `json:"person_sk"`
	PersonNk        *string `json:"person_nk"`
	PersonRank      string  `json:"person_rank"`
	PersonName      string  `json:"person_name"`
	PersonLastName1 string  `json:"person_last_name_1"`
	PersonLastName2 string  `json:"person_last_name_2"`
}

// Variante con campos separados (espejo de get_comision_people en Rust), bulk.
func (q *Queries) ListComisionPeopleExpanded(ctx context.Context, dollar_1 []int32) ([]ListComisionPeopleExpandedRow, error) {
	rows, err := q.db.Query(ctx, listComisionPeopleExpanded, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListComisionPeopleExpandedRow
	for rows.Next() {
		var i ListComisionPeopleExpandedRow
		if err := rows.Scan(
			&i.ComisionFk,
			&i.PersonSk,
			&i.PersonNk,
			&i.PersonRank,
			&i.PersonName,
			&i.PersonLastName1,
			&i.PersonLastName2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComisiones = `-- name: ListComisiones :many

SELECT
    c.comision_sk,
    c.comision_start_date,
    c.comision_end_date,
    (c.comision_end_date - c.comision_start_date + 1)::int AS dias,
    cl.comision_name                                       AS lugar,
    ct.name                                                AS tipo,
    c.comision_esfuerzo                                    AS esfuerzo,
    c.comision_departure_time                              AS hora_salida,
    c.comision_arrival_time                                AS hora_llegada,
    c.comision_code                                        AS codigo
FROM detall.comision c
JOIN detall.comision_lugar cl ON c.comision_lugar_fk = cl.comision_lugar_sk
JOIN detall.comision_type  ct ON c.comision_type_fk  = ct.comision_type_sk
WHERE c.comision_escuadrilla_fk = $1
  AND ($2 = 0     OR c.comision_sk          = $2)
  AND ($3::date IS NULL OR c.comision_start_date >= $3)
  AND ($4::date IS NULL OR c.comision_end_date   <= $4)
ORDER BY c.comision_sk DESC
LIMIT $5 OFFSET $6
`

type ListComisionesParams struct {
	ComisionEscuadrillaFk int32       `json:"comision_escuadrilla_fk"`
	Column2               interface{} `json:"column_2"`
	Column3               pgtype.Date `json:"column_3"`
	Column4               pgtype.Date `json:"column_4"`
	Limit                 int32       `json:"limit"`
	Offset                int32       `json:"offset"`
}

type ListComisionesRow struct {
	ComisionSk        int32       `json:"comision_sk"`
	ComisionStartDate pgtype.Date `json:"comision_start_date"`
	ComisionEndDate   pgtype.Date `json:"comision_end_date"`
	Dias              int32       `json:"dias"`
	Lugar             string      `json:"lugar"`
	Tipo              string      `json:"tipo"`
	Esfuerzo          bool        `json:"esfuerzo"`
	HoraSalida        pgtype.Time `json:"hora_salida"`
	HoraLlegada       pgtype.Time `json:"hora_llegada"`
	Codigo            *string     `json:"codigo"`
}

// =============== Comisión listings ===============
// Paginado + filtros opcionales. Convención:
//
//	$2 = comision_sk filtro (0 → sin filtro)
//	$3 = date_from (pgtype.Date.Valid=false → sin filtro)
//	$4 = date_to   (idem)
func (q *Queries) ListComisiones(ctx context.Context, arg ListComisionesParams) ([]ListComisionesRow, error) {
	rows, err := q.db.Query(ctx, listComisiones,
		arg.ComisionEscuadrillaFk,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListComisionesRow
	for rows.Next() {
		var i ListComisionesRow
		if err := rows.Scan(
			&i.ComisionSk,
			&i.ComisionStartDate,
			&i.ComisionEndDate,
			&i.Dias,
			&i.Lugar,
			&i.Tipo,
			&i.Esfuerzo,
			&i.HoraSalida,
			&i.HoraLlegada,
			&i.Codigo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonComisionesByType = `-- name: ListPersonComisionesByType :many

SELECT
    c.comision_sk,
    c.comision_code,
    c.comision_start_date,
    c.comision_end_date,
    cl.comision_name                                       AS lugar,
    (c.comision_end_date - c.comision_start_date + 1)::int AS dias
FROM detall.person_comision pc
JOIN detall.person        p  ON pc.person_fk      = p.person_sk
JOIN detall.comision      c  ON pc.comision_fk    = c.comision_sk
JOIN detall.comision_type ct ON c.comision_type_fk = ct.comision_type_sk
JOIN detall.comision_lugar cl ON c.comision_lugar_fk = cl.comision_lugar_sk
WHERE pc.person_fk = $1
  AND ct.name = $2
  AND p.person_escuadrilla_fk = $3
ORDER BY c.comision_start_date DESC
`

type ListPersonComisionesByTypeParams struct {
	PersonFk            int32  `json:"person_fk"`
	Name                string `json:"name"`
	PersonEscuadrillaFk int32  `json:"person_escuadrilla_fk"`
}

type ListPersonComisionesByTypeRow struct {
	ComisionSk        int32       `json:"comision_sk"`
	ComisionCode      *string     `json:"comision_code"`
	ComisionStartDate pgtype.Date `json:"comision_start_date"`
	ComisionEndDate   pgtype.Date `json:"comision_end_date"`
	Lugar             string      `json:"lugar"`
	Dias              int32       `json:"dias"`
}

// =============== Desglose días de comisión por persona ===============
// Detalle de las comisiones que componen el total de una categoría para una
// persona (lo que se muestra al pinchar una celda en "Días de comisión").
// Espejan la aritmética de DiasComision para que el sumatorio de `dias` cuadre.
// Categorías "no caducan": dias = duración total de la comisión.
// $1 = person_sk, $2 = comision_type.name, $3 = escuadrilla de la sesión.
// RLS: person_sk viene de un query param del cliente; el JOIN a person con
// person_escuadrilla_fk impide leer el desglose de personas de otra escuadrilla.
func (q *Queries) ListPersonComisionesByType(ctx context.Context, arg ListPersonComisionesByTypeParams) ([]ListPersonComisionesByTypeRow, error) {
	rows, err := q.db.Query(ctx, listPersonComisionesByType, arg.PersonFk, arg.Name, arg.PersonEscuadrillaFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonComisionesByTypeRow
	for rows.Next() {
		var i ListPersonComisionesByTypeRow
		if err := rows.Scan(
			&i.ComisionSk,
			&i.ComisionCode,
			&i.ComisionStartDate,
			&i.ComisionEndDate,
			&i.Lugar,
			&i.Dias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonComisionesByTypeWindowed = `-- name: ListPersonComisionesByTypeWindowed :many
WITH ventana AS (
    SELECT $3::date AS fecha_fin, ($3::date - 365) AS fecha_inicio
)
SELECT
    c.comision_sk,
    c.comision_code,
    c.comision_start_date,
    c.comision_end_date,
    cl.comision_name AS lugar,
    (LEAST(c.comision_end_date, w.fecha_fin)
     - GREATEST(c.comision_start_date, w.fecha_inicio) + 1)::int AS dias
FROM detall.person_comision pc
JOIN detall.person        p  ON pc.person_fk      = p.person_sk
JOIN detall.comision      c  ON pc.comision_fk    = c.comision_sk
JOIN detall.comision_type ct ON c.comision_type_fk = ct.comision_type_sk
JOIN detall.comision_lugar cl ON c.comision_lugar_fk = cl.comision_lugar_sk
CROSS JOIN ventana w
WHERE pc.person_fk = $1
  AND ct.name = $2
  AND c.comision_start_date <= w.fecha_fin
  AND c.comision_end_date   >= w.fecha_inicio
  AND p.person_escuadrilla_fk = $4
ORDER BY c.comision_start_date DESC
`

type ListPersonComisionesByTypeWindowedParams struct {
	PersonFk            int32       `json:"person_fk"`
	Name                string      `json:"name"`
	Column3             pgtype.Date `json:"column_3"`
	PersonEscuadrillaFk int32       `json:"person_escuadrilla_fk"`
}

type ListPersonComisionesByTypeWindowedRow struct {
	ComisionSk        int32       `json:"comision_sk"`
	ComisionCode      *string     `json:"comision_code"`
	ComisionStartDate pgtype.Date `json:"comision_start_date"`
	ComisionEndDate   pgtype.Date `json:"comision_end_date"`
	Lugar             string      `json:"lugar"`
	Dias              int32       `json:"dias"`
}

// Categorías "sí caducan" (OMP/UNADEST/UNAEMB): dias = solapamiento con
// [fechaFin-365, fechaFin]. $1 = person_sk, $2 = comision_type.name,
// $3 = fechaFin, $4 = escuadrilla de la sesión (RLS, ver ListPersonComisionesByType).
func (q *Queries) ListPersonComisionesByTypeWindowed(ctx context.Context, arg ListPersonComisionesByTypeWindowedParams) ([]ListPersonComisionesByTypeWindowedRow, error) {
	rows, err := q.db.Query(ctx, listPersonComisionesByTypeWindowed,
		arg.PersonFk,
		arg.Name,
		arg.Column3,
		arg.PersonEscuadrillaFk,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonComisionesByTypeWindowedRow
	for rows.Next() {
		var i ListPersonComisionesByTypeWindowedRow
		if err := rows.Scan(
			&i.ComisionSk,
			&i.ComisionCode,
			&i.ComisionStartDate,
			&i.ComisionEndDate,
			&i.Lugar,
			&i.Dias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonRancheria = `-- name: ListPersonRancheria :many
SELECT
    c.comision_sk,
    c.comision_code,
    c.comision_start_date,
    c.comision_end_date,
    cl.comision_name AS lugar,
    r.dias::int      AS dias
FROM detall.person_comision pc
JOIN detall.person         p  ON pc.person_fk        = p.person_sk
JOIN detall.comision       c  ON pc.comision_fk      = c.comision_sk
JOIN detall.comision_lugar cl ON c.comision_lugar_fk = cl.comision_lugar_sk
JOIN detall.person_comision_rancheria r ON r.person_comision_fk = pc.person_comision_sk
WHERE pc.person_fk = $1
  AND p.person_escuadrilla_fk = $2
ORDER BY c.comision_start_date DESC
`

type ListPersonRancheriaParams struct {
	PersonFk            int32 `json:"person_fk"`
	PersonEscuadrillaFk int32 `json:"person_escuadrilla_fk"`
}

type ListPersonRancheriaRow struct {
	ComisionSk        int32       `json:"comision_sk"`
	ComisionCode      *string     `json:"comision_code"`
	ComisionStartDate pgtype.Date `json:"comision_start_date"`
	ComisionEndDate   pgtype.Date `json:"comision_end_date"`
	Lugar             string      `json:"lugar"`
	Dias              int32       `json:"dias"`
}

// Ranchería: dias = person_comision_rancheria.dias (independiente del tipo).
// $1 = person_sk, $2 = escuadrilla de la sesión (RLS, ver ListPersonComisionesByType).
func (q *Queries) ListPersonRancheria(ctx context.Context, arg ListPersonRancheriaParams) ([]ListPersonRancheriaRow, error) {
	rows, err := q.db.Query(ctx, listPersonRancheria, arg.PersonFk, arg.PersonEscuadrillaFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonRancheriaRow
	for rows.Next() {
		var i ListPersonRancheriaRow
		if err := rows.Scan(
			&i.ComisionSk,
			&i.ComisionCode,
			&i.ComisionStartDate,
			&i.ComisionEndDate,
			&i.Lugar,
			&i.Dias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lugarExistsByName = `-- name: LugarExistsByName :one

SELECT EXISTS (
    SELECT 1 FROM detall.comision_lugar WHERE LOWER(comision_name) = LOWER($1)
) AS exists
`

// =============== comision_lugar CRUD ===============
func (q *Queries) LugarExistsByName(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, lugarExistsByName, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lugarExistsByNameOther = `-- name: LugarExistsByNameOther :one
SELECT EXISTS (
    SELECT 1 FROM detall.comision_lugar
    WHERE comision_name = $1 AND comision_lugar_sk <> $2
) AS exists
`

type LugarExistsByNameOtherParams struct {
	ComisionName    string `json:"comision_name"`
	ComisionLugarSk int32  `json:"comision_lugar_sk"`
}

func (q *Queries) LugarExistsByNameOther(ctx context.Context, arg LugarExistsByNameOtherParams) (bool, error) {
	row := q.db.QueryRow(ctx, lugarExistsByNameOther, arg.ComisionName, arg.ComisionLugarSk)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lugarUsageCount = `-- name: LugarUsageCount :one
SELECT COUNT(*)::int FROM detall.comision WHERE comision_lugar_fk = $1
`

func (q *Queries) LugarUsageCount(ctx context.Context, comisionLugarFk int32) (int32, error) {
	row := q.db.QueryRow(ctx, lugarUsageCount, comisionLugarFk)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const personAlreadyInComision = `-- name: PersonAlreadyInComision :one
SELECT EXISTS (
    SELECT 1 FROM detall.person_comision
    WHERE comision_fk = $1 AND person_fk = $2
) AS exists
`

type PersonAlreadyInComisionParams struct {
	ComisionFk int32 `json:"comision_fk"`
	PersonFk   int32 `json:"person_fk"`
}

func (q *Queries) PersonAlreadyInComision(ctx context.Context, arg PersonAlreadyInComisionParams) (bool, error) {
	row := q.db.QueryRow(ctx, personAlreadyInComision, arg.ComisionFk, arg.PersonFk)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const personFullName = `-- name: PersonFullName :one
SELECT
    BTRIM(
        COALESCE(NULLIF(BTRIM(person_rank), ''), '')         || ' ' ||
        COALESCE(NULLIF(BTRIM(person_name), ''), '')         || ' ' ||
        COALESCE(NULLIF(BTRIM(person_last_name_1), ''), '')  || ' ' ||
        COALESCE(NULLIF(BTRIM(person_last_name_2), ''), '')
    )::text AS full_name
FROM detall.person WHERE person_sk = $1
`

// Para mensajes de error en bulk assign.
func (q *Queries) PersonFullName(ctx context.Context, personSk int32) (string, error) {
	row := q.db.QueryRow(ctx, personFullName, personSk)
	var full_name string
	err := row.Scan(&full_name)
	return full_name, err
}

const personHasOverlapAbsence = `-- name: PersonHasOverlapAbsence :one
SELECT EXISTS (
    SELECT 1 FROM detall.absence
    WHERE absence_person_fk = $1
      AND $2::date <= absence_end_date
      AND $3::date >= absence_start_date
) AS exists
`

type PersonHasOverlapAbsenceParams struct {
	AbsencePersonFk int32       `json:"absence_person_fk"`
	Column2         pgtype.Date `json:"column_2"`
	Column3         pgtype.Date `json:"column_3"`
}

func (q *Queries) PersonHasOverlapAbsence(ctx context.Context, arg PersonHasOverlapAbsenceParams) (bool, error) {
	row := q.db.QueryRow(ctx, personHasOverlapAbsence, arg.AbsencePersonFk, arg.Column2, arg.Column3)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const personHasOverlapComision = `-- name: PersonHasOverlapComision :one
SELECT EXISTS (
    SELECT 1
    FROM detall.person_comision pc
    JOIN detall.comision c ON c.comision_sk = pc.comision_fk
    WHERE pc.person_fk = $1
      AND $2::date <= c.comision_end_date
      AND $3::date >= c.comision_start_date
) AS exists
`

type PersonHasOverlapComisionParams struct {
	PersonFk int32       `json:"person_fk"`
	Column2  pgtype.Date `json:"column_2"`
	Column3  pgtype.Date `json:"column_3"`
}

// Otra comisión cualquiera del person que solapa con [start, end].
func (q *Queries) PersonHasOverlapComision(ctx context.Context, arg PersonHasOverlapComisionParams) (bool, error) {
	row := q.db.QueryRow(ctx, personHasOverlapComision, arg.PersonFk, arg.Column2, arg.Column3)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const personsInEscuadrilla = `-- name: PersonsInEscuadrilla :many
SELECT person_sk
FROM detall.person
WHERE person_sk = ANY($1::int[])
  AND person_escuadrilla_fk = $2
`

type PersonsInEscuadrillaParams struct {
	Column1             []int32 `json:"column_1"`
	PersonEscuadrillaFk int32   `json:"person_escuadrilla_fk"`
}

// De entre los person_sk dados, devuelve los que pertenecen a la escuadrilla.
// Sirve para validar en el bulk-assign que no se asignan personas de otra
// escuadrilla (los person_sk vienen del cliente y no están acotados de otro modo).
func (q *Queries) PersonsInEscuadrilla(ctx context.Context, arg PersonsInEscuadrillaParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, personsInEscuadrilla, arg.Column1, arg.PersonEscuadrillaFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var person_sk int32
		if err := rows.Scan(&person_sk); err != nil {
			return nil, err
		}
		items = append(items, person_sk)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveComisionLugar = `-- name: ResolveComisionLugar :one
SELECT comision_lugar_sk FROM detall.comision_lugar WHERE comision_name = $1
`

func (q *Queries) ResolveComisionLugar(ctx context.Context, comisionName string) (int32, error) {
	row := q.db.QueryRow(ctx, resolveComisionLugar, comisionName)
	var comision_lugar_sk int32
	err := row.Scan(&comision_lugar_sk)
	return comision_lugar_sk, err
}

const resolveComisionType = `-- name: ResolveComisionType :one



SELECT comision_type_sk FROM detall.comision_type WHERE name = $1
`

// ============================================================
// Comisiones (Hito 4, lote 4)
//
// Reimplementa sp_get_comisiones, sp_get_dias_comision + CRUD de
// detall.comision, detall.comision_lugar, detall.person_comision.
//
// Fix RLS: update/delete de comisión filtran por escuadrilla_fk.
// detall.comision_lugar NO tiene escuadrilla_fk (catálogo global) →
// las mutaciones se protegen sólo con RequireAuth.
// ============================================================
// =============== Resolvers (name → sk) ===============
func (q *Queries) ResolveComisionType(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, resolveComisionType, name)
	var comision_type_sk int32
	err := row.Scan(&comision_type_sk)
	return comision_type_sk, err
}

const updateComision = `-- name: UpdateComision :execrows
UPDATE detall.comision
SET comision_start_date    = $1,
    comision_end_date      = $2,
    comision_type_fk       = $3,
    comision_lugar_fk      = $4,
    comision_esfuerzo      = $5,
    comision_departure_time = $6,
    comision_arrival_time   = $7,
    comision_code           = $8
WHERE comision_sk = $9 AND comision_escuadrilla_fk = $10
`

type UpdateComisionParams struct {
	ComisionStartDate     pgtype.Date `json:"comision_start_date"`
	ComisionEndDate       pgtype.Date `json:"comision_end_date"`
	ComisionTypeFk        int32       `json:"comision_type_fk"`
	ComisionLugarFk       int32       `json:"comision_lugar_fk"`
	ComisionEsfuerzo      bool        `json:"comision_esfuerzo"`
	ComisionDepartureTime pgtype.Time `json:"comision_departure_time"`
	ComisionArrivalTime   pgtype.Time `json:"comision_arrival_time"`
	ComisionCode          *string     `json:"comision_code"`
	ComisionSk            int32       `json:"comision_sk"`
	ComisionEscuadrillaFk int32       `json:"comision_escuadrilla_fk"`
}

func (q *Queries) UpdateComision(ctx context.Context, arg UpdateComisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateComision,
		arg.ComisionStartDate,
		arg.ComisionEndDate,
		arg.ComisionTypeFk,
		arg.ComisionLugarFk,
		arg.ComisionEsfuerzo,
		arg.ComisionDepartureTime,
		arg.ComisionArrivalTime,
		arg.ComisionCode,
		arg.ComisionSk,
		arg.ComisionEscuadrillaFk,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateComisionLugar = `-- name: UpdateComisionLugar :execrows
UPDATE detall.comision_lugar SET comision_name = $1
WHERE comision_lugar_sk = $2
`

type UpdateComisionLugarParams struct {
	ComisionName    string `json:"comision_name"`
	ComisionLugarSk int32  `json:"comision_lugar_sk"`
}

func (q *Queries) UpdateComisionLugar(ctx context.Context, arg UpdateComisionLugarParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateComisionLugar, arg.ComisionName, arg.ComisionLugarSk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
