// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package queries

import (
	"context"
)

const countEvents = `-- name: CountEvents :one
SELECT COUNT(*)::int AS total FROM operations.event
`

func (q *Queries) CountEvents(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countEvents)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const getEventsAll = `-- name: GetEventsAll :many

SELECT event_sk, event_name, event_place
FROM operations.event
ORDER BY event_name
`

// ============================================================
// Events (Hito 4, lote 2)
// Reemplaza operations.sp_get_events + add_event + update_event.
// operations.event no tiene escuadrilla_fk → catálogo global.
// ============================================================
func (q *Queries) GetEventsAll(ctx context.Context) ([]OperationsEvent, error) {
	rows, err := q.db.Query(ctx, getEventsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OperationsEvent
	for rows.Next() {
		var i OperationsEvent
		if err := rows.Scan(&i.EventSk, &i.EventName, &i.EventPlace); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO operations.event (event_name, event_place)
VALUES ($1, $2)
RETURNING event_sk
`

type InsertEventParams struct {
	EventName  string `json:"event_name"`
	EventPlace string `json:"event_place"`
}

// Devuelve el sk para que el frontend pueda redirigir / seleccionar.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertEvent, arg.EventName, arg.EventPlace)
	var event_sk int32
	err := row.Scan(&event_sk)
	return event_sk, err
}

const updateEvent = `-- name: UpdateEvent :execrows
UPDATE operations.event
SET event_name = $1, event_place = $2
WHERE event_sk = $3
`

type UpdateEventParams struct {
	EventName  string `json:"event_name"`
	EventPlace string `json:"event_place"`
	EventSk    int32  `json:"event_sk"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEvent, arg.EventName, arg.EventPlace, arg.EventSk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
