// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: extramodelhours.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExtraModelHourPersons = `-- name: CountExtraModelHourPersons :one
SELECT COUNT(*)::int FROM (
    SELECT eh.extra_model_hours_person_fk
    FROM operations.extra_model_hour eh
    JOIN detall.person p ON eh.extra_model_hours_person_fk = p.person_sk
    WHERE p.person_escuadrilla_fk = $1
      AND ($2::text = ''
           OR public.unaccent(p.person_nk) ILIKE public.unaccent('%' || $2 || '%')
           OR public.unaccent(BTRIM(p.person_rank || ' ' || p.person_name || ' ' || p.person_last_name_1 || ' ' ||
                    COALESCE(p.person_last_name_2, ''))) ILIKE public.unaccent('%' || $2 || '%')
           OR public.unaccent(p.person_name) ILIKE public.unaccent('%' || $2 || '%'))
    GROUP BY eh.extra_model_hours_person_fk
) t
`

type CountExtraModelHourPersonsParams struct {
	PersonEscuadrillaFk int32  `json:"person_escuadrilla_fk"`
	Column2             string `json:"column_2"`
}

func (q *Queries) CountExtraModelHourPersons(ctx context.Context, arg CountExtraModelHourPersonsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countExtraModelHourPersons, arg.PersonEscuadrillaFk, arg.Column2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteExtraModelHour = `-- name: DeleteExtraModelHour :execrows
DELETE FROM operations.extra_model_hour eh
USING detall.person p
WHERE eh.extra_model_hours_sk = $1
  AND p.person_sk = eh.extra_model_hours_person_fk
  AND p.person_escuadrilla_fk = $2
`

type DeleteExtraModelHourParams struct {
	ExtraModelHoursSk   int32 `json:"extra_model_hours_sk"`
	PersonEscuadrillaFk int32 `json:"person_escuadrilla_fk"`
}

func (q *Queries) DeleteExtraModelHour(ctx context.Context, arg DeleteExtraModelHourParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExtraModelHour, arg.ExtraModelHoursSk, arg.PersonEscuadrillaFk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertExtraModelHour = `-- name: InsertExtraModelHour :one

INSERT INTO operations.extra_model_hour (
    extra_model_hours_date, extra_model_hours_person_fk, extra_model_hours_is_real,
    extra_model_hours_cta, extra_model_hours_day, extra_model_hours_conv_night,
    extra_model_hours_gvn, extra_model_hours_inst, extra_model_hours_remarks
)
SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9
WHERE EXISTS (
    SELECT 1 FROM detall.person
    WHERE person_sk = $2 AND person_escuadrilla_fk = $10
)
RETURNING extra_model_hours_sk
`

type InsertExtraModelHourParams struct {
	ExtraModelHoursDate      pgtype.Date    `json:"extra_model_hours_date"`
	ExtraModelHoursPersonFk  int32          `json:"extra_model_hours_person_fk"`
	ExtraModelHoursIsReal    bool           `json:"extra_model_hours_is_real"`
	ExtraModelHoursCta       pgtype.Numeric `json:"extra_model_hours_cta"`
	ExtraModelHoursDay       pgtype.Numeric `json:"extra_model_hours_day"`
	ExtraModelHoursConvNight pgtype.Numeric `json:"extra_model_hours_conv_night"`
	ExtraModelHoursGvn       pgtype.Numeric `json:"extra_model_hours_gvn"`
	ExtraModelHoursInst      pgtype.Numeric `json:"extra_model_hours_inst"`
	ExtraModelHoursRemarks   *string        `json:"extra_model_hours_remarks"`
	PersonEscuadrillaFk      int32          `json:"person_escuadrilla_fk"`
}

// ============================================================
// Horas extra del modelo de aeronave anterior (operations.extra_model_hour)
//
// Horas por persona con fecha y discriminador real/simulador
// (extra_model_hours_is_real). Sin restricción de unicidad: una persona puede
// tener varias filas (se suman en los cálculos de horas y en la vista agrupada).
//
// RLS por código: la tabla es person-centric (sin escuadrilla_fk); el
// aislamiento se hace vía la escuadrilla de la persona
// (detall.person.person_escuadrilla_fk = $N) en cada sentencia.
// ============================================================
// Inserta solo si la persona pertenece a la escuadrilla de la sesión ($9); si
// no, no inserta ninguna fila (RETURNING vacío → ErrNoRows en el service).
func (q *Queries) InsertExtraModelHour(ctx context.Context, arg InsertExtraModelHourParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertExtraModelHour,
		arg.ExtraModelHoursDate,
		arg.ExtraModelHoursPersonFk,
		arg.ExtraModelHoursIsReal,
		arg.ExtraModelHoursCta,
		arg.ExtraModelHoursDay,
		arg.ExtraModelHoursConvNight,
		arg.ExtraModelHoursGvn,
		arg.ExtraModelHoursInst,
		arg.ExtraModelHoursRemarks,
		arg.PersonEscuadrillaFk,
	)
	var extra_model_hours_sk int32
	err := row.Scan(&extra_model_hours_sk)
	return extra_model_hours_sk, err
}

const listExtraModelHourByPerson = `-- name: ListExtraModelHourByPerson :many
SELECT
    eh.extra_model_hours_sk,
    p.person_nk,
    BTRIM(p.person_rank || ' ' || p.person_name || ' ' || p.person_last_name_1 || ' ' ||
          COALESCE(p.person_last_name_2, ''))::text AS persona,
    eh.extra_model_hours_person_fk,
    eh.extra_model_hours_date,
    eh.extra_model_hours_is_real,
    eh.extra_model_hours_cta::float8        AS cta,
    eh.extra_model_hours_day::float8        AS day,
    eh.extra_model_hours_conv_night::float8 AS conv_night,
    eh.extra_model_hours_gvn::float8        AS gvn,
    eh.extra_model_hours_inst::float8       AS inst,
    eh.extra_model_hours_remarks
FROM operations.extra_model_hour eh
JOIN detall.person p ON eh.extra_model_hours_person_fk = p.person_sk
WHERE p.person_escuadrilla_fk = $1
  AND eh.extra_model_hours_person_fk = $2
ORDER BY eh.extra_model_hours_date DESC, eh.extra_model_hours_sk DESC
`

type ListExtraModelHourByPersonParams struct {
	PersonEscuadrillaFk     int32 `json:"person_escuadrilla_fk"`
	ExtraModelHoursPersonFk int32 `json:"extra_model_hours_person_fk"`
}

type ListExtraModelHourByPersonRow struct {
	ExtraModelHoursSk       int32       `json:"extra_model_hours_sk"`
	PersonNk                *string     `json:"person_nk"`
	Persona                 string      `json:"persona"`
	ExtraModelHoursPersonFk int32       `json:"extra_model_hours_person_fk"`
	ExtraModelHoursDate     pgtype.Date `json:"extra_model_hours_date"`
	ExtraModelHoursIsReal   bool        `json:"extra_model_hours_is_real"`
	Cta                     float64     `json:"cta"`
	Day                     float64     `json:"day"`
	ConvNight               float64     `json:"conv_night"`
	Gvn                     float64     `json:"gvn"`
	Inst                    float64     `json:"inst"`
	ExtraModelHoursRemarks  *string     `json:"extra_model_hours_remarks"`
}

// Detalle: registros individuales de UNA persona ($2), acotado a la escuadrilla
// de la sesión ($1). Sin paginar (cada persona tiene pocos registros).
func (q *Queries) ListExtraModelHourByPerson(ctx context.Context, arg ListExtraModelHourByPersonParams) ([]ListExtraModelHourByPersonRow, error) {
	rows, err := q.db.Query(ctx, listExtraModelHourByPerson, arg.PersonEscuadrillaFk, arg.ExtraModelHoursPersonFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExtraModelHourByPersonRow
	for rows.Next() {
		var i ListExtraModelHourByPersonRow
		if err := rows.Scan(
			&i.ExtraModelHoursSk,
			&i.PersonNk,
			&i.Persona,
			&i.ExtraModelHoursPersonFk,
			&i.ExtraModelHoursDate,
			&i.ExtraModelHoursIsReal,
			&i.Cta,
			&i.Day,
			&i.ConvNight,
			&i.Gvn,
			&i.Inst,
			&i.ExtraModelHoursRemarks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtraModelHourPersonTotals = `-- name: ListExtraModelHourPersonTotals :many
SELECT
    p.person_sk,
    p.person_nk,
    BTRIM(p.person_rank || ' ' || p.person_name || ' ' || p.person_last_name_1 || ' ' ||
          COALESCE(p.person_last_name_2, ''))::text AS persona,
    COUNT(*)::int                                AS record_count,
    SUM(eh.extra_model_hours_cta)::float8        AS cta,
    SUM(eh.extra_model_hours_day)::float8        AS day,
    SUM(eh.extra_model_hours_conv_night)::float8 AS conv_night,
    SUM(eh.extra_model_hours_gvn)::float8        AS gvn,
    SUM(eh.extra_model_hours_inst)::float8       AS inst
FROM operations.extra_model_hour eh
JOIN detall.person p ON eh.extra_model_hours_person_fk = p.person_sk
JOIN detall.v_person_ordered vpo ON vpo.person_sk = p.person_sk
WHERE p.person_escuadrilla_fk = $1
  AND ($2::text = ''
       OR public.unaccent(p.person_nk) ILIKE public.unaccent('%' || $2 || '%')
       OR public.unaccent(BTRIM(p.person_rank || ' ' || p.person_name || ' ' || p.person_last_name_1 || ' ' ||
                COALESCE(p.person_last_name_2, ''))) ILIKE public.unaccent('%' || $2 || '%')
       OR public.unaccent(p.person_name) ILIKE public.unaccent('%' || $2 || '%'))
GROUP BY p.person_sk, vpo.order_position
ORDER BY vpo.order_position
LIMIT $3 OFFSET $4
`

type ListExtraModelHourPersonTotalsParams struct {
	PersonEscuadrillaFk int32  `json:"person_escuadrilla_fk"`
	Column2             string `json:"column_2"`
	Limit               int32  `json:"limit"`
	Offset              int32  `json:"offset"`
}

type ListExtraModelHourPersonTotalsRow struct {
	PersonSk    int32   `json:"person_sk"`
	PersonNk    *string `json:"person_nk"`
	Persona     string  `json:"persona"`
	RecordCount int32   `json:"record_count"`
	Cta         float64 `json:"cta"`
	Day         float64 `json:"day"`
	ConvNight   float64 `json:"conv_night"`
	Gvn         float64 `json:"gvn"`
	Inst        float64 `json:"inst"`
}

// Vista agrupada: una fila por persona con el conteo de registros y la SUMA de
// cada métrica (real + simulador combinados). Ordenado por el orden canónico
// (detall.v_person_ordered.order_position). Paginado por persona. $2 = filtro
// opcional por nombre/NK (cadena vacía = sin filtro), ignorando acentos.
func (q *Queries) ListExtraModelHourPersonTotals(ctx context.Context, arg ListExtraModelHourPersonTotalsParams) ([]ListExtraModelHourPersonTotalsRow, error) {
	rows, err := q.db.Query(ctx, listExtraModelHourPersonTotals,
		arg.PersonEscuadrillaFk,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExtraModelHourPersonTotalsRow
	for rows.Next() {
		var i ListExtraModelHourPersonTotalsRow
		if err := rows.Scan(
			&i.PersonSk,
			&i.PersonNk,
			&i.Persona,
			&i.RecordCount,
			&i.Cta,
			&i.Day,
			&i.ConvNight,
			&i.Gvn,
			&i.Inst,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExtraModelHour = `-- name: UpdateExtraModelHour :execrows
UPDATE operations.extra_model_hour eh
SET extra_model_hours_date        = $2,
    extra_model_hours_is_real     = $3,
    extra_model_hours_cta         = $4,
    extra_model_hours_day         = $5,
    extra_model_hours_conv_night  = $6,
    extra_model_hours_gvn         = $7,
    extra_model_hours_inst        = $8,
    extra_model_hours_remarks     = $9
FROM detall.person p
WHERE eh.extra_model_hours_sk = $1
  AND p.person_sk = eh.extra_model_hours_person_fk
  AND p.person_escuadrilla_fk = $10
`

type UpdateExtraModelHourParams struct {
	ExtraModelHoursSk        int32          `json:"extra_model_hours_sk"`
	ExtraModelHoursDate      pgtype.Date    `json:"extra_model_hours_date"`
	ExtraModelHoursIsReal    bool           `json:"extra_model_hours_is_real"`
	ExtraModelHoursCta       pgtype.Numeric `json:"extra_model_hours_cta"`
	ExtraModelHoursDay       pgtype.Numeric `json:"extra_model_hours_day"`
	ExtraModelHoursConvNight pgtype.Numeric `json:"extra_model_hours_conv_night"`
	ExtraModelHoursGvn       pgtype.Numeric `json:"extra_model_hours_gvn"`
	ExtraModelHoursInst      pgtype.Numeric `json:"extra_model_hours_inst"`
	ExtraModelHoursRemarks   *string        `json:"extra_model_hours_remarks"`
	PersonEscuadrillaFk      int32          `json:"person_escuadrilla_fk"`
}

// Actualiza fecha, tipo y horas (la persona del registro no cambia). Acotado a
// registros de personas de la escuadrilla de la sesión ($9).
func (q *Queries) UpdateExtraModelHour(ctx context.Context, arg UpdateExtraModelHourParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateExtraModelHour,
		arg.ExtraModelHoursSk,
		arg.ExtraModelHoursDate,
		arg.ExtraModelHoursIsReal,
		arg.ExtraModelHoursCta,
		arg.ExtraModelHoursDay,
		arg.ExtraModelHoursConvNight,
		arg.ExtraModelHoursGvn,
		arg.ExtraModelHoursInst,
		arg.ExtraModelHoursRemarks,
		arg.PersonEscuadrillaFk,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
