// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: extrahours.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExtraHourPersons = `-- name: CountExtraHourPersons :one
SELECT COUNT(*)::int FROM (
    SELECT eh.extra_hours_person_fk
    FROM operations.extra_hour eh
    JOIN detall.person p ON eh.extra_hours_person_fk = p.person_sk
    WHERE p.person_escuadrilla_fk = $1
      AND ($2::text = ''
           OR public.unaccent(p.person_nk) ILIKE public.unaccent('%' || $2 || '%')
           OR public.unaccent(BTRIM(p.person_rank || ' ' || p.person_last_name_1 || ' ' ||
                    COALESCE(p.person_last_name_2, ''))) ILIKE public.unaccent('%' || $2 || '%')
           OR public.unaccent(p.person_name) ILIKE public.unaccent('%' || $2 || '%'))
    GROUP BY eh.extra_hours_person_fk
) t
`

type CountExtraHourPersonsParams struct {
	PersonEscuadrillaFk int32  `json:"person_escuadrilla_fk"`
	Column2             string `json:"column_2"`
}

// Número de personas (no de registros) que tienen horas extra, con el mismo
// filtro de nombre que ListExtraHourPersonTotals.
func (q *Queries) CountExtraHourPersons(ctx context.Context, arg CountExtraHourPersonsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countExtraHourPersons, arg.PersonEscuadrillaFk, arg.Column2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteExtraHour = `-- name: DeleteExtraHour :execrows
DELETE FROM operations.extra_hour eh
USING detall.person p
WHERE eh.extra_hours_sk = $1
  AND p.person_sk = eh.extra_hours_person_fk
  AND p.person_escuadrilla_fk = $2
`

type DeleteExtraHourParams struct {
	ExtraHoursSk        int32 `json:"extra_hours_sk"`
	PersonEscuadrillaFk int32 `json:"person_escuadrilla_fk"`
}

func (q *Queries) DeleteExtraHour(ctx context.Context, arg DeleteExtraHourParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExtraHour, arg.ExtraHoursSk, arg.PersonEscuadrillaFk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertExtraHour = `-- name: InsertExtraHour :one

INSERT INTO operations.extra_hour (
    extra_hours_person_fk, extra_hours_cta, extra_hours_day,
    extra_hours_conv_night, extra_hours_gvn, extra_hours_inst, extra_hours_remarks
)
SELECT $1, $2, $3, $4, $5, $6, $7
WHERE EXISTS (
    SELECT 1 FROM detall.person
    WHERE person_sk = $1 AND person_escuadrilla_fk = $8
)
RETURNING extra_hours_sk
`

type InsertExtraHourParams struct {
	ExtraHoursPersonFk  int32          `json:"extra_hours_person_fk"`
	ExtraHoursCta       pgtype.Numeric `json:"extra_hours_cta"`
	ExtraHoursDay       pgtype.Numeric `json:"extra_hours_day"`
	ExtraHoursConvNight pgtype.Numeric `json:"extra_hours_conv_night"`
	ExtraHoursGvn       pgtype.Numeric `json:"extra_hours_gvn"`
	ExtraHoursInst      pgtype.Numeric `json:"extra_hours_inst"`
	ExtraHoursRemarks   *string        `json:"extra_hours_remarks"`
	PersonEscuadrillaFk int32          `json:"person_escuadrilla_fk"`
}

// ============================================================
// Horas extra (operations.extra_hour)
//
// Arrastre de horas por persona (CTA, día, noche convencional, GVN,
// instrumentos) + observaciones. Una persona puede tener varias filas, que se
// suman en los cálculos de horas (queries/hours.sql) y en la vista agrupada de
// abajo (ListExtraHourPersonTotals).
//
// RLS por código: operations.extra_hour NO tiene escuadrilla_fk (es
// person-centric), así que el aislamiento se hace vía la escuadrilla de la
// persona (detall.person.person_escuadrilla_fk = $N). Todas las sentencias de
// abajo lo aplican, por lo que quedan acotadas a personas de la escuadrilla
// de la sesión.
// ============================================================
// Inserta solo si la persona pertenece a la escuadrilla de la sesión ($8); si
// no, no inserta ninguna fila (RETURNING vacío → ErrNoRows en el service).
func (q *Queries) InsertExtraHour(ctx context.Context, arg InsertExtraHourParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertExtraHour,
		arg.ExtraHoursPersonFk,
		arg.ExtraHoursCta,
		arg.ExtraHoursDay,
		arg.ExtraHoursConvNight,
		arg.ExtraHoursGvn,
		arg.ExtraHoursInst,
		arg.ExtraHoursRemarks,
		arg.PersonEscuadrillaFk,
	)
	var extra_hours_sk int32
	err := row.Scan(&extra_hours_sk)
	return extra_hours_sk, err
}

const listExtraHourByPerson = `-- name: ListExtraHourByPerson :many
SELECT
    eh.extra_hours_sk,
    p.person_nk,
    BTRIM(p.person_rank || ' ' || p.person_name || ' ' || p.person_last_name_1 || ' ' ||
          COALESCE(p.person_last_name_2, ''))::text AS persona,
    eh.extra_hours_person_fk,
    eh.extra_hours_cta::float8        AS cta,
    eh.extra_hours_day::float8        AS day,
    eh.extra_hours_conv_night::float8 AS conv_night,
    eh.extra_hours_gvn::float8        AS gvn,
    eh.extra_hours_inst::float8       AS inst,
    eh.extra_hours_remarks
FROM operations.extra_hour eh
JOIN detall.person p ON eh.extra_hours_person_fk = p.person_sk
WHERE p.person_escuadrilla_fk = $1
  AND eh.extra_hours_person_fk = $2
ORDER BY eh.extra_hours_sk DESC
`

type ListExtraHourByPersonParams struct {
	PersonEscuadrillaFk int32 `json:"person_escuadrilla_fk"`
	ExtraHoursPersonFk  int32 `json:"extra_hours_person_fk"`
}

type ListExtraHourByPersonRow struct {
	ExtraHoursSk       int32   `json:"extra_hours_sk"`
	PersonNk           *string `json:"person_nk"`
	Persona            string  `json:"persona"`
	ExtraHoursPersonFk int32   `json:"extra_hours_person_fk"`
	Cta                float64 `json:"cta"`
	Day                float64 `json:"day"`
	ConvNight          float64 `json:"conv_night"`
	Gvn                float64 `json:"gvn"`
	Inst               float64 `json:"inst"`
	ExtraHoursRemarks  *string `json:"extra_hours_remarks"`
}

// Detalle: registros individuales de UNA persona ($2), acotado a la escuadrilla
// de la sesión ($1). Sin paginar (cada persona tiene pocos registros).
func (q *Queries) ListExtraHourByPerson(ctx context.Context, arg ListExtraHourByPersonParams) ([]ListExtraHourByPersonRow, error) {
	rows, err := q.db.Query(ctx, listExtraHourByPerson, arg.PersonEscuadrillaFk, arg.ExtraHoursPersonFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExtraHourByPersonRow
	for rows.Next() {
		var i ListExtraHourByPersonRow
		if err := rows.Scan(
			&i.ExtraHoursSk,
			&i.PersonNk,
			&i.Persona,
			&i.ExtraHoursPersonFk,
			&i.Cta,
			&i.Day,
			&i.ConvNight,
			&i.Gvn,
			&i.Inst,
			&i.ExtraHoursRemarks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtraHourPersonTotals = `-- name: ListExtraHourPersonTotals :many
SELECT
    p.person_sk,
    p.person_nk,
    BTRIM(p.person_rank || ' ' || p.person_name || ' ' || p.person_last_name_1 || ' ' ||
          COALESCE(p.person_last_name_2, ''))::text AS persona,
    COUNT(*)::int                          AS record_count,
    SUM(eh.extra_hours_cta)::float8        AS cta,
    SUM(eh.extra_hours_day)::float8        AS day,
    SUM(eh.extra_hours_conv_night)::float8 AS conv_night,
    SUM(eh.extra_hours_gvn)::float8        AS gvn,
    SUM(eh.extra_hours_inst)::float8       AS inst
FROM operations.extra_hour eh
JOIN detall.person p ON eh.extra_hours_person_fk = p.person_sk
JOIN detall.v_person_ordered vpo ON vpo.person_sk = p.person_sk
WHERE p.person_escuadrilla_fk = $1
  AND ($2::text = ''
       OR public.unaccent(p.person_nk) ILIKE public.unaccent('%' || $2 || '%')
       OR public.unaccent(BTRIM(p.person_rank || ' ' || p.person_last_name_1 || ' ' ||
                COALESCE(p.person_last_name_2, ''))) ILIKE public.unaccent('%' || $2 || '%')
       OR public.unaccent(p.person_name) ILIKE public.unaccent('%' || $2 || '%'))
GROUP BY p.person_sk, vpo.order_position
ORDER BY vpo.order_position
LIMIT $3 OFFSET $4
`

type ListExtraHourPersonTotalsParams struct {
	PersonEscuadrillaFk int32  `json:"person_escuadrilla_fk"`
	Column2             string `json:"column_2"`
	Limit               int32  `json:"limit"`
	Offset              int32  `json:"offset"`
}

type ListExtraHourPersonTotalsRow struct {
	PersonSk    int32   `json:"person_sk"`
	PersonNk    *string `json:"person_nk"`
	Persona     string  `json:"persona"`
	RecordCount int32   `json:"record_count"`
	Cta         float64 `json:"cta"`
	Day         float64 `json:"day"`
	ConvNight   float64 `json:"conv_night"`
	Gvn         float64 `json:"gvn"`
	Inst        float64 `json:"inst"`
}

// Vista agrupada: una fila por persona con el conteo de registros y la SUMA de
// cada métrica. Ordenado por el orden canónico de personas
// (detall.v_person_ordered.order_position: rango, antigüedad, escalafón…).
// Paginado por persona. $2 = filtro opcional por nombre/NK (cadena vacía = sin filtro).
func (q *Queries) ListExtraHourPersonTotals(ctx context.Context, arg ListExtraHourPersonTotalsParams) ([]ListExtraHourPersonTotalsRow, error) {
	rows, err := q.db.Query(ctx, listExtraHourPersonTotals,
		arg.PersonEscuadrillaFk,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExtraHourPersonTotalsRow
	for rows.Next() {
		var i ListExtraHourPersonTotalsRow
		if err := rows.Scan(
			&i.PersonSk,
			&i.PersonNk,
			&i.Persona,
			&i.RecordCount,
			&i.Cta,
			&i.Day,
			&i.ConvNight,
			&i.Gvn,
			&i.Inst,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExtraHour = `-- name: UpdateExtraHour :execrows
UPDATE operations.extra_hour eh
SET extra_hours_cta        = $2,
    extra_hours_day        = $3,
    extra_hours_conv_night = $4,
    extra_hours_gvn        = $5,
    extra_hours_inst       = $6,
    extra_hours_remarks    = $7
FROM detall.person p
WHERE eh.extra_hours_sk = $1
  AND p.person_sk = eh.extra_hours_person_fk
  AND p.person_escuadrilla_fk = $8
`

type UpdateExtraHourParams struct {
	ExtraHoursSk        int32          `json:"extra_hours_sk"`
	ExtraHoursCta       pgtype.Numeric `json:"extra_hours_cta"`
	ExtraHoursDay       pgtype.Numeric `json:"extra_hours_day"`
	ExtraHoursConvNight pgtype.Numeric `json:"extra_hours_conv_night"`
	ExtraHoursGvn       pgtype.Numeric `json:"extra_hours_gvn"`
	ExtraHoursInst      pgtype.Numeric `json:"extra_hours_inst"`
	ExtraHoursRemarks   *string        `json:"extra_hours_remarks"`
	PersonEscuadrillaFk int32          `json:"person_escuadrilla_fk"`
}

// Actualiza solo las horas y observaciones (la persona del registro no cambia).
// Acotado a registros de personas de la escuadrilla de la sesión ($8).
func (q *Queries) UpdateExtraHour(ctx context.Context, arg UpdateExtraHourParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateExtraHour,
		arg.ExtraHoursSk,
		arg.ExtraHoursCta,
		arg.ExtraHoursDay,
		arg.ExtraHoursConvNight,
		arg.ExtraHoursGvn,
		arg.ExtraHoursInst,
		arg.ExtraHoursRemarks,
		arg.PersonEscuadrillaFk,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
