// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: festivos.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFestivo = `-- name: DeleteFestivo :execrows
DELETE FROM detall.festivos WHERE festivo_sk = $1
`

func (q *Queries) DeleteFestivo(ctx context.Context, festivoSk int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFestivo, festivoSk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const festivoExistsOnDate = `-- name: FestivoExistsOnDate :one
SELECT EXISTS (
    SELECT 1 FROM detall.festivos WHERE festivo_dia = $1
) AS exists
`

// Comportamiento heredado: bloquear cualquier 2º festivo en la misma fecha,
// aunque el motivo difiera (más estricto que UQ_festivo en BD).
func (q *Queries) FestivoExistsOnDate(ctx context.Context, festivoDia pgtype.Date) (bool, error) {
	row := q.db.QueryRow(ctx, festivoExistsOnDate, festivoDia)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const festivoExistsOnDateOtherSk = `-- name: FestivoExistsOnDateOtherSk :one
SELECT EXISTS (
    SELECT 1 FROM detall.festivos WHERE festivo_dia = $1 AND festivo_sk <> $2
) AS exists
`

type FestivoExistsOnDateOtherSkParams struct {
	FestivoDia pgtype.Date `json:"festivo_dia"`
	FestivoSk  int32       `json:"festivo_sk"`
}

func (q *Queries) FestivoExistsOnDateOtherSk(ctx context.Context, arg FestivoExistsOnDateOtherSkParams) (bool, error) {
	row := q.db.QueryRow(ctx, festivoExistsOnDateOtherSk, arg.FestivoDia, arg.FestivoSk)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertFestivo = `-- name: InsertFestivo :one
INSERT INTO detall.festivos (festivo_dia, festivo_motivo)
VALUES ($1, $2)
RETURNING festivo_sk
`

type InsertFestivoParams struct {
	FestivoDia    pgtype.Date `json:"festivo_dia"`
	FestivoMotivo string      `json:"festivo_motivo"`
}

func (q *Queries) InsertFestivo(ctx context.Context, arg InsertFestivoParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertFestivo, arg.FestivoDia, arg.FestivoMotivo)
	var festivo_sk int32
	err := row.Scan(&festivo_sk)
	return festivo_sk, err
}

const listFestivos = `-- name: ListFestivos :many

SELECT festivo_sk, festivo_dia, festivo_motivo
FROM detall.festivos
ORDER BY festivo_dia
`

// ============================================================
// Festivos (Hito 4, lote 2)
// Catálogo global (sin escuadrilla_fk en la tabla).
// ============================================================
func (q *Queries) ListFestivos(ctx context.Context) ([]DetallFestivo, error) {
	rows, err := q.db.Query(ctx, listFestivos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DetallFestivo
	for rows.Next() {
		var i DetallFestivo
		if err := rows.Scan(&i.FestivoSk, &i.FestivoDia, &i.FestivoMotivo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFestivo = `-- name: UpdateFestivo :execrows
UPDATE detall.festivos
SET festivo_dia = $1, festivo_motivo = $2
WHERE festivo_sk = $3
`

type UpdateFestivoParams struct {
	FestivoDia    pgtype.Date `json:"festivo_dia"`
	FestivoMotivo string      `json:"festivo_motivo"`
	FestivoSk     int32       `json:"festivo_sk"`
}

func (q *Queries) UpdateFestivo(ctx context.Context, arg UpdateFestivoParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFestivo, arg.FestivoDia, arg.FestivoMotivo, arg.FestivoSk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
