// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flights.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFlights = `-- name: CountFlights :one
SELECT COUNT(*)::int
FROM operations.flight f
WHERE f.flight_escuadrilla_fk = $1
  AND ($2 = 0 OR f.flight_sk = $2)
  AND ($3::date IS NULL OR f.flight_date >= $3)
  AND ($4::date IS NULL OR f.flight_date <= $4)
`

type CountFlightsParams struct {
	FlightEscuadrillaFk int32       `json:"flight_escuadrilla_fk"`
	Column2             interface{} `json:"column_2"`
	Column3             pgtype.Date `json:"column_3"`
	Column4             pgtype.Date `json:"column_4"`
}

func (q *Queries) CountFlights(ctx context.Context, arg CountFlightsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countFlights,
		arg.FlightEscuadrillaFk,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteFlight = `-- name: DeleteFlight :execrows

DELETE FROM operations.flight
WHERE flight_sk = $1 AND flight_escuadrilla_fk = $2
`

type DeleteFlightParams struct {
	FlightSk            int32 `json:"flight_sk"`
	FlightEscuadrillaFk int32 `json:"flight_escuadrilla_fk"`
}

// =============== DELETE (cascade en BD elimina hijos) ===============
func (q *Queries) DeleteFlight(ctx context.Context, arg DeleteFlightParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFlight, arg.FlightSk, arg.FlightEscuadrillaFk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const flightApproaches = `-- name: FlightApproaches :many
SELECT app_flight_fk AS flight_sk, app_person_fk AS person_sk,
       app_type_fk AS type_fk, app_qty AS qty
FROM operations.approach
WHERE app_flight_fk = ANY($1::int[])
`

type FlightApproachesRow struct {
	FlightSk int32 `json:"flight_sk"`
	PersonSk int32 `json:"person_sk"`
	TypeFk   int32 `json:"type_fk"`
	Qty      int32 `json:"qty"`
}

func (q *Queries) FlightApproaches(ctx context.Context, dollar_1 []int32) ([]FlightApproachesRow, error) {
	rows, err := q.db.Query(ctx, flightApproaches, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightApproachesRow
	for rows.Next() {
		var i FlightApproachesRow
		if err := rows.Scan(
			&i.FlightSk,
			&i.PersonSk,
			&i.TypeFk,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const flightCrew = `-- name: FlightCrew :many

SELECT DISTINCT
    p.person_sk,
    p.person_nk,
    p.order_position,
    p.person_rol,
    BTRIM(p.person_rank || ' ' || p.person_last_name_1 || ' ' || p.person_last_name_2)::text AS nombre,
    ph.person_hour_flight_fk AS flight_sk
FROM detall.v_person_ordered p
JOIN operations.person_hour ph ON ph.person_hour_person_fk = p.person_sk
WHERE ph.person_hour_flight_fk = ANY($1::int[])
ORDER BY ph.person_hour_flight_fk, p.order_position
`

type FlightCrewRow struct {
	PersonSk      int32   `json:"person_sk"`
	PersonNk      *string `json:"person_nk"`
	OrderPosition int64   `json:"order_position"`
	PersonRol     string  `json:"person_rol"`
	Nombre        string  `json:"nombre"`
	FlightSk      int32   `json:"flight_sk"`
}

// =============== BULK FETCHES por flight_sk[] (para componer JSON) ===============
// Personas que tienen al menos 1 person_hour para los vuelos dados.
func (q *Queries) FlightCrew(ctx context.Context, dollar_1 []int32) ([]FlightCrewRow, error) {
	rows, err := q.db.Query(ctx, flightCrew, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightCrewRow
	for rows.Next() {
		var i FlightCrewRow
		if err := rows.Scan(
			&i.PersonSk,
			&i.PersonNk,
			&i.OrderPosition,
			&i.PersonRol,
			&i.Nombre,
			&i.FlightSk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const flightCupos = `-- name: FlightCupos :many
SELECT ch.cupo_flight_fk AS flight_sk,
       a.authority_name  AS autoridad,
       ch.cupo_hour_qty::numeric AS horas
FROM operations.cupo_hour ch
JOIN operations.authority a ON a.authority_sk = ch.cupo_authority_fk
WHERE ch.cupo_flight_fk = ANY($1::int[])
`

type FlightCuposRow struct {
	FlightSk  int32          `json:"flight_sk"`
	Autoridad string         `json:"autoridad"`
	Horas     pgtype.Numeric `json:"horas"`
}

func (q *Queries) FlightCupos(ctx context.Context, dollar_1 []int32) ([]FlightCuposRow, error) {
	rows, err := q.db.Query(ctx, flightCupos, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightCuposRow
	for rows.Next() {
		var i FlightCuposRow
		if err := rows.Scan(&i.FlightSk, &i.Autoridad, &i.Horas); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const flightFormationHours = `-- name: FlightFormationHours :many
SELECT formation_hour_flight_fk AS flight_sk, formation_hour_person_fk AS person_sk,
       formation_hour_period_fk AS period_fk,
       COALESCE(formation_hour_formation_qty, 0)::numeric AS qty
FROM operations.formation_hour
WHERE formation_hour_flight_fk = ANY($1::int[])
`

type FlightFormationHoursRow struct {
	FlightSk int32          `json:"flight_sk"`
	PersonSk int32          `json:"person_sk"`
	PeriodFk int32          `json:"period_fk"`
	Qty      pgtype.Numeric `json:"qty"`
}

func (q *Queries) FlightFormationHours(ctx context.Context, dollar_1 []int32) ([]FlightFormationHoursRow, error) {
	rows, err := q.db.Query(ctx, flightFormationHours, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightFormationHoursRow
	for rows.Next() {
		var i FlightFormationHoursRow
		if err := rows.Scan(
			&i.FlightSk,
			&i.PersonSk,
			&i.PeriodFk,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const flightGvntypeHours = `-- name: FlightGvntypeHours :many
SELECT gvntype_hour_flight_fk AS flight_sk, gvntype_hour_person_fk AS person_sk,
       COALESCE(gvntype_hour_iit_qty, 0)::numeric AS iit,
       COALESCE(gvntype_hour_anvis_qty, 0)::numeric AS anvis
FROM operations.gvntype_hour
WHERE gvntype_hour_flight_fk = ANY($1::int[])
`

type FlightGvntypeHoursRow struct {
	FlightSk int32          `json:"flight_sk"`
	PersonSk int32          `json:"person_sk"`
	Iit      pgtype.Numeric `json:"iit"`
	Anvis    pgtype.Numeric `json:"anvis"`
}

func (q *Queries) FlightGvntypeHours(ctx context.Context, dollar_1 []int32) ([]FlightGvntypeHoursRow, error) {
	rows, err := q.db.Query(ctx, flightGvntypeHours, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightGvntypeHoursRow
	for rows.Next() {
		var i FlightGvntypeHoursRow
		if err := rows.Scan(
			&i.FlightSk,
			&i.PersonSk,
			&i.Iit,
			&i.Anvis,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const flightIftHours = `-- name: FlightIftHours :many
SELECT ift_hour_flight_fk AS flight_sk, ift_hour_person_fk AS person_sk,
       ift_hour_qty::numeric AS qty
FROM operations.ift_hour
WHERE ift_hour_flight_fk = ANY($1::int[])
`

type FlightIftHoursRow struct {
	FlightSk int32          `json:"flight_sk"`
	PersonSk int32          `json:"person_sk"`
	Qty      pgtype.Numeric `json:"qty"`
}

func (q *Queries) FlightIftHours(ctx context.Context, dollar_1 []int32) ([]FlightIftHoursRow, error) {
	rows, err := q.db.Query(ctx, flightIftHours, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightIftHoursRow
	for rows.Next() {
		var i FlightIftHoursRow
		if err := rows.Scan(&i.FlightSk, &i.PersonSk, &i.Qty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const flightInstructorHours = `-- name: FlightInstructorHours :many
SELECT instructor_hour_flight_fk AS flight_sk, instructor_hour_person_fk AS person_sk,
       instructor_hour_qty::numeric AS qty
FROM operations.instructor_hour
WHERE instructor_hour_flight_fk = ANY($1::int[])
`

type FlightInstructorHoursRow struct {
	FlightSk int32          `json:"flight_sk"`
	PersonSk int32          `json:"person_sk"`
	Qty      pgtype.Numeric `json:"qty"`
}

func (q *Queries) FlightInstructorHours(ctx context.Context, dollar_1 []int32) ([]FlightInstructorHoursRow, error) {
	rows, err := q.db.Query(ctx, flightInstructorHours, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightInstructorHoursRow
	for rows.Next() {
		var i FlightInstructorHoursRow
		if err := rows.Scan(&i.FlightSk, &i.PersonSk, &i.Qty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const flightLandings = `-- name: FlightLandings :many
SELECT landing_flight_fk AS flight_sk, landing_person_fk AS person_sk,
       landing_place_fk AS place_fk, landing_period_fk AS period_fk,
       landing_qty AS qty
FROM operations.landing
WHERE landing_flight_fk = ANY($1::int[])
`

type FlightLandingsRow struct {
	FlightSk int32 `json:"flight_sk"`
	PersonSk int32 `json:"person_sk"`
	PlaceFk  int32 `json:"place_fk"`
	PeriodFk int32 `json:"period_fk"`
	Qty      int32 `json:"qty"`
}

func (q *Queries) FlightLandings(ctx context.Context, dollar_1 []int32) ([]FlightLandingsRow, error) {
	rows, err := q.db.Query(ctx, flightLandings, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightLandingsRow
	for rows.Next() {
		var i FlightLandingsRow
		if err := rows.Scan(
			&i.FlightSk,
			&i.PersonSk,
			&i.PlaceFk,
			&i.PeriodFk,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const flightPapeletas = `-- name: FlightPapeletas :many
SELECT pcc.papeleta_crew_count_flight_fk  AS flight_sk,
       pcc.papeleta_crew_count_person_fk  AS person_sk,
       pap.papeleta_name                  AS nombre,
       pap.papeleta_description           AS descripcion,
       pcc.papeleta_crew_count_period_fk  AS periodo
FROM operations.papeleta_crew_count pcc
JOIN operations.papeleta pap ON pap.papeleta_sk = pcc.papeleta_crew_count_session_fk
WHERE pcc.papeleta_crew_count_flight_fk = ANY($1::int[])
`

type FlightPapeletasRow struct {
	FlightSk    int32  `json:"flight_sk"`
	PersonSk    int32  `json:"person_sk"`
	Nombre      string `json:"nombre"`
	Descripcion string `json:"descripcion"`
	Periodo     int32  `json:"periodo"`
}

func (q *Queries) FlightPapeletas(ctx context.Context, dollar_1 []int32) ([]FlightPapeletasRow, error) {
	rows, err := q.db.Query(ctx, flightPapeletas, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightPapeletasRow
	for rows.Next() {
		var i FlightPapeletasRow
		if err := rows.Scan(
			&i.FlightSk,
			&i.PersonSk,
			&i.Nombre,
			&i.Descripcion,
			&i.Periodo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const flightPassengers = `-- name: FlightPassengers :many
SELECT p.passenger_flight_fk AS flight_sk,
       pt.passenger_type_name AS tipo,
       p.passenger_qty AS cantidad,
       p.passenger_route AS ruta
FROM operations.passenger p
JOIN operations.passenger_type pt ON pt.passenger_type_sk = p.passenger_type_fk
WHERE p.passenger_flight_fk = ANY($1::int[])
`

type FlightPassengersRow struct {
	FlightSk int32  `json:"flight_sk"`
	Tipo     string `json:"tipo"`
	Cantidad int32  `json:"cantidad"`
	Ruta     string `json:"ruta"`
}

func (q *Queries) FlightPassengers(ctx context.Context, dollar_1 []int32) ([]FlightPassengersRow, error) {
	rows, err := q.db.Query(ctx, flightPassengers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightPassengersRow
	for rows.Next() {
		var i FlightPassengersRow
		if err := rows.Scan(
			&i.FlightSk,
			&i.Tipo,
			&i.Cantidad,
			&i.Ruta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const flightPersonHours = `-- name: FlightPersonHours :many
SELECT person_hour_flight_fk AS flight_sk, person_hour_person_fk AS person_sk,
       person_hour_period_fk AS period_fk, person_hour_hour_qty::numeric AS qty
FROM operations.person_hour
WHERE person_hour_flight_fk = ANY($1::int[])
`

type FlightPersonHoursRow struct {
	FlightSk int32          `json:"flight_sk"`
	PersonSk int32          `json:"person_sk"`
	PeriodFk int32          `json:"period_fk"`
	Qty      pgtype.Numeric `json:"qty"`
}

func (q *Queries) FlightPersonHours(ctx context.Context, dollar_1 []int32) ([]FlightPersonHoursRow, error) {
	rows, err := q.db.Query(ctx, flightPersonHours, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightPersonHoursRow
	for rows.Next() {
		var i FlightPersonHoursRow
		if err := rows.Scan(
			&i.FlightSk,
			&i.PersonSk,
			&i.PeriodFk,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const flightProjectiles = `-- name: FlightProjectiles :many
SELECT projectile_flight_fk AS flight_sk, projectile_person_fk AS person_sk,
       projectile_type_fk AS type_fk, projectile_qty AS qty
FROM operations.projectile
WHERE projectile_flight_fk = ANY($1::int[])
`

type FlightProjectilesRow struct {
	FlightSk int32 `json:"flight_sk"`
	PersonSk int32 `json:"person_sk"`
	TypeFk   int32 `json:"type_fk"`
	Qty      int32 `json:"qty"`
}

func (q *Queries) FlightProjectiles(ctx context.Context, dollar_1 []int32) ([]FlightProjectilesRow, error) {
	rows, err := q.db.Query(ctx, flightProjectiles, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightProjectilesRow
	for rows.Next() {
		var i FlightProjectilesRow
		if err := rows.Scan(
			&i.FlightSk,
			&i.PersonSk,
			&i.TypeFk,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const flightWtHours = `-- name: FlightWtHours :many
SELECT wt_hour_flight_fk AS flight_sk, wt_hour_person_fk AS person_sk,
       wt_hour_qty::numeric AS qty
FROM operations.wt_hour
WHERE wt_hour_flight_fk = ANY($1::int[])
`

type FlightWtHoursRow struct {
	FlightSk int32          `json:"flight_sk"`
	PersonSk int32          `json:"person_sk"`
	Qty      pgtype.Numeric `json:"qty"`
}

func (q *Queries) FlightWtHours(ctx context.Context, dollar_1 []int32) ([]FlightWtHoursRow, error) {
	rows, err := q.db.Query(ctx, flightWtHours, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightWtHoursRow
	for rows.Next() {
		var i FlightWtHoursRow
		if err := rows.Scan(&i.FlightSk, &i.PersonSk, &i.Qty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertApproach = `-- name: InsertApproach :exec
INSERT INTO operations.approach (
    app_flight_fk, app_person_fk, app_type_fk, app_qty
) VALUES ($1, $2, $3, $4)
`

type InsertApproachParams struct {
	AppFlightFk int32 `json:"app_flight_fk"`
	AppPersonFk int32 `json:"app_person_fk"`
	AppTypeFk   int32 `json:"app_type_fk"`
	AppQty      int32 `json:"app_qty"`
}

func (q *Queries) InsertApproach(ctx context.Context, arg InsertApproachParams) error {
	_, err := q.db.Exec(ctx, insertApproach,
		arg.AppFlightFk,
		arg.AppPersonFk,
		arg.AppTypeFk,
		arg.AppQty,
	)
	return err
}

const insertCupoHour = `-- name: InsertCupoHour :exec
INSERT INTO operations.cupo_hour (
    cupo_flight_fk, cupo_authority_fk, cupo_hour_qty
) VALUES ($1, $2, $3)
`

type InsertCupoHourParams struct {
	CupoFlightFk    int32          `json:"cupo_flight_fk"`
	CupoAuthorityFk int32          `json:"cupo_authority_fk"`
	CupoHourQty     pgtype.Numeric `json:"cupo_hour_qty"`
}

func (q *Queries) InsertCupoHour(ctx context.Context, arg InsertCupoHourParams) error {
	_, err := q.db.Exec(ctx, insertCupoHour, arg.CupoFlightFk, arg.CupoAuthorityFk, arg.CupoHourQty)
	return err
}

const insertFlight = `-- name: InsertFlight :one



INSERT INTO operations.flight (
    flight_date, flight_departure_place, flight_departure_time,
    flight_arrival_place, flight_arrival_time,
    flight_aircraft_fk, flight_event_fk, flight_person_cta_fk,
    flight_escuadrilla_fk, flight_total_hours
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING flight_sk
`

type InsertFlightParams struct {
	FlightDate           pgtype.Date    `json:"flight_date"`
	FlightDeparturePlace int32          `json:"flight_departure_place"`
	FlightDepartureTime  pgtype.Time    `json:"flight_departure_time"`
	FlightArrivalPlace   int32          `json:"flight_arrival_place"`
	FlightArrivalTime    pgtype.Time    `json:"flight_arrival_time"`
	FlightAircraftFk     int32          `json:"flight_aircraft_fk"`
	FlightEventFk        int32          `json:"flight_event_fk"`
	FlightPersonCtaFk    int32          `json:"flight_person_cta_fk"`
	FlightEscuadrillaFk  int32          `json:"flight_escuadrilla_fk"`
	FlightTotalHours     pgtype.Numeric `json:"flight_total_hours"`
}

// ============================================================
// Flights (Hito 4, lote 7)
//
// Reimplementa db_insert_flight (transacción con ~10 tablas hijas),
// db_delete_flight y sp_get_flights_with_flexible_crew.
//
// Convenciones de SK (del seed/legacy):
//
//	period:        1=día, 2=noche, 3=gvn
//	ifr_app_type:  1=precision, 2=no_precision, 3=td, 4=sp
//	landing_place: 1=tierra, 2=mono-spot, 3=multi-spot, 4=carrier
//	projectile:    1=m3m, 2=mag58
//
// ============================================================
// =============== INSERT MASTER + DEPENDIENTES ===============
func (q *Queries) InsertFlight(ctx context.Context, arg InsertFlightParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertFlight,
		arg.FlightDate,
		arg.FlightDeparturePlace,
		arg.FlightDepartureTime,
		arg.FlightArrivalPlace,
		arg.FlightArrivalTime,
		arg.FlightAircraftFk,
		arg.FlightEventFk,
		arg.FlightPersonCtaFk,
		arg.FlightEscuadrillaFk,
		arg.FlightTotalHours,
	)
	var flight_sk int32
	err := row.Scan(&flight_sk)
	return flight_sk, err
}

const insertFormationHour = `-- name: InsertFormationHour :exec
INSERT INTO operations.formation_hour (
    formation_hour_flight_fk, formation_hour_person_fk,
    formation_hour_period_fk, formation_hour_formation_qty
) VALUES ($1, $2, $3, $4)
`

type InsertFormationHourParams struct {
	FormationHourFlightFk     int32          `json:"formation_hour_flight_fk"`
	FormationHourPersonFk     int32          `json:"formation_hour_person_fk"`
	FormationHourPeriodFk     int32          `json:"formation_hour_period_fk"`
	FormationHourFormationQty pgtype.Numeric `json:"formation_hour_formation_qty"`
}

func (q *Queries) InsertFormationHour(ctx context.Context, arg InsertFormationHourParams) error {
	_, err := q.db.Exec(ctx, insertFormationHour,
		arg.FormationHourFlightFk,
		arg.FormationHourPersonFk,
		arg.FormationHourPeriodFk,
		arg.FormationHourFormationQty,
	)
	return err
}

const insertGvntypeHour = `-- name: InsertGvntypeHour :exec
INSERT INTO operations.gvntype_hour (
    gvntype_hour_flight_fk, gvntype_hour_person_fk,
    gvntype_hour_iit_qty, gvntype_hour_anvis_qty
) VALUES ($1, $2, $3, $4)
`

type InsertGvntypeHourParams struct {
	GvntypeHourFlightFk int32          `json:"gvntype_hour_flight_fk"`
	GvntypeHourPersonFk int32          `json:"gvntype_hour_person_fk"`
	GvntypeHourIitQty   pgtype.Numeric `json:"gvntype_hour_iit_qty"`
	GvntypeHourAnvisQty pgtype.Numeric `json:"gvntype_hour_anvis_qty"`
}

func (q *Queries) InsertGvntypeHour(ctx context.Context, arg InsertGvntypeHourParams) error {
	_, err := q.db.Exec(ctx, insertGvntypeHour,
		arg.GvntypeHourFlightFk,
		arg.GvntypeHourPersonFk,
		arg.GvntypeHourIitQty,
		arg.GvntypeHourAnvisQty,
	)
	return err
}

const insertIftHour = `-- name: InsertIftHour :exec
INSERT INTO operations.ift_hour (
    ift_hour_flight_fk, ift_hour_person_fk, ift_hour_qty
) VALUES ($1, $2, $3)
`

type InsertIftHourParams struct {
	IftHourFlightFk int32          `json:"ift_hour_flight_fk"`
	IftHourPersonFk int32          `json:"ift_hour_person_fk"`
	IftHourQty      pgtype.Numeric `json:"ift_hour_qty"`
}

func (q *Queries) InsertIftHour(ctx context.Context, arg InsertIftHourParams) error {
	_, err := q.db.Exec(ctx, insertIftHour, arg.IftHourFlightFk, arg.IftHourPersonFk, arg.IftHourQty)
	return err
}

const insertInstructorHour = `-- name: InsertInstructorHour :exec
INSERT INTO operations.instructor_hour (
    instructor_hour_flight_fk, instructor_hour_person_fk, instructor_hour_qty
) VALUES ($1, $2, $3)
`

type InsertInstructorHourParams struct {
	InstructorHourFlightFk int32          `json:"instructor_hour_flight_fk"`
	InstructorHourPersonFk int32          `json:"instructor_hour_person_fk"`
	InstructorHourQty      pgtype.Numeric `json:"instructor_hour_qty"`
}

func (q *Queries) InsertInstructorHour(ctx context.Context, arg InsertInstructorHourParams) error {
	_, err := q.db.Exec(ctx, insertInstructorHour, arg.InstructorHourFlightFk, arg.InstructorHourPersonFk, arg.InstructorHourQty)
	return err
}

const insertLanding = `-- name: InsertLanding :exec
INSERT INTO operations.landing (
    landing_flight_fk, landing_person_fk,
    landing_place_fk, landing_period_fk, landing_qty
) VALUES ($1, $2, $3, $4, $5)
`

type InsertLandingParams struct {
	LandingFlightFk int32 `json:"landing_flight_fk"`
	LandingPersonFk int32 `json:"landing_person_fk"`
	LandingPlaceFk  int32 `json:"landing_place_fk"`
	LandingPeriodFk int32 `json:"landing_period_fk"`
	LandingQty      int32 `json:"landing_qty"`
}

func (q *Queries) InsertLanding(ctx context.Context, arg InsertLandingParams) error {
	_, err := q.db.Exec(ctx, insertLanding,
		arg.LandingFlightFk,
		arg.LandingPersonFk,
		arg.LandingPlaceFk,
		arg.LandingPeriodFk,
		arg.LandingQty,
	)
	return err
}

const insertPapeletaCrewCount = `-- name: InsertPapeletaCrewCount :exec
INSERT INTO operations.papeleta_crew_count (
    papeleta_crew_count_flight_fk, papeleta_crew_count_person_fk,
    papeleta_crew_count_session_fk, papeleta_crew_count_period_fk
) VALUES ($1, $2, $3, $4)
`

type InsertPapeletaCrewCountParams struct {
	PapeletaCrewCountFlightFk  int32 `json:"papeleta_crew_count_flight_fk"`
	PapeletaCrewCountPersonFk  int32 `json:"papeleta_crew_count_person_fk"`
	PapeletaCrewCountSessionFk int32 `json:"papeleta_crew_count_session_fk"`
	PapeletaCrewCountPeriodFk  int32 `json:"papeleta_crew_count_period_fk"`
}

func (q *Queries) InsertPapeletaCrewCount(ctx context.Context, arg InsertPapeletaCrewCountParams) error {
	_, err := q.db.Exec(ctx, insertPapeletaCrewCount,
		arg.PapeletaCrewCountFlightFk,
		arg.PapeletaCrewCountPersonFk,
		arg.PapeletaCrewCountSessionFk,
		arg.PapeletaCrewCountPeriodFk,
	)
	return err
}

const insertPassenger = `-- name: InsertPassenger :exec
INSERT INTO operations.passenger (
    passenger_flight_fk, passenger_type_fk, passenger_qty, passenger_route
) VALUES ($1, $2, $3, $4)
`

type InsertPassengerParams struct {
	PassengerFlightFk int32  `json:"passenger_flight_fk"`
	PassengerTypeFk   int32  `json:"passenger_type_fk"`
	PassengerQty      int32  `json:"passenger_qty"`
	PassengerRoute    string `json:"passenger_route"`
}

func (q *Queries) InsertPassenger(ctx context.Context, arg InsertPassengerParams) error {
	_, err := q.db.Exec(ctx, insertPassenger,
		arg.PassengerFlightFk,
		arg.PassengerTypeFk,
		arg.PassengerQty,
		arg.PassengerRoute,
	)
	return err
}

const insertPersonHour = `-- name: InsertPersonHour :exec
INSERT INTO operations.person_hour (
    person_hour_flight_fk, person_hour_person_fk,
    person_hour_period_fk, person_hour_hour_qty
) VALUES ($1, $2, $3, $4)
`

type InsertPersonHourParams struct {
	PersonHourFlightFk int32          `json:"person_hour_flight_fk"`
	PersonHourPersonFk int32          `json:"person_hour_person_fk"`
	PersonHourPeriodFk int32          `json:"person_hour_period_fk"`
	PersonHourHourQty  pgtype.Numeric `json:"person_hour_hour_qty"`
}

func (q *Queries) InsertPersonHour(ctx context.Context, arg InsertPersonHourParams) error {
	_, err := q.db.Exec(ctx, insertPersonHour,
		arg.PersonHourFlightFk,
		arg.PersonHourPersonFk,
		arg.PersonHourPeriodFk,
		arg.PersonHourHourQty,
	)
	return err
}

const insertProjectile = `-- name: InsertProjectile :exec
INSERT INTO operations.projectile (
    projectile_flight_fk, projectile_person_fk,
    projectile_type_fk, projectile_qty
) VALUES ($1, $2, $3, $4)
`

type InsertProjectileParams struct {
	ProjectileFlightFk int32 `json:"projectile_flight_fk"`
	ProjectilePersonFk int32 `json:"projectile_person_fk"`
	ProjectileTypeFk   int32 `json:"projectile_type_fk"`
	ProjectileQty      int32 `json:"projectile_qty"`
}

func (q *Queries) InsertProjectile(ctx context.Context, arg InsertProjectileParams) error {
	_, err := q.db.Exec(ctx, insertProjectile,
		arg.ProjectileFlightFk,
		arg.ProjectilePersonFk,
		arg.ProjectileTypeFk,
		arg.ProjectileQty,
	)
	return err
}

const insertWtHour = `-- name: InsertWtHour :exec
INSERT INTO operations.wt_hour (
    wt_hour_flight_fk, wt_hour_person_fk, wt_hour_qty
) VALUES ($1, $2, $3)
`

type InsertWtHourParams struct {
	WtHourFlightFk int32          `json:"wt_hour_flight_fk"`
	WtHourPersonFk int32          `json:"wt_hour_person_fk"`
	WtHourQty      pgtype.Numeric `json:"wt_hour_qty"`
}

func (q *Queries) InsertWtHour(ctx context.Context, arg InsertWtHourParams) error {
	_, err := q.db.Exec(ctx, insertWtHour, arg.WtHourFlightFk, arg.WtHourPersonFk, arg.WtHourQty)
	return err
}

const listFlights = `-- name: ListFlights :many

SELECT
    f.flight_sk,
    f.flight_date,
    f.flight_departure_time,
    f.flight_total_hours,
    h.aircraft_number,
    e.event_name,
    e.event_place,
    cta.person_rank        AS cta_rank,
    cta.person_last_name_1 AS cta_lastname1,
    cta.person_last_name_2 AS cta_lastname2
FROM operations.flight f
JOIN operations.aircraft h  ON f.flight_aircraft_fk = h.aircraft_sk
JOIN operations.event    e  ON f.flight_event_fk    = e.event_sk
JOIN detall.person       cta ON f.flight_person_cta_fk = cta.person_sk
WHERE f.flight_escuadrilla_fk = $1
  AND ($2 = 0 OR f.flight_sk = $2)
  AND ($3::date IS NULL OR f.flight_date >= $3)
  AND ($4::date IS NULL OR f.flight_date <= $4)
ORDER BY f.flight_date DESC, f.flight_sk DESC
LIMIT $5 OFFSET $6
`

type ListFlightsParams struct {
	FlightEscuadrillaFk int32       `json:"flight_escuadrilla_fk"`
	Column2             interface{} `json:"column_2"`
	Column3             pgtype.Date `json:"column_3"`
	Column4             pgtype.Date `json:"column_4"`
	Limit               int32       `json:"limit"`
	Offset              int32       `json:"offset"`
}

type ListFlightsRow struct {
	FlightSk            int32          `json:"flight_sk"`
	FlightDate          pgtype.Date    `json:"flight_date"`
	FlightDepartureTime pgtype.Time    `json:"flight_departure_time"`
	FlightTotalHours    pgtype.Numeric `json:"flight_total_hours"`
	AircraftNumber      string         `json:"aircraft_number"`
	EventName           string         `json:"event_name"`
	EventPlace          string         `json:"event_place"`
	CtaRank             string         `json:"cta_rank"`
	CtaLastname1        string         `json:"cta_lastname1"`
	CtaLastname2        string         `json:"cta_lastname2"`
}

// =============== LIST (sp_get_flights_with_flexible_crew) ===============
// Paginado + filtros opcionales. $2 = flight_sk (0=sin filtro), $3/$4 = date_from/to (NULL=sin filtro).
func (q *Queries) ListFlights(ctx context.Context, arg ListFlightsParams) ([]ListFlightsRow, error) {
	rows, err := q.db.Query(ctx, listFlights,
		arg.FlightEscuadrillaFk,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlightsRow
	for rows.Next() {
		var i ListFlightsRow
		if err := rows.Scan(
			&i.FlightSk,
			&i.FlightDate,
			&i.FlightDepartureTime,
			&i.FlightTotalHours,
			&i.AircraftNumber,
			&i.EventName,
			&i.EventPlace,
			&i.CtaRank,
			&i.CtaLastname1,
			&i.CtaLastname2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
