// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fuel.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFuel = `-- name: CountFuel :one
SELECT COUNT(*)::int AS total
FROM operations.fuel f
JOIN operations.aircraft a ON a.aircraft_sk = f.fuel_helo_fk
WHERE a.aircraft_escuadrilla_fk = $1
  AND ($2 = 0 OR f.fuel_sk = $2)
  AND ($2 <> 0 OR f.fuel_date BETWEEN $3 AND $4)
`

type CountFuelParams struct {
	AircraftEscuadrillaFk int32       `json:"aircraft_escuadrilla_fk"`
	Column2               interface{} `json:"column_2"`
	FuelDate              pgtype.Date `json:"fuel_date"`
	FuelDate_2            pgtype.Date `json:"fuel_date_2"`
}

// Número de repostajes con el mismo filtro que ListFuel.
func (q *Queries) CountFuel(ctx context.Context, arg CountFuelParams) (int32, error) {
	row := q.db.QueryRow(ctx, countFuel,
		arg.AircraftEscuadrillaFk,
		arg.Column2,
		arg.FuelDate,
		arg.FuelDate_2,
	)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const deleteFuel = `-- name: DeleteFuel :execrows
DELETE FROM operations.fuel f
USING operations.aircraft a
WHERE f.fuel_sk = $1
  AND a.aircraft_sk = f.fuel_helo_fk
  AND a.aircraft_escuadrilla_fk = $2
`

type DeleteFuelParams struct {
	FuelSk                int32 `json:"fuel_sk"`
	AircraftEscuadrillaFk int32 `json:"aircraft_escuadrilla_fk"`
}

// Borra un repostaje solo si su aeronave pertenece a la escuadrilla ($2).
func (q *Queries) DeleteFuel(ctx context.Context, arg DeleteFuelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFuel, arg.FuelSk, arg.AircraftEscuadrillaFk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fuelDetailGrouped = `-- name: FuelDetailGrouped :many

SELECT
    pay.fuel_payer_assignment_type_abbrev AS payer,
    e.event_name        AS event,
    ph.fuel_phase       AS phase,
    fp.fuel_place_name  AS place_name,
    fp.fuel_place_type  AS place_type,
    SUM(f.fuel_qty)::float8 AS qty
FROM operations.fuel f
JOIN operations.aircraft a     ON a.aircraft_sk = f.fuel_helo_fk
JOIN operations.fuel_payer pay ON pay.fuel_payer_sk = f.fuel_payer_fk
JOIN operations.event e        ON e.event_sk = f.fuel_event_fk
JOIN operations.fuel_phase ph  ON ph.fuel_phase_sk = f.fuel_phase_fk
JOIN operations.fuel_place fp  ON fp.fuel_place_sk = f.fuel_place_fk
WHERE a.aircraft_escuadrilla_fk = $1
  AND f.fuel_date BETWEEN $2 AND $3
GROUP BY pay.fuel_payer_assignment_type_abbrev, e.event_name,
         ph.fuel_phase, ph.fuel_phase_sk, fp.fuel_place_name, fp.fuel_place_type
ORDER BY pay.fuel_payer_assignment_type_abbrev, e.event_name, ph.fuel_phase_sk, fp.fuel_place_name
`

type FuelDetailGroupedParams struct {
	AircraftEscuadrillaFk int32       `json:"aircraft_escuadrilla_fk"`
	FuelDate              pgtype.Date `json:"fuel_date"`
	FuelDate_2            pgtype.Date `json:"fuel_date_2"`
}

type FuelDetailGroupedRow struct {
	Payer     string  `json:"payer"`
	Event     string  `json:"event"`
	Phase     string  `json:"phase"`
	PlaceName string  `json:"place_name"`
	PlaceType string  `json:"place_type"`
	Qty       float64 `json:"qty"`
}

// ============================================================
// Resumen del mes. Todas acotadas a la escuadrilla ($1) vía la aeronave y al
// rango del mes ($2/$3).
// ============================================================
// Detalle agregado del mes por (pagador, evento, fase, lugar). El servicio lo
// agrupa por pagador (subtotal) para el informe seccionado. phase_sk ordena las
// fases por el catálogo (Preparación antes que Ejecución).
func (q *Queries) FuelDetailGrouped(ctx context.Context, arg FuelDetailGroupedParams) ([]FuelDetailGroupedRow, error) {
	rows, err := q.db.Query(ctx, fuelDetailGrouped, arg.AircraftEscuadrillaFk, arg.FuelDate, arg.FuelDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FuelDetailGroupedRow
	for rows.Next() {
		var i FuelDetailGroupedRow
		if err := rows.Scan(
			&i.Payer,
			&i.Event,
			&i.Phase,
			&i.PlaceName,
			&i.PlaceType,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFuel = `-- name: InsertFuel :one
INSERT INTO operations.fuel (
    fuel_date, fuel_helo_fk, fuel_place_fk, fuel_payer_fk,
    fuel_event_fk, fuel_phase_fk, fuel_type_fk, fuel_qty
)
SELECT $1, $2, $3, $4, $5, $6, $7, $8
WHERE EXISTS (
    SELECT 1 FROM operations.aircraft
    WHERE aircraft_sk = $2 AND aircraft_escuadrilla_fk = $9
)
RETURNING fuel_sk
`

type InsertFuelParams struct {
	FuelDate              pgtype.Date    `json:"fuel_date"`
	FuelHeloFk            int32          `json:"fuel_helo_fk"`
	FuelPlaceFk           int32          `json:"fuel_place_fk"`
	FuelPayerFk           int32          `json:"fuel_payer_fk"`
	FuelEventFk           int32          `json:"fuel_event_fk"`
	FuelPhaseFk           int32          `json:"fuel_phase_fk"`
	FuelTypeFk            int32          `json:"fuel_type_fk"`
	FuelQty               pgtype.Numeric `json:"fuel_qty"`
	AircraftEscuadrillaFk int32          `json:"aircraft_escuadrilla_fk"`
}

// Inserta solo si la aeronave ($2) pertenece a la escuadrilla de la sesión ($9);
// si no, no inserta ninguna fila (RETURNING vacío → ErrNoRows en el service).
func (q *Queries) InsertFuel(ctx context.Context, arg InsertFuelParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertFuel,
		arg.FuelDate,
		arg.FuelHeloFk,
		arg.FuelPlaceFk,
		arg.FuelPayerFk,
		arg.FuelEventFk,
		arg.FuelPhaseFk,
		arg.FuelTypeFk,
		arg.FuelQty,
		arg.AircraftEscuadrillaFk,
	)
	var fuel_sk int32
	err := row.Scan(&fuel_sk)
	return fuel_sk, err
}

const listFuel = `-- name: ListFuel :many

SELECT
    f.fuel_sk,
    f.fuel_date,
    f.fuel_helo_fk,
    a.aircraft_number,
    f.fuel_place_fk,
    fp.fuel_place_name,
    fp.fuel_place_type,
    f.fuel_payer_fk,
    pay.fuel_payer_assignment_type_abbrev,
    pay.fuel_payer_name,
    f.fuel_event_fk,
    e.event_name,
    e.event_place,
    f.fuel_phase_fk,
    ph.fuel_phase,
    f.fuel_type_fk,
    ft.fuel_type,
    f.fuel_qty::float8 AS fuel_qty
FROM operations.fuel f
JOIN operations.aircraft a    ON a.aircraft_sk = f.fuel_helo_fk
JOIN operations.fuel_place fp ON fp.fuel_place_sk = f.fuel_place_fk
JOIN operations.fuel_payer pay ON pay.fuel_payer_sk = f.fuel_payer_fk
JOIN operations.event e       ON e.event_sk = f.fuel_event_fk
JOIN operations.fuel_phase ph ON ph.fuel_phase_sk = f.fuel_phase_fk
JOIN operations.fuel_type ft  ON ft.fuel_type_sk = f.fuel_type_fk
WHERE a.aircraft_escuadrilla_fk = $1
  AND ($2 = 0 OR f.fuel_sk = $2)
  AND ($2 <> 0 OR f.fuel_date BETWEEN $3 AND $4)
ORDER BY f.fuel_date DESC, f.fuel_sk DESC
LIMIT $5 OFFSET $6
`

type ListFuelParams struct {
	AircraftEscuadrillaFk int32       `json:"aircraft_escuadrilla_fk"`
	Column2               interface{} `json:"column_2"`
	FuelDate              pgtype.Date `json:"fuel_date"`
	FuelDate_2            pgtype.Date `json:"fuel_date_2"`
	Limit                 int32       `json:"limit"`
	Offset                int32       `json:"offset"`
}

type ListFuelRow struct {
	FuelSk                        int32       `json:"fuel_sk"`
	FuelDate                      pgtype.Date `json:"fuel_date"`
	FuelHeloFk                    int32       `json:"fuel_helo_fk"`
	AircraftNumber                string      `json:"aircraft_number"`
	FuelPlaceFk                   int32       `json:"fuel_place_fk"`
	FuelPlaceName                 string      `json:"fuel_place_name"`
	FuelPlaceType                 string      `json:"fuel_place_type"`
	FuelPayerFk                   int32       `json:"fuel_payer_fk"`
	FuelPayerAssignmentTypeAbbrev string      `json:"fuel_payer_assignment_type_abbrev"`
	FuelPayerName                 string      `json:"fuel_payer_name"`
	FuelEventFk                   int32       `json:"fuel_event_fk"`
	EventName                     string      `json:"event_name"`
	EventPlace                    string      `json:"event_place"`
	FuelPhaseFk                   int32       `json:"fuel_phase_fk"`
	FuelPhase                     string      `json:"fuel_phase"`
	FuelTypeFk                    int32       `json:"fuel_type_fk"`
	FuelType                      string      `json:"fuel_type"`
	FuelQty                       float64     `json:"fuel_qty"`
}

// ============================================================
// Combustible (operations.fuel) — repostajes
//
// Cada fila es un repostaje: fecha, aeronave (helo), lugar, pagador, evento,
// fase, tipo de combustible y cantidad (litros). Los catálogos (fuel_place,
// fuel_payer, fuel_phase, fuel_type) son globales; operations.event también.
//
// RLS por código: operations.fuel NO tiene escuadrilla_fk. El aislamiento se
// hace vía la aeronave del repostaje (fuel_helo_fk → operations.aircraft.
// aircraft_escuadrilla_fk = $N). Todas las sentencias de abajo lo aplican, por
// lo que quedan acotadas a aeronaves de la escuadrilla de la sesión.
// ============================================================
// Lista paginada de repostajes, acotada a la escuadrilla de la sesión ($1) vía
// la aeronave. Si $2 (fuel_sk) != 0 busca ese registro concreto (ignorando el
// mes); si $2 = 0 filtra por el rango del mes seleccionado ($3/$4). Devuelve
// etiquetas resueltas + los *_fk (para precargar el formulario de edición).
func (q *Queries) ListFuel(ctx context.Context, arg ListFuelParams) ([]ListFuelRow, error) {
	rows, err := q.db.Query(ctx, listFuel,
		arg.AircraftEscuadrillaFk,
		arg.Column2,
		arg.FuelDate,
		arg.FuelDate_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFuelRow
	for rows.Next() {
		var i ListFuelRow
		if err := rows.Scan(
			&i.FuelSk,
			&i.FuelDate,
			&i.FuelHeloFk,
			&i.AircraftNumber,
			&i.FuelPlaceFk,
			&i.FuelPlaceName,
			&i.FuelPlaceType,
			&i.FuelPayerFk,
			&i.FuelPayerAssignmentTypeAbbrev,
			&i.FuelPayerName,
			&i.FuelEventFk,
			&i.EventName,
			&i.EventPlace,
			&i.FuelPhaseFk,
			&i.FuelPhase,
			&i.FuelTypeFk,
			&i.FuelType,
			&i.FuelQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFuel = `-- name: UpdateFuel :execrows
UPDATE operations.fuel f
SET fuel_date     = $2,
    fuel_helo_fk  = $3,
    fuel_place_fk = $4,
    fuel_payer_fk = $5,
    fuel_event_fk = $6,
    fuel_phase_fk = $7,
    fuel_type_fk  = $8,
    fuel_qty      = $9
FROM operations.aircraft a
WHERE f.fuel_sk = $1
  AND a.aircraft_sk = f.fuel_helo_fk
  AND a.aircraft_escuadrilla_fk = $10
  AND EXISTS (
      SELECT 1 FROM operations.aircraft a2
      WHERE a2.aircraft_sk = $3 AND a2.aircraft_escuadrilla_fk = $10
  )
`

type UpdateFuelParams struct {
	FuelSk                int32          `json:"fuel_sk"`
	FuelDate              pgtype.Date    `json:"fuel_date"`
	FuelHeloFk            int32          `json:"fuel_helo_fk"`
	FuelPlaceFk           int32          `json:"fuel_place_fk"`
	FuelPayerFk           int32          `json:"fuel_payer_fk"`
	FuelEventFk           int32          `json:"fuel_event_fk"`
	FuelPhaseFk           int32          `json:"fuel_phase_fk"`
	FuelTypeFk            int32          `json:"fuel_type_fk"`
	FuelQty               pgtype.Numeric `json:"fuel_qty"`
	AircraftEscuadrillaFk int32          `json:"aircraft_escuadrilla_fk"`
}

// Actualiza un repostaje, acotado a aeronaves de la escuadrilla de la sesión
// ($10): tanto la fila actual como la nueva aeronave ($3) deben pertenecer a
// la escuadrilla.
func (q *Queries) UpdateFuel(ctx context.Context, arg UpdateFuelParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFuel,
		arg.FuelSk,
		arg.FuelDate,
		arg.FuelHeloFk,
		arg.FuelPlaceFk,
		arg.FuelPayerFk,
		arg.FuelEventFk,
		arg.FuelPhaseFk,
		arg.FuelTypeFk,
		arg.FuelQty,
		arg.AircraftEscuadrillaFk,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
