// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lookups.sql

package queries

import (
	"context"
)

const addAircraft = `-- name: AddAircraft :exec
INSERT INTO operations.aircraft (
    aircraft_type, aircraft_make, aircraft_model, aircraft_variant,
    aircraft_registration, aircraft_number, aircraft_current_flag,
    aircraft_is_multi_engine, aircraft_is_multi_pilot, aircraft_escuadrilla_fk
) VALUES ($1, $2, $3, $4, $5, $6, TRUE, $7, $8, $9)
`

type AddAircraftParams struct {
	AircraftType          string `json:"aircraft_type"`
	AircraftMake          string `json:"aircraft_make"`
	AircraftModel         string `json:"aircraft_model"`
	AircraftVariant       string `json:"aircraft_variant"`
	AircraftRegistration  string `json:"aircraft_registration"`
	AircraftNumber        string `json:"aircraft_number"`
	AircraftIsMultiEngine bool   `json:"aircraft_is_multi_engine"`
	AircraftIsMultiPilot  bool   `json:"aircraft_is_multi_pilot"`
	AircraftEscuadrillaFk int32  `json:"aircraft_escuadrilla_fk"`
}

func (q *Queries) AddAircraft(ctx context.Context, arg AddAircraftParams) error {
	_, err := q.db.Exec(ctx, addAircraft,
		arg.AircraftType,
		arg.AircraftMake,
		arg.AircraftModel,
		arg.AircraftVariant,
		arg.AircraftRegistration,
		arg.AircraftNumber,
		arg.AircraftIsMultiEngine,
		arg.AircraftIsMultiPilot,
		arg.AircraftEscuadrillaFk,
	)
	return err
}

const addDepartureArrivalPlace = `-- name: AddDepartureArrivalPlace :exec

INSERT INTO operations.departure_arrival_place (departure_arrival_place_code, departure_arrival_place_name)
VALUES ($1, $2)
`

type AddDepartureArrivalPlaceParams struct {
	DepartureArrivalPlaceCode string `json:"departure_arrival_place_code"`
	DepartureArrivalPlaceName string `json:"departure_arrival_place_name"`
}

// =============== Mutaciones ===============
// code se normaliza a uppercase en Go.
func (q *Queries) AddDepartureArrivalPlace(ctx context.Context, arg AddDepartureArrivalPlaceParams) error {
	_, err := q.db.Exec(ctx, addDepartureArrivalPlace, arg.DepartureArrivalPlaceCode, arg.DepartureArrivalPlaceName)
	return err
}

const addEvent = `-- name: AddEvent :exec
INSERT INTO operations.event (event_name, event_place) VALUES ($1, $2)
`

type AddEventParams struct {
	EventName  string `json:"event_name"`
	EventPlace string `json:"event_place"`
}

func (q *Queries) AddEvent(ctx context.Context, arg AddEventParams) error {
	_, err := q.db.Exec(ctx, addEvent, arg.EventName, arg.EventPlace)
	return err
}

const deleteAircraft = `-- name: DeleteAircraft :execrows
DELETE FROM operations.aircraft
WHERE aircraft_sk = $1 AND aircraft_escuadrilla_fk = $2
`

type DeleteAircraftParams struct {
	AircraftSk            int32 `json:"aircraft_sk"`
	AircraftEscuadrillaFk int32 `json:"aircraft_escuadrilla_fk"`
}

func (q *Queries) DeleteAircraft(ctx context.Context, arg DeleteAircraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAircraft, arg.AircraftSk, arg.AircraftEscuadrillaFk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDepartureArrivalPlace = `-- name: DeleteDepartureArrivalPlace :execrows
DELETE FROM operations.departure_arrival_place WHERE departure_arrival_place_sk = $1
`

func (q *Queries) DeleteDepartureArrivalPlace(ctx context.Context, departureArrivalPlaceSk int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDepartureArrivalPlace, departureArrivalPlaceSk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEvent = `-- name: DeleteEvent :execrows
DELETE FROM operations.event WHERE event_sk = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, eventSk int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEvent, eventSk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lookupAircrafts = `-- name: LookupAircrafts :many



SELECT aircraft_sk, aircraft_number
FROM operations.aircraft
WHERE aircraft_current_flag = TRUE
  AND aircraft_escuadrilla_fk = $1
ORDER BY aircraft_number
`

type LookupAircraftsRow struct {
	AircraftSk     int32  `json:"aircraft_sk"`
	AircraftNumber string `json:"aircraft_number"`
}

// ============================================================
// Lookups (Hito 4, lote 1)
//
// Traducción de src-tauri/src/database/commands/lookups.rs (29 fns).
// RLS explícita: $1 = escuadrilla_id en cada query que lo necesita.
// ============================================================
// =============== Reads: catálogos para selectores (sk + label) ===============
// get_aircrafts (frontend): selector de aeronaves activas.
func (q *Queries) LookupAircrafts(ctx context.Context, aircraftEscuadrillaFk int32) ([]LookupAircraftsRow, error) {
	rows, err := q.db.Query(ctx, lookupAircrafts, aircraftEscuadrillaFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupAircraftsRow
	for rows.Next() {
		var i LookupAircraftsRow
		if err := rows.Scan(&i.AircraftSk, &i.AircraftNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupAircraftsManage = `-- name: LookupAircraftsManage :many
SELECT aircraft_sk, aircraft_registration, aircraft_number, aircraft_current_flag,
       aircraft_type, aircraft_make, aircraft_model, aircraft_variant,
       aircraft_is_multi_engine, aircraft_is_multi_pilot
FROM operations.aircraft
WHERE aircraft_escuadrilla_fk = $1
ORDER BY aircraft_number
`

type LookupAircraftsManageRow struct {
	AircraftSk            int32  `json:"aircraft_sk"`
	AircraftRegistration  string `json:"aircraft_registration"`
	AircraftNumber        string `json:"aircraft_number"`
	AircraftCurrentFlag   bool   `json:"aircraft_current_flag"`
	AircraftType          string `json:"aircraft_type"`
	AircraftMake          string `json:"aircraft_make"`
	AircraftModel         string `json:"aircraft_model"`
	AircraftVariant       string `json:"aircraft_variant"`
	AircraftIsMultiEngine bool   `json:"aircraft_is_multi_engine"`
	AircraftIsMultiPilot  bool   `json:"aircraft_is_multi_pilot"`
}

// get_aircrafts_manage: vista completa para gestión.
func (q *Queries) LookupAircraftsManage(ctx context.Context, aircraftEscuadrillaFk int32) ([]LookupAircraftsManageRow, error) {
	rows, err := q.db.Query(ctx, lookupAircraftsManage, aircraftEscuadrillaFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupAircraftsManageRow
	for rows.Next() {
		var i LookupAircraftsManageRow
		if err := rows.Scan(
			&i.AircraftSk,
			&i.AircraftRegistration,
			&i.AircraftNumber,
			&i.AircraftCurrentFlag,
			&i.AircraftType,
			&i.AircraftMake,
			&i.AircraftModel,
			&i.AircraftVariant,
			&i.AircraftIsMultiEngine,
			&i.AircraftIsMultiPilot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupAuthorities = `-- name: LookupAuthorities :many
SELECT authority_sk, authority_name
FROM operations.authority
ORDER BY authority_name
`

type LookupAuthoritiesRow struct {
	AuthoritySk   int32  `json:"authority_sk"`
	AuthorityName string `json:"authority_name"`
}

func (q *Queries) LookupAuthorities(ctx context.Context) ([]LookupAuthoritiesRow, error) {
	rows, err := q.db.Query(ctx, lookupAuthorities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupAuthoritiesRow
	for rows.Next() {
		var i LookupAuthoritiesRow
		if err := rows.Scan(&i.AuthoritySk, &i.AuthorityName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupComisionLugares = `-- name: LookupComisionLugares :many
SELECT comision_lugar_sk, comision_name
FROM detall.comision_lugar
ORDER BY comision_name
`

func (q *Queries) LookupComisionLugares(ctx context.Context) ([]DetallComisionLugar, error) {
	rows, err := q.db.Query(ctx, lookupComisionLugares)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DetallComisionLugar
	for rows.Next() {
		var i DetallComisionLugar
		if err := rows.Scan(&i.ComisionLugarSk, &i.ComisionName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupComisionTypes = `-- name: LookupComisionTypes :many
SELECT comision_type_sk, name, origin
FROM detall.comision_type
ORDER BY origin
`

func (q *Queries) LookupComisionTypes(ctx context.Context) ([]DetallComisionType, error) {
	rows, err := q.db.Query(ctx, lookupComisionTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DetallComisionType
	for rows.Next() {
		var i DetallComisionType
		if err := rows.Scan(&i.ComisionTypeSk, &i.Name, &i.Origin); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupCrew = `-- name: LookupCrew :many
SELECT person_sk, person_nk
FROM detall.v_person_ordered
WHERE person_rol NOT IN ('Piloto', 'No Tripulante')
  AND person_escuadrilla_fk = $1
ORDER BY order_position
`

type LookupCrewRow struct {
	PersonSk int32   `json:"person_sk"`
	PersonNk *string `json:"person_nk"`
}

// get_crew_lookup: dotación (no pilotos, no no-tripulantes).
func (q *Queries) LookupCrew(ctx context.Context, personEscuadrillaFk int32) ([]LookupCrewRow, error) {
	rows, err := q.db.Query(ctx, lookupCrew, personEscuadrillaFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupCrewRow
	for rows.Next() {
		var i LookupCrewRow
		if err := rows.Scan(&i.PersonSk, &i.PersonNk); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupDepartureArrivalPlaces = `-- name: LookupDepartureArrivalPlaces :many
SELECT departure_arrival_place_sk, departure_arrival_place_code, departure_arrival_place_name
FROM operations.departure_arrival_place
ORDER BY departure_arrival_place_name
`

func (q *Queries) LookupDepartureArrivalPlaces(ctx context.Context) ([]OperationsDepartureArrivalPlace, error) {
	rows, err := q.db.Query(ctx, lookupDepartureArrivalPlaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OperationsDepartureArrivalPlace
	for rows.Next() {
		var i OperationsDepartureArrivalPlace
		if err := rows.Scan(&i.DepartureArrivalPlaceSk, &i.DepartureArrivalPlaceCode, &i.DepartureArrivalPlaceName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupEventNames = `-- name: LookupEventNames :many

SELECT event_name_value FROM operations.event_name ORDER BY event_name_value
`

// =============== Reads: catálogos plano (Vec<String>) ===============
func (q *Queries) LookupEventNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, lookupEventNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var event_name_value string
		if err := rows.Scan(&event_name_value); err != nil {
			return nil, err
		}
		items = append(items, event_name_value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupEvents = `-- name: LookupEvents :many
SELECT event_sk, (event_name || ' - ' || event_place)::text AS event_label
FROM operations.event
ORDER BY event_label
`

type LookupEventsRow struct {
	EventSk    int32  `json:"event_sk"`
	EventLabel string `json:"event_label"`
}

// get_events_lookup: "nombre - lugar" concatenado.
func (q *Queries) LookupEvents(ctx context.Context) ([]LookupEventsRow, error) {
	rows, err := q.db.Query(ctx, lookupEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupEventsRow
	for rows.Next() {
		var i LookupEventsRow
		if err := rows.Scan(&i.EventSk, &i.EventLabel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupEventsManage = `-- name: LookupEventsManage :many
SELECT event_sk, event_name, event_place
FROM operations.event
ORDER BY event_name, event_place
`

// get_events_manage: nombre y lugar separados.
func (q *Queries) LookupEventsManage(ctx context.Context) ([]OperationsEvent, error) {
	rows, err := q.db.Query(ctx, lookupEventsManage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OperationsEvent
	for rows.Next() {
		var i OperationsEvent
		if err := rows.Scan(&i.EventSk, &i.EventName, &i.EventPlace); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupPapeletaBloques = `-- name: LookupPapeletaBloques :many
SELECT papeleta_block_name FROM operations.papeleta_block ORDER BY papeleta_block_name
`

func (q *Queries) LookupPapeletaBloques(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, lookupPapeletaBloques)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var papeleta_block_name string
		if err := rows.Scan(&papeleta_block_name); err != nil {
			return nil, err
		}
		items = append(items, papeleta_block_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupPapeletaPlanes = `-- name: LookupPapeletaPlanes :many
SELECT papeleta_plan_name FROM operations.papeleta_plan ORDER BY papeleta_plan_name
`

func (q *Queries) LookupPapeletaPlanes(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, lookupPapeletaPlanes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var papeleta_plan_name string
		if err := rows.Scan(&papeleta_plan_name); err != nil {
			return nil, err
		}
		items = append(items, papeleta_plan_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupPapeletas = `-- name: LookupPapeletas :many
SELECT papeleta_sk, papeleta_name
FROM operations.papeleta
WHERE papeleta_escuadrilla_fk = $1
ORDER BY papeleta_name
`

type LookupPapeletasRow struct {
	PapeletaSk   int32  `json:"papeleta_sk"`
	PapeletaName string `json:"papeleta_name"`
}

func (q *Queries) LookupPapeletas(ctx context.Context, papeletaEscuadrillaFk int32) ([]LookupPapeletasRow, error) {
	rows, err := q.db.Query(ctx, lookupPapeletas, papeletaEscuadrillaFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupPapeletasRow
	for rows.Next() {
		var i LookupPapeletasRow
		if err := rows.Scan(&i.PapeletaSk, &i.PapeletaName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupPassengerTypes = `-- name: LookupPassengerTypes :many
SELECT passenger_type_sk, passenger_type_name
FROM operations.passenger_type
ORDER BY passenger_type_name
`

func (q *Queries) LookupPassengerTypes(ctx context.Context) ([]OperationsPassengerType, error) {
	rows, err := q.db.Query(ctx, lookupPassengerTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OperationsPassengerType
	for rows.Next() {
		var i OperationsPassengerType
		if err := rows.Scan(&i.PassengerTypeSk, &i.PassengerTypeName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupPersonDivisiones = `-- name: LookupPersonDivisiones :many
SELECT division_name FROM detall.division ORDER BY division_name
`

func (q *Queries) LookupPersonDivisiones(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, lookupPersonDivisiones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var division_name string
		if err := rows.Scan(&division_name); err != nil {
			return nil, err
		}
		items = append(items, division_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupPersonEmpleos = `-- name: LookupPersonEmpleos :many
SELECT rank_name FROM detall.rank ORDER BY rank_order
`

// Ordenados por precedencia militar (rank_order).
func (q *Queries) LookupPersonEmpleos(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, lookupPersonEmpleos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var rank_name string
		if err := rows.Scan(&rank_name); err != nil {
			return nil, err
		}
		items = append(items, rank_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupPersonEspecialidades = `-- name: LookupPersonEspecialidades :many
SELECT especialidad_name FROM detall.especialidad ORDER BY especialidad_name
`

func (q *Queries) LookupPersonEspecialidades(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, lookupPersonEspecialidades)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var especialidad_name string
		if err := rows.Scan(&especialidad_name); err != nil {
			return nil, err
		}
		items = append(items, especialidad_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupPersonRoles = `-- name: LookupPersonRoles :many
SELECT person_rol_name FROM detall.person_rol ORDER BY person_rol_name
`

func (q *Queries) LookupPersonRoles(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, lookupPersonRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var person_rol_name string
		if err := rows.Scan(&person_rol_name); err != nil {
			return nil, err
		}
		items = append(items, person_rol_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupPersons = `-- name: LookupPersons :many
SELECT
    person_sk,
    (person_rank || ' ' || person_name || ' ' || person_last_name_1 ||
     CASE WHEN COALESCE(person_last_name_2, '') = '' THEN '' ELSE ' ' || person_last_name_2 END
    )::text AS full_name
FROM detall.v_person_ordered
WHERE person_escuadrilla_fk = $1
ORDER BY order_position
`

type LookupPersonsRow struct {
	PersonSk int32  `json:"person_sk"`
	FullName string `json:"full_name"`
}

// get_persons_lookup: "rank name last_name_1 [last_name_2]".
func (q *Queries) LookupPersons(ctx context.Context, personEscuadrillaFk int32) ([]LookupPersonsRow, error) {
	rows, err := q.db.Query(ctx, lookupPersons, personEscuadrillaFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupPersonsRow
	for rows.Next() {
		var i LookupPersonsRow
		if err := rows.Scan(&i.PersonSk, &i.FullName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupPersonsForComision = `-- name: LookupPersonsForComision :many
SELECT person_sk, person_rank, person_name, person_last_name_1, person_last_name_2
FROM detall.v_person_ordered
WHERE person_escuadrilla_fk = $1
ORDER BY order_position
`

type LookupPersonsForComisionRow struct {
	PersonSk        int32  `json:"person_sk"`
	PersonRank      string `json:"person_rank"`
	PersonName      string `json:"person_name"`
	PersonLastName1 string `json:"person_last_name_1"`
	PersonLastName2 string `json:"person_last_name_2"`
}

func (q *Queries) LookupPersonsForComision(ctx context.Context, personEscuadrillaFk int32) ([]LookupPersonsForComisionRow, error) {
	rows, err := q.db.Query(ctx, lookupPersonsForComision, personEscuadrillaFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupPersonsForComisionRow
	for rows.Next() {
		var i LookupPersonsForComisionRow
		if err := rows.Scan(
			&i.PersonSk,
			&i.PersonRank,
			&i.PersonName,
			&i.PersonLastName1,
			&i.PersonLastName2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupPilots = `-- name: LookupPilots :many
SELECT person_sk, person_nk
FROM detall.v_person_ordered
WHERE person_rol = 'Piloto'
  AND person_escuadrilla_fk = $1
ORDER BY order_position
`

type LookupPilotsRow struct {
	PersonSk int32   `json:"person_sk"`
	PersonNk *string `json:"person_nk"`
}

// get_pilots_lookup: pilotos ordenados por la vista canónica.
func (q *Queries) LookupPilots(ctx context.Context, personEscuadrillaFk int32) ([]LookupPilotsRow, error) {
	rows, err := q.db.Query(ctx, lookupPilots, personEscuadrillaFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupPilotsRow
	for rows.Next() {
		var i LookupPilotsRow
		if err := rows.Scan(&i.PersonSk, &i.PersonNk); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupRecentComisiones = `-- name: LookupRecentComisiones :many
SELECT
    c.comision_sk,
    cl.comision_name                       AS lugar,
    ct.name                                AS tipo,
    TO_CHAR(c.comision_start_date, 'YYYY-MM-DD') AS fecha_inicio,
    TO_CHAR(c.comision_end_date,   'YYYY-MM-DD') AS fecha_fin,
    c.comision_esfuerzo                    AS esfuerzo
FROM detall.comision c
LEFT JOIN detall.comision_lugar cl ON c.comision_lugar_fk = cl.comision_lugar_sk
LEFT JOIN detall.comision_type  ct ON c.comision_type_fk  = ct.comision_type_sk
WHERE c.comision_escuadrilla_fk = $1
ORDER BY c.comision_sk DESC
LIMIT 20
`

type LookupRecentComisionesRow struct {
	ComisionSk  int32   `json:"comision_sk"`
	Lugar       *string `json:"lugar"`
	Tipo        *string `json:"tipo"`
	FechaInicio string  `json:"fecha_inicio"`
	FechaFin    string  `json:"fecha_fin"`
	Esfuerzo    bool    `json:"esfuerzo"`
}

// TOP 20 (LIMIT 20) más recientes. esfuerzo: boolean (en SQL Server era BIT
// y el Rust intentaba leer como string, lo que devolvía NULL).
func (q *Queries) LookupRecentComisiones(ctx context.Context, comisionEscuadrillaFk int32) ([]LookupRecentComisionesRow, error) {
	rows, err := q.db.Query(ctx, lookupRecentComisiones, comisionEscuadrillaFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LookupRecentComisionesRow
	for rows.Next() {
		var i LookupRecentComisionesRow
		if err := rows.Scan(
			&i.ComisionSk,
			&i.Lugar,
			&i.Tipo,
			&i.FechaInicio,
			&i.FechaFin,
			&i.Esfuerzo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAircraftCurrentFlag = `-- name: UpdateAircraftCurrentFlag :one
UPDATE operations.aircraft
SET aircraft_current_flag = $1
WHERE aircraft_sk = $2 AND aircraft_escuadrilla_fk = $3
RETURNING aircraft_current_flag
`

type UpdateAircraftCurrentFlagParams struct {
	AircraftCurrentFlag   bool  `json:"aircraft_current_flag"`
	AircraftSk            int32 `json:"aircraft_sk"`
	AircraftEscuadrillaFk int32 `json:"aircraft_escuadrilla_fk"`
}

// Devuelve el flag persistido para que el handler pueda verificar.
func (q *Queries) UpdateAircraftCurrentFlag(ctx context.Context, arg UpdateAircraftCurrentFlagParams) (bool, error) {
	row := q.db.QueryRow(ctx, updateAircraftCurrentFlag, arg.AircraftCurrentFlag, arg.AircraftSk, arg.AircraftEscuadrillaFk)
	var aircraft_current_flag bool
	err := row.Scan(&aircraft_current_flag)
	return aircraft_current_flag, err
}

const upsertEventName = `-- name: UpsertEventName :exec
INSERT INTO operations.event_name (event_name_value)
VALUES ($1)
ON CONFLICT (event_name_value) DO NOTHING
`

// Idempotente: si el nombre ya existe, no hace nada.
func (q *Queries) UpsertEventName(ctx context.Context, eventNameValue string) error {
	_, err := q.db.Exec(ctx, upsertEventName, eventNameValue)
	return err
}
