// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DetallAbsence struct {
	AbsenceSk            int32       `json:"absence_sk"`
	AbsenceStartDate     pgtype.Date `json:"absence_start_date"`
	AbsenceEndDate       pgtype.Date `json:"absence_end_date"`
	AbsencePersonFk      int32       `json:"absence_person_fk"`
	AbsenceReasonFk      int32       `json:"absence_reason_fk"`
	AbsenceRemark        *string     `json:"absence_remark"`
	AbsenceEscuadrillaFk int32       `json:"absence_escuadrilla_fk"`
}

type DetallAbsenceReason struct {
	AbsenceReasonSk int32  `json:"absence_reason_sk"`
	AbsenceReason   string `json:"absence_reason"`
}

type DetallAuditLog struct {
	AuditID   int64              `json:"audit_id"`
	TableName string             `json:"table_name"`
	Operation string             `json:"operation"`
	RecordID  string             `json:"record_id"`
	OldData   []byte             `json:"old_data"`
	NewData   []byte             `json:"new_data"`
	UserID    *string            `json:"user_id"`
	IpAddress *string            `json:"ip_address"`
	ChangedAt pgtype.Timestamptz `json:"changed_at"`
}

type DetallComision struct {
	ComisionSk            int32       `json:"comision_sk"`
	ComisionStartDate     pgtype.Date `json:"comision_start_date"`
	ComisionEndDate       pgtype.Date `json:"comision_end_date"`
	ComisionTypeFk        int32       `json:"comision_type_fk"`
	ComisionLugarFk       int32       `json:"comision_lugar_fk"`
	ComisionEscuadrillaFk int32       `json:"comision_escuadrilla_fk"`
	ComisionEsfuerzo      bool        `json:"comision_esfuerzo"`
	ComisionDepartureTime pgtype.Time `json:"comision_departure_time"`
	ComisionArrivalTime   pgtype.Time `json:"comision_arrival_time"`
}

type DetallComisionLugar struct {
	ComisionLugarSk int32  `json:"comision_lugar_sk"`
	ComisionName    string `json:"comision_name"`
}

type DetallComisionType struct {
	ComisionTypeSk int32  `json:"comision_type_sk"`
	Name           string `json:"name"`
	Origin         string `json:"origin"`
}

type DetallDivision struct {
	DivisionSk   int32  `json:"division_sk"`
	DivisionName string `json:"division_name"`
}

type DetallEscuadrilla struct {
	EscuadrillaSk           int32       `json:"escuadrilla_sk"`
	EscuadrillaCode         string      `json:"escuadrilla_code"`
	EscuadrillaName         string      `json:"escuadrilla_name"`
	EscuadrillaCreationDate pgtype.Date `json:"escuadrilla_creation_date"`
	EscuadrillaModelFk      *int32      `json:"escuadrilla_model_fk"`
}

type DetallEspecialidad struct {
	EspecialidadSk   int32  `json:"especialidad_sk"`
	EspecialidadName string `json:"especialidad_name"`
}

type DetallFestivo struct {
	FestivoSk     int32       `json:"festivo_sk"`
	FestivoDia    pgtype.Date `json:"festivo_dia"`
	FestivoMotivo string      `json:"festivo_motivo"`
}

type DetallLocalidad struct {
	LocalidadSk   int32  `json:"localidad_sk"`
	LocalidadName string `json:"localidad_name"`
}

type DetallNotcrewQualification struct {
	NotcrewRatingsSk                  int32              `json:"notcrew_ratings_sk"`
	PersonFk                          int32              `json:"person_fk"`
	NotcrewRatingFk                   int32              `json:"notcrew_rating_fk"`
	DateQualified                     pgtype.Timestamptz `json:"date_qualified"`
	NotcrewQualificationEscuadrillaFk int32              `json:"notcrew_qualification_escuadrilla_fk"`
}

type DetallNotcrewRatingType struct {
	NotcrewRatingSk   int32  `json:"notcrew_rating_sk"`
	NotcrewRatingName string `json:"notcrew_rating_name"`
	NotcrewRatingAbrv string `json:"notcrew_rating_abrv"`
}

type DetallPerson struct {
	PersonSk                 int32       `json:"person_sk"`
	PersonNk                 *string     `json:"person_nk"`
	PersonUser               string      `json:"person_user"`
	PersonRank               string      `json:"person_rank"`
	PersonCuerpo             string      `json:"person_cuerpo"`
	PersonEspecialidad       string      `json:"person_especialidad"`
	PersonName               string      `json:"person_name"`
	PersonLastName1          string      `json:"person_last_name_1"`
	PersonLastName2          string      `json:"person_last_name_2"`
	PersonPhone              string      `json:"person_phone"`
	PersonDni                *string     `json:"person_dni"`
	PersonLocalidad          string      `json:"person_localidad"`
	PersonDivision           string      `json:"person_division"`
	PersonRol                string      `json:"person_rol"`
	PersonAEmp               pgtype.Date `json:"person_a_emp"`
	PersonFEmb               pgtype.Date `json:"person_f_emb"`
	PersonBirthdate          pgtype.Date `json:"person_birthdate"`
	PersonNumEscalafon       int32       `json:"person_num_escalafon"`
	PersonCurrentFlag        bool        `json:"person_current_flag"`
	PersonPermissionLevel    string      `json:"person_permission_level"`
	PersonPasswordHash       *string     `json:"person_password_hash"`
	PersonPasswordMustChange bool        `json:"person_password_must_change"`
	PersonEscuadrillaFk      int32       `json:"person_escuadrilla_fk"`
}

type DetallPersonComision struct {
	PersonComisionSk int32 `json:"person_comision_sk"`
	ComisionFk       int32 `json:"comision_fk"`
	PersonFk         int32 `json:"person_fk"`
}

type DetallPersonRol struct {
	PersonRolSk   int32  `json:"person_rol_sk"`
	PersonRolName string `json:"person_rol_name"`
}

type DetallRank struct {
	RankSk       int32  `json:"rank_sk"`
	RankName     string `json:"rank_name"`
	RankOrder    int16  `json:"rank_order"`
	RankCategory string `json:"rank_category"`
}

type DetallSession struct {
	SessionSk  int64              `json:"session_sk"`
	TokenHash  []byte             `json:"token_hash"`
	PersonFk   int32              `json:"person_fk"`
	IpAddress  *string            `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

type DetallVPersonOrdered struct {
	PersonSk              int32       `json:"person_sk"`
	PersonNk              *string     `json:"person_nk"`
	PersonUser            string      `json:"person_user"`
	PersonRank            string      `json:"person_rank"`
	PersonCuerpo          string      `json:"person_cuerpo"`
	PersonEspecialidad    string      `json:"person_especialidad"`
	PersonName            string      `json:"person_name"`
	PersonLastName1       string      `json:"person_last_name_1"`
	PersonLastName2       string      `json:"person_last_name_2"`
	PersonPhone           string      `json:"person_phone"`
	PersonDni             *string     `json:"person_dni"`
	PersonDivision        string      `json:"person_division"`
	PersonRol             string      `json:"person_rol"`
	PersonAEmp            pgtype.Date `json:"person_a_emp"`
	PersonFEmb            pgtype.Date `json:"person_f_emb"`
	PersonBirthdate       pgtype.Date `json:"person_birthdate"`
	PersonNumEscalafon    int32       `json:"person_num_escalafon"`
	PersonCurrentFlag     bool        `json:"person_current_flag"`
	PersonPermissionLevel string      `json:"person_permission_level"`
	PersonEscuadrillaFk   int32       `json:"person_escuadrilla_fk"`
	RankCategory          string      `json:"rank_category"`
	OrderPosition         int64       `json:"order_position"`
}

type FlightsafetyDunker struct {
	DunkerSk            int32       `json:"dunker_sk"`
	DunkerDate          pgtype.Date `json:"dunker_date"`
	DunkerPersonFk      int32       `json:"dunker_person_fk"`
	DunkerResult        *bool       `json:"dunker_result"`
	DunkerScheduledDate pgtype.Date `json:"dunker_scheduled_date"`
	DunkerExpiryDate    pgtype.Date `json:"dunker_expiry_date"`
}

type FlightsafetyHypobaric struct {
	HypobaricSk            int32       `json:"hypobaric_sk"`
	HypobaricDate          pgtype.Date `json:"hypobaric_date"`
	HypobaricPersonFk      int32       `json:"hypobaric_person_fk"`
	HypobaricResult        *bool       `json:"hypobaric_result"`
	HypobaricScheduledDate pgtype.Date `json:"hypobaric_scheduled_date"`
	HypobaricExpiryDate    pgtype.Date `json:"hypobaric_expiry_date"`
}

type FlightsafetyMedicalExam struct {
	MedicalExamSk            int32       `json:"medical_exam_sk"`
	MedicalExamDate          pgtype.Date `json:"medical_exam_date"`
	MedicalExamPersonFk      int32       `json:"medical_exam_person_fk"`
	MedicalExamPlaceFk       *int32      `json:"medical_exam_place_fk"`
	MedicalExamResultFk      *int32      `json:"medical_exam_result_fk"`
	MedicalExamRemark        *string     `json:"medical_exam_remark"`
	MedicalExamScheduledDate pgtype.Date `json:"medical_exam_scheduled_date"`
	MedicalExamExpiryDate    pgtype.Date `json:"medical_exam_expiry_date"`
}

type FlightsafetyMedicalExamPlace struct {
	MedicalExamPlaceSk int32  `json:"medical_exam_place_sk"`
	MedicalExamPlace   string `json:"medical_exam_place"`
}

type FlightsafetyMedicalExamResult struct {
	MedicalExamResultSk int32  `json:"medical_exam_result_sk"`
	MedicalExamResult   string `json:"medical_exam_result"`
}

type OperationsAircraft struct {
	AircraftSk            int32  `json:"aircraft_sk"`
	AircraftModelFk       int32  `json:"aircraft_model_fk"`
	AircraftRegistration  string `json:"aircraft_registration"`
	AircraftNumber        string `json:"aircraft_number"`
	AircraftCurrentFlag   bool   `json:"aircraft_current_flag"`
	AircraftEscuadrillaFk int32  `json:"aircraft_escuadrilla_fk"`
}

type OperationsAircraftModel struct {
	AircraftModelSk       int32  `json:"aircraft_model_sk"`
	AircraftType          string `json:"aircraft_type"`
	AircraftMake          string `json:"aircraft_make"`
	AircraftModel         string `json:"aircraft_model"`
	AircraftVariant       string `json:"aircraft_variant"`
	AircraftIsMultiEngine bool   `json:"aircraft_is_multi_engine"`
	AircraftIsMultiPilot  bool   `json:"aircraft_is_multi_pilot"`
}

type OperationsApproach struct {
	AppSk       int32 `json:"app_sk"`
	AppFlightFk int32 `json:"app_flight_fk"`
	AppPersonFk int32 `json:"app_person_fk"`
	AppTypeFk   int32 `json:"app_type_fk"`
	AppQty      int32 `json:"app_qty"`
}

type OperationsAuthority struct {
	AuthoritySk   int32  `json:"authority_sk"`
	AuthorityName string `json:"authority_name"`
	AuthorityAbrv string `json:"authority_abrv"`
}

type OperationsCapba struct {
	CapbaID          int32  `json:"capba_id"`
	CapbaGroupCodeFk int32  `json:"capba_group_code_fk"`
	CapbaName        string `json:"capba_name"`
}

type OperationsCapbaGroup struct {
	CapbaGroupSk   int32  `json:"capba_group_sk"`
	CapbaGroupCode int32  `json:"capba_group_code"`
	CapbaGroupName string `json:"capba_group_name"`
}

type OperationsCapbaHour struct {
	CapbaHourSk   int32          `json:"capba_hour_sk"`
	CapbaFlightFk int32          `json:"capba_flight_fk"`
	CapbaCapbaFk  int32          `json:"capba_capba_fk"`
	CapbaHourQty  pgtype.Numeric `json:"capba_hour_qty"`
}

type OperationsCrewQualification struct {
	CrewRatingSk                   int32       `json:"crew_rating_sk"`
	PersonFk                       int32       `json:"person_fk"`
	CrewRatingsFk                  int32       `json:"crew_ratings_fk"`
	DateQualified                  pgtype.Date `json:"date_qualified"`
	CrewQualificationEscuadrillaFk int32       `json:"crew_qualification_escuadrilla_fk"`
}

type OperationsCrewRatingType struct {
	CrewRatingSk int32  `json:"crew_rating_sk"`
	Name         string `json:"name"`
	Abbreviation string `json:"abbreviation"`
	Type         string `json:"type"`
	Role         string `json:"role"`
}

type OperationsCupoHour struct {
	CupoHourSk      int32          `json:"cupo_hour_sk"`
	CupoFlightFk    int32          `json:"cupo_flight_fk"`
	CupoAuthorityFk int32          `json:"cupo_authority_fk"`
	CupoHourQty     pgtype.Numeric `json:"cupo_hour_qty"`
}

type OperationsDepartureArrivalPlace struct {
	DepartureArrivalPlaceSk   int32  `json:"departure_arrival_place_sk"`
	DepartureArrivalPlaceCode string `json:"departure_arrival_place_code"`
	DepartureArrivalPlaceName string `json:"departure_arrival_place_name"`
}

type OperationsEscuadrillaCapba struct {
	EscuadrillaCapbaSk                 int32 `json:"escuadrilla_capba_sk"`
	EscuadrillaCapbaEscuadrillaFk      int32 `json:"escuadrilla_capba_escuadrilla_fk"`
	EscuadrillaCapbaCapbaFk            int32 `json:"escuadrilla_capba_capba_fk"`
	EscuadrillaCapbaCapacidadOperativa int32 `json:"escuadrilla_capba_capacidad_operativa"`
}

type OperationsEvent struct {
	EventSk    int32  `json:"event_sk"`
	EventName  string `json:"event_name"`
	EventPlace string `json:"event_place"`
}

type OperationsEventName struct {
	EventNameSk    int32  `json:"event_name_sk"`
	EventNameValue string `json:"event_name_value"`
}

type OperationsExtraHour struct {
	ExtraHoursSk        int32          `json:"extra_hours_sk"`
	ExtraHoursDate      pgtype.Date    `json:"extra_hours_date"`
	ExtraHoursPersonFk  int32          `json:"extra_hours_person_fk"`
	ExtraHoursModelFk   int32          `json:"extra_hours_model_fk"`
	ExtraHoursIsReal    bool           `json:"extra_hours_is_real"`
	ExtraHoursCta       pgtype.Numeric `json:"extra_hours_cta"`
	ExtraHoursDay       pgtype.Numeric `json:"extra_hours_day"`
	ExtraHoursConvNight pgtype.Numeric `json:"extra_hours_conv_night"`
	ExtraHoursGvn       pgtype.Numeric `json:"extra_hours_gvn"`
	ExtraHoursInst      pgtype.Numeric `json:"extra_hours_inst"`
	ExtraHoursRemarks   *string        `json:"extra_hours_remarks"`
}

type OperationsFlight struct {
	FlightSk             int32          `json:"flight_sk"`
	FlightDate           pgtype.Date    `json:"flight_date"`
	FlightDeparturePlace int32          `json:"flight_departure_place"`
	FlightDepartureTime  pgtype.Time    `json:"flight_departure_time"`
	FlightArrivalPlace   int32          `json:"flight_arrival_place"`
	FlightArrivalTime    pgtype.Time    `json:"flight_arrival_time"`
	FlightAircraftFk     int32          `json:"flight_aircraft_fk"`
	FlightEventFk        int32          `json:"flight_event_fk"`
	FlightPersonCtaFk    int32          `json:"flight_person_cta_fk"`
	FlightEscuadrillaFk  int32          `json:"flight_escuadrilla_fk"`
	FlightTotalHours     pgtype.Numeric `json:"flight_total_hours"`
}

type OperationsFormationHour struct {
	FormationHourSk           int32          `json:"formation_hour_sk"`
	FormationHourFlightFk     int32          `json:"formation_hour_flight_fk"`
	FormationHourPersonFk     int32          `json:"formation_hour_person_fk"`
	FormationHourPeriodFk     int32          `json:"formation_hour_period_fk"`
	FormationHourFormationQty pgtype.Numeric `json:"formation_hour_formation_qty"`
}

type OperationsFuel struct {
	FuelSk      int32          `json:"fuel_sk"`
	FuelDate    pgtype.Date    `json:"fuel_date"`
	FuelHeloFk  int32          `json:"fuel_helo_fk"`
	FuelPlaceFk int32          `json:"fuel_place_fk"`
	FuelPayerFk int32          `json:"fuel_payer_fk"`
	FuelEventFk int32          `json:"fuel_event_fk"`
	FuelPhaseFk int32          `json:"fuel_phase_fk"`
	FuelTypeFk  int32          `json:"fuel_type_fk"`
	FuelQty     pgtype.Numeric `json:"fuel_qty"`
}

type OperationsFuelPayer struct {
	FuelPayerSk                   int32  `json:"fuel_payer_sk"`
	FuelPayerAssignmentTypeAbbrev string `json:"fuel_payer_assignment_type_abbrev"`
	FuelPayerAssignmentType       string `json:"fuel_payer_assignment_type"`
	FuelPayerName                 string `json:"fuel_payer_name"`
}

type OperationsFuelPhase struct {
	FuelPhaseSk int32  `json:"fuel_phase_sk"`
	FuelPhase   string `json:"fuel_phase"`
}

type OperationsFuelPlace struct {
	FuelPlaceSk   int32  `json:"fuel_place_sk"`
	FuelPlaceName string `json:"fuel_place_name"`
	FuelPlaceType string `json:"fuel_place_type"`
}

type OperationsFuelType struct {
	FuelTypeSk int32  `json:"fuel_type_sk"`
	FuelType   string `json:"fuel_type"`
}

type OperationsGroundSchool struct {
	GroundSchoolSk            int32              `json:"ground_school_sk"`
	GroundSchoolDatetime      pgtype.Timestamptz `json:"ground_school_datetime"`
	GroundSchoolPersonFk      int32              `json:"ground_school_person_fk"`
	GroundSchoolPapeletaFk    int32              `json:"ground_school_papeleta_fk"`
	GroundSchoolEscuadrillaFk int32              `json:"ground_school_escuadrilla_fk"`
}

type OperationsGvntypeHour struct {
	GvntypeHourSk       int32          `json:"gvntype_hour_sk"`
	GvntypeHourFlightFk int32          `json:"gvntype_hour_flight_fk"`
	GvntypeHourPersonFk int32          `json:"gvntype_hour_person_fk"`
	GvntypeHourIitQty   pgtype.Numeric `json:"gvntype_hour_iit_qty"`
	GvntypeHourAnvisQty pgtype.Numeric `json:"gvntype_hour_anvis_qty"`
}

type OperationsIfrAppType struct {
	IfrAppTypeSk   int32  `json:"ifr_app_type_sk"`
	IfrAppTypeName string `json:"ifr_app_type_name"`
	IfrAppTypeType string `json:"ifr_app_type_type"`
}

type OperationsIftHour struct {
	IftHourSk       int32          `json:"ift_hour_sk"`
	IftHourFlightFk int32          `json:"ift_hour_flight_fk"`
	IftHourPersonFk int32          `json:"ift_hour_person_fk"`
	IftHourQty      pgtype.Numeric `json:"ift_hour_qty"`
}

type OperationsInstructorHour struct {
	InstructorHourSk       int32          `json:"instructor_hour_sk"`
	InstructorHourFlightFk int32          `json:"instructor_hour_flight_fk"`
	InstructorHourPersonFk int32          `json:"instructor_hour_person_fk"`
	InstructorHourQty      pgtype.Numeric `json:"instructor_hour_qty"`
}

type OperationsLanding struct {
	LandingSk       int32 `json:"landing_sk"`
	LandingFlightFk int32 `json:"landing_flight_fk"`
	LandingPersonFk int32 `json:"landing_person_fk"`
	LandingPlaceFk  int32 `json:"landing_place_fk"`
	LandingPeriodFk int32 `json:"landing_period_fk"`
	LandingQty      int32 `json:"landing_qty"`
}

type OperationsLandingPlace struct {
	LandingPlaceSk   int32  `json:"landing_place_sk"`
	LandingPlaceName string `json:"landing_place_name"`
}

type OperationsPapeletaBlock struct {
	PapeletaBlockSk   int32  `json:"papeleta_block_sk"`
	PapeletaBlockName string `json:"papeleta_block_name"`
}

type OperationsPapeletaCrewCount struct {
	PapeletaCrewCountSk        int32 `json:"papeleta_crew_count_sk"`
	PapeletaCrewCountFlightFk  int32 `json:"papeleta_crew_count_flight_fk"`
	PapeletaCrewCountPersonFk  int32 `json:"papeleta_crew_count_person_fk"`
	PapeletaCrewCountSessionFk int32 `json:"papeleta_crew_count_session_fk"`
	PapeletaCrewCountPeriodFk  int32 `json:"papeleta_crew_count_period_fk"`
}

type OperationsPapeletaPlan struct {
	PapeletaPlanSk   int32  `json:"papeleta_plan_sk"`
	PapeletaPlanName string `json:"papeleta_plan_name"`
}

type OperationsPapeletum struct {
	PapeletaSk            int32          `json:"papeleta_sk"`
	PapeletaName          string         `json:"papeleta_name"`
	PapeletaDescription   string         `json:"papeleta_description"`
	PapeletaBlock         string         `json:"papeleta_block"`
	PapeletaPlan          *string        `json:"papeleta_plan"`
	PapeletaTv            pgtype.Numeric `json:"papeleta_tv"`
	PapeletaPilotCrpValue *int32         `json:"papeleta_pilot_crp_value"`
	PapeletaDvCrpValue    *int32         `json:"papeleta_dv_crp_value"`
	PapeletaExpiration    *int32         `json:"papeleta_expiration"`
	PapeletaOrder         *int32         `json:"papeleta_order"`
	PapeletaEscuadrillaFk int32          `json:"papeleta_escuadrilla_fk"`
}

type OperationsPassenger struct {
	PassengerSk       int32  `json:"passenger_sk"`
	PassengerFlightFk int32  `json:"passenger_flight_fk"`
	PassengerTypeFk   int32  `json:"passenger_type_fk"`
	PassengerQty      int32  `json:"passenger_qty"`
	PassengerRoute    string `json:"passenger_route"`
}

type OperationsPassengerType struct {
	PassengerTypeSk   int32  `json:"passenger_type_sk"`
	PassengerTypeName string `json:"passenger_type_name"`
}

type OperationsPeriod struct {
	PeriodSk   int32  `json:"period_sk"`
	PeriodName string `json:"period_name"`
}

type OperationsPersonHour struct {
	PersonHourSk       int32          `json:"person_hour_sk"`
	PersonHourFlightFk int32          `json:"person_hour_flight_fk"`
	PersonHourPersonFk int32          `json:"person_hour_person_fk"`
	PersonHourPeriodFk int32          `json:"person_hour_period_fk"`
	PersonHourHourQty  pgtype.Numeric `json:"person_hour_hour_qty"`
}

type OperationsProjectile struct {
	ProjectileSk       int32 `json:"projectile_sk"`
	ProjectileFlightFk int32 `json:"projectile_flight_fk"`
	ProjectilePersonFk int32 `json:"projectile_person_fk"`
	ProjectileTypeFk   int32 `json:"projectile_type_fk"`
	ProjectileQty      int32 `json:"projectile_qty"`
}

type OperationsProjectileType struct {
	ProjectileTypeSk     int32  `json:"projectile_type_sk"`
	ProjectileTypeName   string `json:"projectile_type_name"`
	ProjectileTypeWeapon string `json:"projectile_type_weapon"`
}

type OperationsViewGroundSchool struct {
	ID          int32   `json:"id"`
	FechaHora   string  `json:"fecha_hora"`
	Crew        *string `json:"crew"`
	Nombre      string  `json:"nombre"`
	Descripcion string  `json:"descripcion"`
	Bloque      string  `json:"bloque"`
}

type OperationsViewLastFlight struct {
	ID          int32          `json:"id"`
	FechaHora   string         `json:"fecha_hora"`
	Helicoptero string         `json:"helicoptero"`
	Evento      interface{}    `json:"evento"`
	Hac         *string        `json:"hac"`
	Horas       pgtype.Numeric `json:"horas"`
}

type OperationsWtHour struct {
	WtHourSk       int32          `json:"wt_hour_sk"`
	WtHourFlightFk int32          `json:"wt_hour_flight_fk"`
	WtHourPersonFk int32          `json:"wt_hour_person_fk"`
	WtHourQty      pgtype.Numeric `json:"wt_hour_qty"`
}
