// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: papeletas.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPapeletas = `-- name: CountPapeletas :one
SELECT COUNT(*)::int AS total
FROM operations.papeleta
WHERE papeleta_escuadrilla_fk = $1
`

func (q *Queries) CountPapeletas(ctx context.Context, papeletaEscuadrillaFk int32) (int32, error) {
	row := q.db.QueryRow(ctx, countPapeletas, papeletaEscuadrillaFk)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const insertPapeleta = `-- name: InsertPapeleta :one
INSERT INTO operations.papeleta (
    papeleta_name, papeleta_description, papeleta_block, papeleta_plan,
    papeleta_tv, papeleta_pilot_crp_value, papeleta_dv_crp_value,
    papeleta_expiration, papeleta_order, papeleta_escuadrilla_fk
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING papeleta_sk
`

type InsertPapeletaParams struct {
	PapeletaName          string         `json:"papeleta_name"`
	PapeletaDescription   string         `json:"papeleta_description"`
	PapeletaBlock         string         `json:"papeleta_block"`
	PapeletaPlan          *string        `json:"papeleta_plan"`
	PapeletaTv            pgtype.Numeric `json:"papeleta_tv"`
	PapeletaPilotCrpValue *int32         `json:"papeleta_pilot_crp_value"`
	PapeletaDvCrpValue    *int32         `json:"papeleta_dv_crp_value"`
	PapeletaExpiration    *int32         `json:"papeleta_expiration"`
	PapeletaOrder         *int32         `json:"papeleta_order"`
	PapeletaEscuadrillaFk int32          `json:"papeleta_escuadrilla_fk"`
}

func (q *Queries) InsertPapeleta(ctx context.Context, arg InsertPapeletaParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertPapeleta,
		arg.PapeletaName,
		arg.PapeletaDescription,
		arg.PapeletaBlock,
		arg.PapeletaPlan,
		arg.PapeletaTv,
		arg.PapeletaPilotCrpValue,
		arg.PapeletaDvCrpValue,
		arg.PapeletaExpiration,
		arg.PapeletaOrder,
		arg.PapeletaEscuadrillaFk,
	)
	var papeleta_sk int32
	err := row.Scan(&papeleta_sk)
	return papeleta_sk, err
}

const listPapeletas = `-- name: ListPapeletas :many

SELECT
    papeleta_sk, papeleta_name, papeleta_description,
    papeleta_block, papeleta_plan, papeleta_tv,
    papeleta_pilot_crp_value, papeleta_dv_crp_value, papeleta_expiration,
    papeleta_order
FROM operations.papeleta
WHERE papeleta_escuadrilla_fk = $1
ORDER BY papeleta_plan, papeleta_order NULLS LAST, papeleta_block, papeleta_name
`

type ListPapeletasRow struct {
	PapeletaSk            int32          `json:"papeleta_sk"`
	PapeletaName          string         `json:"papeleta_name"`
	PapeletaDescription   string         `json:"papeleta_description"`
	PapeletaBlock         string         `json:"papeleta_block"`
	PapeletaPlan          *string        `json:"papeleta_plan"`
	PapeletaTv            pgtype.Numeric `json:"papeleta_tv"`
	PapeletaPilotCrpValue *int32         `json:"papeleta_pilot_crp_value"`
	PapeletaDvCrpValue    *int32         `json:"papeleta_dv_crp_value"`
	PapeletaExpiration    *int32         `json:"papeleta_expiration"`
	PapeletaOrder         *int32         `json:"papeleta_order"`
}

// ============================================================
// Papeletas (Hito 4, lote 2)
//
// Fix RLS: add_papeleta y update_papeleta originales NO inyectaban
// papeleta_escuadrilla_fk en SQL Server, pero la columna es NOT NULL.
// En PG explícitamente:
//   - INSERT setea papeleta_escuadrilla_fk = $9 (de la sesión).
//   - UPDATE filtra por papeleta_escuadrilla_fk para impedir editar
//     papeletas de otra escuadrilla.
//
// ============================================================
func (q *Queries) ListPapeletas(ctx context.Context, papeletaEscuadrillaFk int32) ([]ListPapeletasRow, error) {
	rows, err := q.db.Query(ctx, listPapeletas, papeletaEscuadrillaFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPapeletasRow
	for rows.Next() {
		var i ListPapeletasRow
		if err := rows.Scan(
			&i.PapeletaSk,
			&i.PapeletaName,
			&i.PapeletaDescription,
			&i.PapeletaBlock,
			&i.PapeletaPlan,
			&i.PapeletaTv,
			&i.PapeletaPilotCrpValue,
			&i.PapeletaDvCrpValue,
			&i.PapeletaExpiration,
			&i.PapeletaOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePapeleta = `-- name: UpdatePapeleta :execrows
UPDATE operations.papeleta
SET papeleta_name = $1,
    papeleta_description = $2,
    papeleta_block = $3,
    papeleta_plan = $4,
    papeleta_tv = $5,
    papeleta_pilot_crp_value = $6,
    papeleta_dv_crp_value = $7,
    papeleta_expiration = $8,
    papeleta_order = $9
WHERE papeleta_sk = $10 AND papeleta_escuadrilla_fk = $11
`

type UpdatePapeletaParams struct {
	PapeletaName          string         `json:"papeleta_name"`
	PapeletaDescription   string         `json:"papeleta_description"`
	PapeletaBlock         string         `json:"papeleta_block"`
	PapeletaPlan          *string        `json:"papeleta_plan"`
	PapeletaTv            pgtype.Numeric `json:"papeleta_tv"`
	PapeletaPilotCrpValue *int32         `json:"papeleta_pilot_crp_value"`
	PapeletaDvCrpValue    *int32         `json:"papeleta_dv_crp_value"`
	PapeletaExpiration    *int32         `json:"papeleta_expiration"`
	PapeletaOrder         *int32         `json:"papeleta_order"`
	PapeletaSk            int32          `json:"papeleta_sk"`
	PapeletaEscuadrillaFk int32          `json:"papeleta_escuadrilla_fk"`
}

func (q *Queries) UpdatePapeleta(ctx context.Context, arg UpdatePapeletaParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePapeleta,
		arg.PapeletaName,
		arg.PapeletaDescription,
		arg.PapeletaBlock,
		arg.PapeletaPlan,
		arg.PapeletaTv,
		arg.PapeletaPilotCrpValue,
		arg.PapeletaDvCrpValue,
		arg.PapeletaExpiration,
		arg.PapeletaOrder,
		arg.PapeletaSk,
		arg.PapeletaEscuadrillaFk,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
