// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: persons.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPersons = `-- name: CountPersons :one
SELECT COUNT(*)::int FROM detall.v_person_ordered WHERE person_escuadrilla_fk = $1
`

func (q *Queries) CountPersons(ctx context.Context, personEscuadrillaFk int32) (int32, error) {
	row := q.db.QueryRow(ctx, countPersons, personEscuadrillaFk)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countSuperusersInEscuadrilla = `-- name: CountSuperusersInEscuadrilla :one
SELECT COUNT(*)::int
FROM detall.person
WHERE person_permission_level = 'Superusuario' AND person_escuadrilla_fk = $1
`

func (q *Queries) CountSuperusersInEscuadrilla(ctx context.Context, personEscuadrillaFk int32) (int32, error) {
	row := q.db.QueryRow(ctx, countSuperusersInEscuadrilla, personEscuadrillaFk)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getCrewMembersBySk = `-- name: GetCrewMembersBySk :many
SELECT person_sk, person_nk
FROM detall.person
WHERE person_sk = ANY($1::int[])
  AND person_escuadrilla_fk = $2
ORDER BY person_sk
`

type GetCrewMembersBySkParams struct {
	Column1             []int32 `json:"column_1"`
	PersonEscuadrillaFk int32   `json:"person_escuadrilla_fk"`
}

type GetCrewMembersBySkRow struct {
	PersonSk int32   `json:"person_sk"`
	PersonNk *string `json:"person_nk"`
}

func (q *Queries) GetCrewMembersBySk(ctx context.Context, arg GetCrewMembersBySkParams) ([]GetCrewMembersBySkRow, error) {
	rows, err := q.db.Query(ctx, getCrewMembersBySk, arg.Column1, arg.PersonEscuadrillaFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCrewMembersBySkRow
	for rows.Next() {
		var i GetCrewMembersBySkRow
		if err := rows.Scan(&i.PersonSk, &i.PersonNk); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonPermissionLevelInEscuadrilla = `-- name: GetPersonPermissionLevelInEscuadrilla :one
SELECT person_permission_level
FROM detall.person
WHERE person_sk = $1 AND person_escuadrilla_fk = $2
`

type GetPersonPermissionLevelInEscuadrillaParams struct {
	PersonSk            int32 `json:"person_sk"`
	PersonEscuadrillaFk int32 `json:"person_escuadrilla_fk"`
}

func (q *Queries) GetPersonPermissionLevelInEscuadrilla(ctx context.Context, arg GetPersonPermissionLevelInEscuadrillaParams) (string, error) {
	row := q.db.QueryRow(ctx, getPersonPermissionLevelInEscuadrilla, arg.PersonSk, arg.PersonEscuadrillaFk)
	var person_permission_level string
	err := row.Scan(&person_permission_level)
	return person_permission_level, err
}

const insertPerson = `-- name: InsertPerson :one
INSERT INTO detall.person (
    person_nk, person_user, person_rank, person_cuerpo, person_especialidad,
    person_name, person_last_name_1, person_last_name_2, person_phone, person_dni,
    person_localidad, person_division, person_rol, person_a_emp, person_f_emb,
    person_birthdate, person_num_escalafon, person_current_flag, person_permission_level,
    person_escuadrilla_fk, person_password_hash, person_password_must_change
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15,
    $16, $17, TRUE, 'Común',
    $18, $19, TRUE
)
RETURNING person_sk
`

type InsertPersonParams struct {
	PersonNk            *string     `json:"person_nk"`
	PersonUser          string      `json:"person_user"`
	PersonRank          string      `json:"person_rank"`
	PersonCuerpo        string      `json:"person_cuerpo"`
	PersonEspecialidad  string      `json:"person_especialidad"`
	PersonName          string      `json:"person_name"`
	PersonLastName1     string      `json:"person_last_name_1"`
	PersonLastName2     string      `json:"person_last_name_2"`
	PersonPhone         string      `json:"person_phone"`
	PersonDni           *string     `json:"person_dni"`
	PersonLocalidad     string      `json:"person_localidad"`
	PersonDivision      string      `json:"person_division"`
	PersonRol           string      `json:"person_rol"`
	PersonAEmp          pgtype.Date `json:"person_a_emp"`
	PersonFEmb          pgtype.Date `json:"person_f_emb"`
	PersonBirthdate     pgtype.Date `json:"person_birthdate"`
	PersonNumEscalafon  int32       `json:"person_num_escalafon"`
	PersonEscuadrillaFk int32       `json:"person_escuadrilla_fk"`
	PersonPasswordHash  *string     `json:"person_password_hash"`
}

// Defaults: current_flag=TRUE, permission_level='Común' (¡con acento!).
// Bug fix vs Rust: el INSERT original omitía person_localidad (NOT NULL),
// por lo que cualquier add_person fallaba si la BD seguía el esquema.
// person_password_hash + person_password_must_change: el alta deja la
// contraseña por defecto ('aether', hasheada en Go) y fuerza el cambio.
func (q *Queries) InsertPerson(ctx context.Context, arg InsertPersonParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertPerson,
		arg.PersonNk,
		arg.PersonUser,
		arg.PersonRank,
		arg.PersonCuerpo,
		arg.PersonEspecialidad,
		arg.PersonName,
		arg.PersonLastName1,
		arg.PersonLastName2,
		arg.PersonPhone,
		arg.PersonDni,
		arg.PersonLocalidad,
		arg.PersonDivision,
		arg.PersonRol,
		arg.PersonAEmp,
		arg.PersonFEmb,
		arg.PersonBirthdate,
		arg.PersonNumEscalafon,
		arg.PersonEscuadrillaFk,
		arg.PersonPasswordHash,
	)
	var person_sk int32
	err := row.Scan(&person_sk)
	return person_sk, err
}

const listPersons = `-- name: ListPersons :many

SELECT
    person_sk                         AS id,
    person_nk                         AS nk,
    person_user                       AS usuario,
    person_rank                       AS empleo,
    person_cuerpo                     AS cuerpo,
    person_especialidad               AS especialidad,
    person_name                       AS nombre,
    person_last_name_1                AS apellido1,
    person_last_name_2                AS apellido2,
    BTRIM(person_rank || ' ' || person_last_name_1 || ' ' || person_last_name_2)::text AS nombre_completo,
    person_phone                      AS telefono,
    person_dni                        AS dni,
    person_localidad                  AS localidad,
    person_division                   AS division,
    person_rol                        AS rol,
    person_a_emp                      AS antiguedad_empleo,
    person_f_emb                      AS fecha_embarco,
    person_birthdate                  AS fecha_nacimiento,
    person_num_escalafon              AS numero_escalafon,
    person_current_flag               AS activo,
    order_position                    AS orden_posicion
FROM detall.v_person_ordered
WHERE person_escuadrilla_fk = $1
ORDER BY order_position
`

type ListPersonsRow struct {
	ID               int32       `json:"id"`
	Nk               *string     `json:"nk"`
	Usuario          string      `json:"usuario"`
	Empleo           string      `json:"empleo"`
	Cuerpo           string      `json:"cuerpo"`
	Especialidad     string      `json:"especialidad"`
	Nombre           string      `json:"nombre"`
	Apellido1        string      `json:"apellido1"`
	Apellido2        string      `json:"apellido2"`
	NombreCompleto   string      `json:"nombre_completo"`
	Telefono         string      `json:"telefono"`
	Dni              *string     `json:"dni"`
	Localidad        string      `json:"localidad"`
	Division         string      `json:"division"`
	Rol              string      `json:"rol"`
	AntiguedadEmpleo pgtype.Date `json:"antiguedad_empleo"`
	FechaEmbarco     pgtype.Date `json:"fecha_embarco"`
	FechaNacimiento  pgtype.Date `json:"fecha_nacimiento"`
	NumeroEscalafon  int32       `json:"numero_escalafon"`
	Activo           bool        `json:"activo"`
	OrdenPosicion    int64       `json:"orden_posicion"`
}

// ============================================================
// Persons (Hito 4, lote 3)
//
// Reimplementa sp_get_persons + add/update/dardebaja/dardealta_person
// + get_crew_members_by_sk.
//
// Fix RLS: add_person ahora setea person_escuadrilla_fk explícitamente
// desde la sesión (en SQL Server usaba SESSION_CONTEXT).
// update_person filtra por escuadrilla para impedir editar de otra.
// Fix typo: 'Comun' → 'Común' (constraint CHK requiere acento).
// ============================================================
// Aliases Spanish para mantener el contrato del frontend
// (src/features/personnel/utils/transformPersonnelFromDB.ts).
func (q *Queries) ListPersons(ctx context.Context, personEscuadrillaFk int32) ([]ListPersonsRow, error) {
	rows, err := q.db.Query(ctx, listPersons, personEscuadrillaFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonsRow
	for rows.Next() {
		var i ListPersonsRow
		if err := rows.Scan(
			&i.ID,
			&i.Nk,
			&i.Usuario,
			&i.Empleo,
			&i.Cuerpo,
			&i.Especialidad,
			&i.Nombre,
			&i.Apellido1,
			&i.Apellido2,
			&i.NombreCompleto,
			&i.Telefono,
			&i.Dni,
			&i.Localidad,
			&i.Division,
			&i.Rol,
			&i.AntiguedadEmpleo,
			&i.FechaEmbarco,
			&i.FechaNacimiento,
			&i.NumeroEscalafon,
			&i.Activo,
			&i.OrdenPosicion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonsForSuperuser = `-- name: ListPersonsForSuperuser :many

SELECT
    vpo.person_sk                                                                              AS id,
    BTRIM(vpo.person_rank || ' ' || vpo.person_last_name_1 || ' ' || vpo.person_last_name_2)::text AS nombre_completo,
    vpo.person_user                                                                            AS usuario,
    vpo.person_permission_level                                                                AS nivel,
    (p.person_password_hash IS NOT NULL)::boolean                                              AS tiene_password
FROM detall.v_person_ordered vpo
JOIN detall.person p ON p.person_sk = vpo.person_sk
WHERE vpo.person_escuadrilla_fk = $1
  AND vpo.person_current_flag = TRUE
ORDER BY vpo.order_position
`

type ListPersonsForSuperuserRow struct {
	ID             int32  `json:"id"`
	NombreCompleto string `json:"nombre_completo"`
	Usuario        string `json:"usuario"`
	Nivel          string `json:"nivel"`
	TienePassword  bool   `json:"tiene_password"`
}

// ============================================================
// Superusuario (god-mode acotado a la escuadrilla). Gestiona credenciales y
// niveles de permiso, pero SOLO de personas de su propia escuadrilla: igual
// que el resto del dominio, todas estas queries filtran por person_escuadrilla_fk.
// ============================================================
// Personas ACTIVAS de la escuadrilla, con nivel y estado de credenciales,
// ordenadas por la lógica de v_person_ordered (order_position). El hash de
// contraseña no está en la vista: se trae con un JOIN a detall.person.
func (q *Queries) ListPersonsForSuperuser(ctx context.Context, personEscuadrillaFk int32) ([]ListPersonsForSuperuserRow, error) {
	rows, err := q.db.Query(ctx, listPersonsForSuperuser, personEscuadrillaFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonsForSuperuserRow
	for rows.Next() {
		var i ListPersonsForSuperuserRow
		if err := rows.Scan(
			&i.ID,
			&i.NombreCompleto,
			&i.Usuario,
			&i.Nivel,
			&i.TienePassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPersonCurrentFlag = `-- name: SetPersonCurrentFlag :execrows
UPDATE detall.person
SET person_current_flag = $1
WHERE person_sk = $2
  AND person_escuadrilla_fk = $3
  AND person_current_flag = NOT $1
`

type SetPersonCurrentFlagParams struct {
	PersonCurrentFlag   bool  `json:"person_current_flag"`
	PersonSk            int32 `json:"person_sk"`
	PersonEscuadrillaFk int32 `json:"person_escuadrilla_fk"`
}

// Una sola query para alta/baja con verificación del estado deseado.
func (q *Queries) SetPersonCurrentFlag(ctx context.Context, arg SetPersonCurrentFlagParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPersonCurrentFlag, arg.PersonCurrentFlag, arg.PersonSk, arg.PersonEscuadrillaFk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPersonPasswordBySk = `-- name: SetPersonPasswordBySk :execrows
UPDATE detall.person SET person_password_hash = $1, person_password_must_change = TRUE
WHERE person_sk = $2 AND person_escuadrilla_fk = $3
`

type SetPersonPasswordBySkParams struct {
	PersonPasswordHash  *string `json:"person_password_hash"`
	PersonSk            int32   `json:"person_sk"`
	PersonEscuadrillaFk int32   `json:"person_escuadrilla_fk"`
}

// Reseteo del Superusuario: fija el hash (por defecto 'aether') y fuerza el
// cambio en el siguiente login. Acotado a la escuadrilla del superusuario.
func (q *Queries) SetPersonPasswordBySk(ctx context.Context, arg SetPersonPasswordBySkParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPersonPasswordBySk, arg.PersonPasswordHash, arg.PersonSk, arg.PersonEscuadrillaFk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPersonPermissionLevel = `-- name: SetPersonPermissionLevel :execrows
UPDATE detall.person SET person_permission_level = $1
WHERE person_sk = $2 AND person_escuadrilla_fk = $3
`

type SetPersonPermissionLevelParams struct {
	PersonPermissionLevel string `json:"person_permission_level"`
	PersonSk              int32  `json:"person_sk"`
	PersonEscuadrillaFk   int32  `json:"person_escuadrilla_fk"`
}

func (q *Queries) SetPersonPermissionLevel(ctx context.Context, arg SetPersonPermissionLevelParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPersonPermissionLevel, arg.PersonPermissionLevel, arg.PersonSk, arg.PersonEscuadrillaFk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePerson = `-- name: UpdatePerson :execrows
UPDATE detall.person
SET person_nk = $1,
    person_user = $2,
    person_rank = $3,
    person_cuerpo = $4,
    person_especialidad = $5,
    person_name = $6,
    person_last_name_1 = $7,
    person_last_name_2 = $8,
    person_phone = $9,
    person_dni = $10,
    person_localidad = $11,
    person_division = $12,
    person_rol = $13,
    person_a_emp = $14,
    person_f_emb = $15,
    person_birthdate = $16,
    person_num_escalafon = $17
WHERE person_sk = $18 AND person_escuadrilla_fk = $19
`

type UpdatePersonParams struct {
	PersonNk            *string     `json:"person_nk"`
	PersonUser          string      `json:"person_user"`
	PersonRank          string      `json:"person_rank"`
	PersonCuerpo        string      `json:"person_cuerpo"`
	PersonEspecialidad  string      `json:"person_especialidad"`
	PersonName          string      `json:"person_name"`
	PersonLastName1     string      `json:"person_last_name_1"`
	PersonLastName2     string      `json:"person_last_name_2"`
	PersonPhone         string      `json:"person_phone"`
	PersonDni           *string     `json:"person_dni"`
	PersonLocalidad     string      `json:"person_localidad"`
	PersonDivision      string      `json:"person_division"`
	PersonRol           string      `json:"person_rol"`
	PersonAEmp          pgtype.Date `json:"person_a_emp"`
	PersonFEmb          pgtype.Date `json:"person_f_emb"`
	PersonBirthdate     pgtype.Date `json:"person_birthdate"`
	PersonNumEscalafon  int32       `json:"person_num_escalafon"`
	PersonSk            int32       `json:"person_sk"`
	PersonEscuadrillaFk int32       `json:"person_escuadrilla_fk"`
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePerson,
		arg.PersonNk,
		arg.PersonUser,
		arg.PersonRank,
		arg.PersonCuerpo,
		arg.PersonEspecialidad,
		arg.PersonName,
		arg.PersonLastName1,
		arg.PersonLastName2,
		arg.PersonPhone,
		arg.PersonDni,
		arg.PersonLocalidad,
		arg.PersonDivision,
		arg.PersonRol,
		arg.PersonAEmp,
		arg.PersonFEmb,
		arg.PersonBirthdate,
		arg.PersonNumEscalafon,
		arg.PersonSk,
		arg.PersonEscuadrillaFk,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
