// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projectiles.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const projectilesByCrew = `-- name: ProjectilesByCrew :many

WITH projectile_agg AS (
    SELECT
        pr.projectile_person_fk AS person_sk,
        SUM(CASE WHEN pr.projectile_type_fk = 1 THEN pr.projectile_qty ELSE 0 END)::int AS m3m,
        SUM(CASE WHEN pr.projectile_type_fk = 2 THEN pr.projectile_qty ELSE 0 END)::int AS mag58
    FROM operations.projectile pr
    JOIN operations.flight f ON pr.projectile_flight_fk = f.flight_sk
    WHERE f.flight_date >= $1 AND f.flight_date <= $2
    GROUP BY pr.projectile_person_fk
)
SELECT
    p.person_nk,
    COALESCE(pa.m3m,   0)::int AS m3m_qty,
    COALESCE(pa.mag58, 0)::int AS mag58_qty
FROM detall.v_person_ordered p
LEFT JOIN projectile_agg pa ON pa.person_sk = p.person_sk
WHERE p.person_nk IS NOT NULL
  AND p.person_escuadrilla_fk = $3
  AND p.person_rol NOT IN ('Piloto', 'No Tripulante')
ORDER BY p.order_position
`

type ProjectilesByCrewParams struct {
	FlightDate          pgtype.Date `json:"flight_date"`
	FlightDate_2        pgtype.Date `json:"flight_date_2"`
	PersonEscuadrillaFk int32       `json:"person_escuadrilla_fk"`
}

type ProjectilesByCrewRow struct {
	PersonNk *string `json:"person_nk"`
	M3mQty   int32   `json:"m3m_qty"`
	Mag58Qty int32   `json:"mag58_qty"`
}

// ============================================================
// Projectiles (proyectiles disparados por dotación)
//
// Agrega operations.projectile por persona sobre un rango de fechas resuelto
// en Go (mismo parser que hours/landings), filtrando por dotación.
//
// projectile_type_fk: 1 = M3M (7.62), 2 = MAG58 (12.7).
//
// Solo dotación: person_rol NOT IN ('Piloto', 'No Tripulante') — regla fija de
// esta página (/dotaciones/proyectiles), por eso va en la propia query.
// RLS explícita: $3 = escuadrilla_fk. Rango por f.flight_date.
// ============================================================
func (q *Queries) ProjectilesByCrew(ctx context.Context, arg ProjectilesByCrewParams) ([]ProjectilesByCrewRow, error) {
	rows, err := q.db.Query(ctx, projectilesByCrew, arg.FlightDate, arg.FlightDate_2, arg.PersonEscuadrillaFk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectilesByCrewRow
	for rows.Next() {
		var i ProjectilesByCrewRow
		if err := rows.Scan(&i.PersonNk, &i.M3mQty, &i.Mag58Qty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
