// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddAircraft(ctx context.Context, arg AddAircraftParams) error
	// ============================================================
	// Ratings (Hito 4, lote 5)
	//
	// Reimplementa los 5 SPs de ratings (model, operational, generalTactical,
	// leadership, maintenance) + CRUD de crew_qualification y notcrew_qualification.
	//
	// Bug fixes vs Rust:
	//   - INSERTs originales NO setean escuadrilla_fk (NOT NULL en BD) → fallarían.
	//     Aquí se inyecta desde la sesión.
	//   - DELETEs originales no filtran por escuadrilla. Aquí WHERE incluye RLS.
	// ============================================================
	// =============== CRUD crew_qualification ===============
	AddCrewRating(ctx context.Context, arg AddCrewRatingParams) (int32, error)
	// =============== Mutaciones ===============
	// code se normaliza a uppercase en Go.
	AddDepartureArrivalPlace(ctx context.Context, arg AddDepartureArrivalPlaceParams) error
	AddEvent(ctx context.Context, arg AddEventParams) error
	// =============== CRUD notcrew_qualification ===============
	AddNotCrewRating(ctx context.Context, arg AddNotCrewRatingParams) (int32, error)
	// ============================================================
	// Training (Hito 4, lote 3)
	//
	// Reimplementa sp_get_adiestramiento + sp_get_instruccion.
	// En vez de un SP gigante con FOR JSON anidado, troceamos en queries
	// pequeñas que el service compone en el shape final.
	// ============================================================
	// =============== adiestramiento ===============
	// Papeletas filtradas por block IN ($1) y plan IN ('Adi Básico', 'Adi Avanzado').
	AdiestramientoPapeletas(ctx context.Context, arg AdiestramientoPapeletasParams) ([]AdiestramientoPapeletasRow, error)
	// Última papeleta por (persona, session): días transcurridos, restantes, estado.
	// Filtramos por personas con rol en $1 y escuadrilla = $2.
	AdiestramientoPapeletasRealizadas(ctx context.Context, arg AdiestramientoPapeletasRealizadasParams) ([]AdiestramientoPapeletasRealizadasRow, error)
	// Por persona (filtrada por rol/escuadrilla): full_name, CRP, días sin volar/real/simulador.
	AdiestramientoPersonas(ctx context.Context, arg AdiestramientoPersonasParams) ([]AdiestramientoPersonasRow, error)
	// Filtra ausencias que se solapan con el mes [start, end].
	// $1 = month_start, $2 = month_end, $3 = escuadrilla.
	AvailabilityAbsences(ctx context.Context, arg AvailabilityAbsencesParams) ([]AvailabilityAbsencesRow, error)
	// $1 = month_start, $2 = month_end, $3 = escuadrilla.
	AvailabilityComisiones(ctx context.Context, arg AvailabilityComisionesParams) ([]AvailabilityComisionesRow, error)
	// ============================================================
	// Availability (Hito 4, lote 3)
	//
	// Reimplementa sp_get_availability + CRUD de detall.absence.
	// Devuelve 3 listas (persons, absenses, person_comisions) filtradas
	// por mes/año recibido como parámetro.
	// ============================================================
	AvailabilityPersons(ctx context.Context, personEscuadrillaFk int32) ([]AvailabilityPersonsRow, error)
	CountComisiones(ctx context.Context, arg CountComisionesParams) (int32, error)
	CountEvents(ctx context.Context) (int32, error)
	CountFlights(ctx context.Context, arg CountFlightsParams) (int32, error)
	CountPapeletas(ctx context.Context, papeletaEscuadrillaFk int32) (int32, error)
	CountPersons(ctx context.Context, personEscuadrillaFk int32) (int32, error)
	// Calificaciones por persona, filtradas por (type, role[]) y escuadrilla.
	// Sólo las que tienen date_qualified, ordenadas por crew_ratings_fk.
	CrewQualificationsByPersonAndType(ctx context.Context, arg CrewQualificationsByPersonAndTypeParams) ([]CrewQualificationsByPersonAndTypeRow, error)
	DeleteAbsence(ctx context.Context, arg DeleteAbsenceParams) (int64, error)
	DeleteAircraft(ctx context.Context, arg DeleteAircraftParams) (int64, error)
	DeleteComision(ctx context.Context, arg DeleteComisionParams) (int64, error)
	DeleteComisionLugar(ctx context.Context, comisionLugarSk int32) (int64, error)
	DeleteCrewRating(ctx context.Context, arg DeleteCrewRatingParams) (int64, error)
	DeleteDepartureArrivalPlace(ctx context.Context, departureArrivalPlaceSk int32) (int64, error)
	DeleteEvent(ctx context.Context, eventSk int32) (int64, error)
	DeleteFestivo(ctx context.Context, festivoSk int32) (int64, error)
	// =============== DELETE (cascade en BD elimina hijos) ===============
	DeleteFlight(ctx context.Context, arg DeleteFlightParams) (int64, error)
	DeleteNotCrewRating(ctx context.Context, arg DeleteNotCrewRatingParams) (int64, error)
	DeletePersonComisionBySk(ctx context.Context, arg DeletePersonComisionBySkParams) (int64, error)
	DeletePersonFromComision(ctx context.Context, arg DeletePersonFromComisionParams) (int64, error)
	// =============== sp_get_dias_comision ===============
	// $1 = fechaFin (NULL → CURRENT_DATE en handler). fechaInicio = fechaFin - 365.
	// Devuelve per-persona días totales por categoría de comisión:
	//   - Categorías "no caducan": SUMA días totales históricos.
	//   - Categorías "sí caducan" (OMP/UNADEST/UNAEMB): SUMA solapamiento con [fechaInicio, fechaFin].
	DiasComision(ctx context.Context, arg DiasComisionParams) ([]DiasComisionRow, error)
	// ============================================================
	// Esfuerzo (Hito 4, lote 6)
	//
	// Reimplementa sp_get_esfuerzo: por persona activa, suma de días de
	// comisión "con esfuerzo" en los últimos 730 días (con clipping de
	// comisiones que parcialmente se solapan con el rango).
	//
	// RLS explícita: $2 = escuadrilla_fk.
	// $1 = fecha_fin (Go la calcula con today si viene vacía).
	// ============================================================
	Esfuerzo(ctx context.Context, arg EsfuerzoParams) ([]EsfuerzoRow, error)
	// Comportamiento heredado: bloquear cualquier 2º festivo en la misma fecha,
	// aunque el motivo difiera (más estricto que UQ_festivo en BD).
	FestivoExistsOnDate(ctx context.Context, festivoDia pgtype.Date) (bool, error)
	FestivoExistsOnDateOtherSk(ctx context.Context, arg FestivoExistsOnDateOtherSkParams) (bool, error)
	FlightApproaches(ctx context.Context, dollar_1 []int32) ([]FlightApproachesRow, error)
	// =============== BULK FETCHES por flight_sk[] (para componer JSON) ===============
	// Personas que tienen al menos 1 person_hour para los vuelos dados.
	FlightCrew(ctx context.Context, dollar_1 []int32) ([]FlightCrewRow, error)
	FlightCupos(ctx context.Context, dollar_1 []int32) ([]FlightCuposRow, error)
	FlightFormationHours(ctx context.Context, dollar_1 []int32) ([]FlightFormationHoursRow, error)
	FlightGvntypeHours(ctx context.Context, dollar_1 []int32) ([]FlightGvntypeHoursRow, error)
	FlightIftHours(ctx context.Context, dollar_1 []int32) ([]FlightIftHoursRow, error)
	FlightInstructorHours(ctx context.Context, dollar_1 []int32) ([]FlightInstructorHoursRow, error)
	FlightLandings(ctx context.Context, dollar_1 []int32) ([]FlightLandingsRow, error)
	FlightPapeletas(ctx context.Context, dollar_1 []int32) ([]FlightPapeletasRow, error)
	FlightPassengers(ctx context.Context, dollar_1 []int32) ([]FlightPassengersRow, error)
	FlightPersonHours(ctx context.Context, dollar_1 []int32) ([]FlightPersonHoursRow, error)
	FlightProjectiles(ctx context.Context, dollar_1 []int32) ([]FlightProjectilesRow, error)
	FlightWtHours(ctx context.Context, dollar_1 []int32) ([]FlightWtHoursRow, error)
	// =============== sp_get_generalTacticalRatings ===============
	// Métricas detalladas por persona para calcular el `state` de las
	// calificaciones generales/tácticas (crew_ratings_fk 12-18).
	// $1 = escuadrilla_fk
	GeneralTacticalPersonMetrics(ctx context.Context, personEscuadrillaFk int32) ([]GeneralTacticalPersonMetricsRow, error)
	// Calificaciones generales/tácticas (crew_ratings_fk 12-18) por persona,
	// con date_qualified. El state se calcula en Go combinando con las métricas.
	GeneralTacticalQualifications(ctx context.Context, personEscuadrillaFk int32) ([]GeneralTacticalQualificationsRow, error)
	// =============== person_comision (assign + delete) ===============
	// Devuelve las fechas y comprueba que la comisión existe en la escuadrilla.
	GetComisionDates(ctx context.Context, arg GetComisionDatesParams) (GetComisionDatesRow, error)
	GetCrewMembersBySk(ctx context.Context, arg GetCrewMembersBySkParams) ([]GetCrewMembersBySkRow, error)
	GetDynamicHorasAutoridad(ctx context.Context, arg GetDynamicHorasAutoridadParams) ([]GetDynamicHorasAutoridadRow, error)
	// Devuelve filas planas (evento, lugar, horas); Go agrupa por evento → map[lugar]horas.
	GetDynamicHorasEventoLugar(ctx context.Context, arg GetDynamicHorasEventoLugarParams) ([]GetDynamicHorasEventoLugarRow, error)
	GetDynamicHorasHelicoptero(ctx context.Context, arg GetDynamicHorasHelicopteroParams) ([]GetDynamicHorasHelicopteroRow, error)
	GetDynamicHorasPeriodo(ctx context.Context, arg GetDynamicHorasPeriodoParams) (GetDynamicHorasPeriodoRow, error)
	GetDynamicHorasVuelo(ctx context.Context, arg GetDynamicHorasVueloParams) ([]GetDynamicHorasVueloRow, error)
	// =============== DYNAMIC STATS ===============
	GetDynamicTotals(ctx context.Context, arg GetDynamicTotalsParams) (GetDynamicTotalsRow, error)
	// ============================================================
	// Events (Hito 4, lote 2)
	// Reemplaza operations.sp_get_events + add_event + update_event.
	// operations.event no tiene escuadrilla_fk → catálogo global.
	// ============================================================
	GetEventsAll(ctx context.Context) ([]OperationsEvent, error)
	GetStaticAdministrativosStats(ctx context.Context, personEscuadrillaFk int32) (GetStaticAdministrativosStatsRow, error)
	// Airflow medio: por persona (rol piloto/dotación), si días sin volar >= 60 → 0,
	// en otro caso 100 - dias/60 * 100. Promedio global.
	GetStaticAirflowAverage(ctx context.Context, personEscuadrillaFk int32) (int32, error)
	// CRP medio: por persona, suma de valores de papeleta_pilot/dv_crp_value de
	// papeletas registradas y NO caducadas (flight_date >= CURRENT_DATE - papeleta_expiration).
	// Cap a 100 por persona, luego AVG global.
	GetStaticCRPAverage(ctx context.Context, personEscuadrillaFk int32) (int32, error)
	GetStaticCrewStats(ctx context.Context, personEscuadrillaFk int32) (GetStaticCrewStatsRow, error)
	GetStaticMantenedoresStats(ctx context.Context, personEscuadrillaFk int32) (GetStaticMantenedoresStatsRow, error)
	GetStaticPersonalTotalStats(ctx context.Context, personEscuadrillaFk int32) (GetStaticPersonalTotalStatsRow, error)
	// ============================================================
	// Dashboard (Hito 3)
	//
	// Reimplementación de sp_get_dashboard_static_stats y
	// sp_get_dashboard_dynamic_stats. La composición final del JSON
	// vive en Go; estas queries devuelven filas tipadas que el service
	// ensambla.
	//
	// RLS explícita: cada query toma $1 = escuadrilla_id y filtra
	// person.person_escuadrilla_fk o flight.flight_escuadrilla_fk.
	// ============================================================
	// =============== STATIC STATS ===============
	GetStaticPilotsStats(ctx context.Context, personEscuadrillaFk int32) (GetStaticPilotsStatsRow, error)
	InsertAbsence(ctx context.Context, arg InsertAbsenceParams) (int32, error)
	InsertApproach(ctx context.Context, arg InsertApproachParams) error
	// =============== Comisión CRUD ===============
	InsertComision(ctx context.Context, arg InsertComisionParams) (int32, error)
	InsertComisionLugar(ctx context.Context, comisionName string) (DetallComisionLugar, error)
	InsertCupoHour(ctx context.Context, arg InsertCupoHourParams) error
	// Devuelve el sk para que el frontend pueda redirigir / seleccionar.
	InsertEvent(ctx context.Context, arg InsertEventParams) (int32, error)
	InsertFestivo(ctx context.Context, arg InsertFestivoParams) (int32, error)
	// ============================================================
	// Flights (Hito 4, lote 7)
	//
	// Reimplementa db_insert_flight (transacción con ~10 tablas hijas),
	// db_delete_flight y sp_get_flights_with_flexible_crew.
	//
	// Convenciones de SK (del seed/legacy):
	//   period:        1=día, 2=noche, 3=gvn
	//   ifr_app_type:  1=precision, 2=no_precision, 3=td, 4=sp
	//   landing_place: 1=tierra, 2=mono-spot, 3=multi-spot, 4=carrier
	//   projectile:    1=m3m, 2=mag58
	// ============================================================
	// =============== INSERT MASTER + DEPENDIENTES ===============
	InsertFlight(ctx context.Context, arg InsertFlightParams) (int32, error)
	InsertFormationHour(ctx context.Context, arg InsertFormationHourParams) error
	InsertGvntypeHour(ctx context.Context, arg InsertGvntypeHourParams) error
	InsertIftHour(ctx context.Context, arg InsertIftHourParams) error
	InsertInstructorHour(ctx context.Context, arg InsertInstructorHourParams) error
	InsertLanding(ctx context.Context, arg InsertLandingParams) error
	InsertPapeleta(ctx context.Context, arg InsertPapeletaParams) (int32, error)
	InsertPapeletaCrewCount(ctx context.Context, arg InsertPapeletaCrewCountParams) error
	InsertPassenger(ctx context.Context, arg InsertPassengerParams) error
	// Defaults: current_flag=TRUE, permission_level='Común' (¡con acento!).
	// Bug fix vs Rust: el INSERT original omitía person_localidad (NOT NULL),
	// por lo que cualquier add_person fallaba si la BD seguía el esquema.
	InsertPerson(ctx context.Context, arg InsertPersonParams) (int32, error)
	InsertPersonHour(ctx context.Context, arg InsertPersonHourParams) error
	InsertPersonToComision(ctx context.Context, arg InsertPersonToComisionParams) error
	InsertProjectile(ctx context.Context, arg InsertProjectileParams) error
	InsertWtHour(ctx context.Context, arg InsertWtHourParams) error
	// =============== instruccion ===============
	InstruccionPapeletas(ctx context.Context, arg InstruccionPapeletasParams) ([]InstruccionPapeletasRow, error)
	// Última papeleta (MAX flight_date) por (persona, session_fk) limitada a planes en $1.
	InstruccionPapeletasRealizadas(ctx context.Context, arg InstruccionPapeletasRealizadasParams) ([]InstruccionPapeletasRealizadasRow, error)
	InstruccionPersonas(ctx context.Context, arg InstruccionPersonasParams) ([]InstruccionPersonasRow, error)
	// Personas asignadas a una comisión, ordenadas por la vista canónica.
	ListComisionPeople(ctx context.Context, comisionFk int32) ([]ListComisionPeopleRow, error)
	// Variante con campos separados (espejo de get_comision_people en Rust).
	ListComisionPeopleExpanded(ctx context.Context, comisionFk int32) ([]ListComisionPeopleExpandedRow, error)
	// =============== Comisión listings ===============
	// Paginado + filtros opcionales. Convención:
	//   $2 = comision_sk filtro (0 → sin filtro)
	//   $3 = date_from (pgtype.Date.Valid=false → sin filtro)
	//   $4 = date_to   (idem)
	ListComisiones(ctx context.Context, arg ListComisionesParams) ([]ListComisionesRow, error)
	// ============================================================
	// Festivos (Hito 4, lote 2)
	// Catálogo global (sin escuadrilla_fk en la tabla).
	// ============================================================
	ListFestivos(ctx context.Context) ([]DetallFestivo, error)
	// =============== LIST (sp_get_flights_with_flexible_crew) ===============
	// Paginado + filtros opcionales. $2 = flight_sk (0=sin filtro), $3/$4 = date_from/to (NULL=sin filtro).
	ListFlights(ctx context.Context, arg ListFlightsParams) ([]ListFlightsRow, error)
	// ============================================================
	// Papeletas (Hito 4, lote 2)
	//
	// Fix RLS: add_papeleta y update_papeleta originales NO inyectaban
	// papeleta_escuadrilla_fk en SQL Server, pero la columna es NOT NULL.
	// En PG explícitamente:
	//   - INSERT setea papeleta_escuadrilla_fk = $9 (de la sesión).
	//   - UPDATE filtra por papeleta_escuadrilla_fk para impedir editar
	//     papeletas de otra escuadrilla.
	// ============================================================
	ListPapeletas(ctx context.Context, papeletaEscuadrillaFk int32) ([]ListPapeletasRow, error)
	// ============================================================
	// Persons (Hito 4, lote 3)
	//
	// Reimplementa sp_get_persons + add/update/dardebaja/dardealta_person
	// + get_crew_members_by_sk.
	//
	// Fix RLS: add_person ahora setea person_escuadrilla_fk explícitamente
	// desde la sesión (en SQL Server usaba SESSION_CONTEXT).
	// update_person filtra por escuadrilla para impedir editar de otra.
	// Fix typo: 'Comun' → 'Común' (constraint CHK requiere acento).
	// ============================================================
	// Aliases Spanish para mantener el contrato del frontend
	// (src/features/personnel/utils/transformPersonnelFromDB.ts).
	ListPersons(ctx context.Context, personEscuadrillaFk int32) ([]ListPersonsRow, error)
	// ============================================================
	// Lookups (Hito 4, lote 1)
	//
	// Traducción de src-tauri/src/database/commands/lookups.rs (29 fns).
	// RLS explícita: $1 = escuadrilla_id en cada query que lo necesita.
	// ============================================================
	// =============== Reads: catálogos para selectores (sk + label) ===============
	// get_aircrafts (frontend): selector de aeronaves activas.
	LookupAircrafts(ctx context.Context, aircraftEscuadrillaFk int32) ([]LookupAircraftsRow, error)
	// get_aircrafts_manage: vista completa para gestión.
	LookupAircraftsManage(ctx context.Context, aircraftEscuadrillaFk int32) ([]LookupAircraftsManageRow, error)
	LookupAuthorities(ctx context.Context) ([]LookupAuthoritiesRow, error)
	LookupComisionLugares(ctx context.Context) ([]DetallComisionLugar, error)
	LookupComisionTypes(ctx context.Context) ([]DetallComisionType, error)
	// get_crew_lookup: dotación (no pilotos, no no-tripulantes).
	LookupCrew(ctx context.Context, personEscuadrillaFk int32) ([]LookupCrewRow, error)
	LookupDepartureArrivalPlaces(ctx context.Context) ([]OperationsDepartureArrivalPlace, error)
	// =============== Reads: catálogos plano (Vec<String>) ===============
	LookupEventNames(ctx context.Context) ([]string, error)
	// get_events_lookup: "nombre - lugar" concatenado.
	LookupEvents(ctx context.Context) ([]LookupEventsRow, error)
	// get_events_manage: nombre y lugar separados.
	LookupEventsManage(ctx context.Context) ([]OperationsEvent, error)
	LookupPapeletaBloques(ctx context.Context) ([]string, error)
	LookupPapeletaPlanes(ctx context.Context) ([]string, error)
	LookupPapeletas(ctx context.Context, papeletaEscuadrillaFk int32) ([]LookupPapeletasRow, error)
	LookupPassengerTypes(ctx context.Context) ([]OperationsPassengerType, error)
	LookupPersonDivisiones(ctx context.Context) ([]string, error)
	// Ordenados por precedencia militar (rank_order).
	LookupPersonEmpleos(ctx context.Context) ([]string, error)
	LookupPersonEspecialidades(ctx context.Context) ([]string, error)
	LookupPersonRoles(ctx context.Context) ([]string, error)
	// get_persons_lookup: "rank name last_name_1 [last_name_2]".
	LookupPersons(ctx context.Context, personEscuadrillaFk int32) ([]LookupPersonsRow, error)
	LookupPersonsForComision(ctx context.Context, personEscuadrillaFk int32) ([]LookupPersonsForComisionRow, error)
	// get_pilots_lookup: pilotos ordenados por la vista canónica.
	LookupPilots(ctx context.Context, personEscuadrillaFk int32) ([]LookupPilotsRow, error)
	// TOP 20 (LIMIT 20) más recientes. esfuerzo: boolean (en SQL Server era BIT
	// y el Rust intentaba leer como string, lo que devolvía NULL).
	LookupRecentComisiones(ctx context.Context, comisionEscuadrillaFk int32) ([]LookupRecentComisionesRow, error)
	// =============== comision_lugar CRUD ===============
	LugarExistsByName(ctx context.Context, lower string) (bool, error)
	LugarExistsByNameOther(ctx context.Context, arg LugarExistsByNameOtherParams) (bool, error)
	LugarUsageCount(ctx context.Context, comisionLugarFk int32) (int32, error)
	// ============================================================
	// Hours (Hito 4, lote 6)
	//
	// Reimplementa sp_get_personNH90PeriodHours. El rango de fechas se
	// resuelve en Go (mismo parser que dashboard) y se pasan ya como dates.
	// Esto evita lógica de fechas en SQL y mantiene la query pura.
	//
	// RLS explícita: $3 = escuadrilla_fk.
	// $4 = roles permitidos (array vacío = todos los roles).
	// ============================================================
	NH90PeriodHours(ctx context.Context, arg NH90PeriodHoursParams) ([]NH90PeriodHoursRow, error)
	NotCrewQualificationsByPerson(ctx context.Context, personEscuadrillaFk int32) ([]NotCrewQualificationsByPersonRow, error)
	NotCrewRatingsCatalog(ctx context.Context) ([]DetallNotcrewRatingType, error)
	// =============== sp_get_operationalRatings ===============
	// Devuelve por persona (Piloto/Dotación/Dotación-Nadador) las métricas necesarias
	// para calcular calificacion_abrv en Go: horas_365, crp_total, h2p_reciente,
	// dv_reciente, pi1_piloto, pi2_piloto, pi1_dotacion, pi2_dotacion.
	// $1 = escuadrilla_fk
	// Exenciones PI1 (datos legacy hardcoded del SP original) se aplican en IN
	// en lugar de un CTE con VALUES porque sqlc descarta el SELECT list
	// cuando ve `SELECT * FROM (VALUES ...)` o aliasing complejo.
	OperationalPersonMetrics(ctx context.Context, personEscuadrillaFk int32) ([]OperationalPersonMetricsRow, error)
	PersonAlreadyInComision(ctx context.Context, arg PersonAlreadyInComisionParams) (bool, error)
	// Para mensajes de error en bulk assign.
	PersonFullName(ctx context.Context, personSk int32) (string, error)
	PersonHasOverlapAbsence(ctx context.Context, arg PersonHasOverlapAbsenceParams) (bool, error)
	// Otra comisión cualquiera del person que solapa con [start, end].
	PersonHasOverlapComision(ctx context.Context, arg PersonHasOverlapComisionParams) (bool, error)
	// Personas activas filtradas por rol[] dentro de una escuadrilla.
	PersonsByRoles(ctx context.Context, arg PersonsByRolesParams) ([]PersonsByRolesRow, error)
	// =============== sp_get_modelRatings ===============
	// Catálogo filtrable por type/role para componer múltiples sub-listas.
	// $1 = type (NULL/empty = todos), $2 = role[] (NULL/empty = todos).
	RatingsCatalog(ctx context.Context, arg RatingsCatalogParams) ([]OperationsCrewRatingType, error)
	// absence_reason del request puede venir como nombre o como id numérico.
	// Para el nombre, hacemos lookup. El handler trata el caso numérico antes de llamar.
	ResolveAbsenceReason(ctx context.Context, absenceReason string) (int32, error)
	ResolveComisionLugar(ctx context.Context, comisionName string) (int32, error)
	// ============================================================
	// Comisiones (Hito 4, lote 4)
	//
	// Reimplementa sp_get_comisiones, sp_get_dias_comision + CRUD de
	// detall.comision, detall.comision_lugar, detall.person_comision.
	//
	// Fix RLS: update/delete de comisión filtran por escuadrilla_fk.
	// detall.comision_lugar NO tiene escuadrilla_fk (catálogo global) →
	// las mutaciones se protegen sólo con RequireAuth.
	// ============================================================
	// =============== Resolvers (name → sk) ===============
	ResolveComisionType(ctx context.Context, name string) (int32, error)
	// Una sola query para alta/baja con verificación del estado deseado.
	SetPersonCurrentFlag(ctx context.Context, arg SetPersonCurrentFlagParams) (int64, error)
	UpdateAbsence(ctx context.Context, arg UpdateAbsenceParams) (int64, error)
	// Devuelve el flag persistido para que el handler pueda verificar.
	UpdateAircraftCurrentFlag(ctx context.Context, arg UpdateAircraftCurrentFlagParams) (bool, error)
	UpdateComision(ctx context.Context, arg UpdateComisionParams) (int64, error)
	UpdateComisionLugar(ctx context.Context, arg UpdateComisionLugarParams) (int64, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (int64, error)
	UpdateFestivo(ctx context.Context, arg UpdateFestivoParams) (int64, error)
	UpdatePapeleta(ctx context.Context, arg UpdatePapeletaParams) (int64, error)
	UpdatePerson(ctx context.Context, arg UpdatePersonParams) (int64, error)
	// Idempotente: si el nombre ya existe, no hace nada.
	UpsertEventName(ctx context.Context, eventNameValue string) error
}

var _ Querier = (*Queries)(nil)
