// Shared hooks barrel export
export { useConfirmationDialog } from './useConfirmationDialog'
export type { ConfirmationTarget } from './useConfirmationDialog'
export { useDebouncedValue } from './useDebouncedValue'

// Lookups (datos de referencia para formularios)
export {
    useAircrafts,
    useAircraftsManage,
    useAircraftModels,
    useEventsManage,
    useDepartureArrivalPlaces,
    useEventsLookup,
    useAuthorities,
    useCapbas,
    usePilotsLookup,
    useCrewLookup,
    usePapeletasLookup,
    useGroundSchoolPapeletasLookup,
    usePassengerTypes,
    useComisionTypes,
    useComisionLugares,
    useRecentComisiones,
    usePersonsForComision,
    useEventNamesLookup,
    usePapeletaBloquesLookup,
    usePapeletaPlanesLookup,
    usePersonEspecialidadesLookup,
    usePersonEmpleosLookup,
    usePersonDivisionesLookup,
    usePersonRolesLookup,
    usePersonsLookup,
    usePersonsNkLookup,
    useFuelPlaces,
    useFuelPayers,
    useFuelPhases,
    useFuelTypes,
    useMedicalExamPlaces,
    useMedicalExamResults,
} from './useLookups'
export type {
    AircraftLookup,
    AircraftManageLookup,
    AircraftModelLookup,
    EventManageLookup,
    DepartureArrivalPlaceLookup,
    EventLookup,
    AuthorityLookup,
    CapbaLookup,
    CrewLookup,
    PapeletaLookup,
    PassengerTypeLookup,
    ComisionTypeLookup,
    ComisionLugarLookup,
    RecentComisionLookup,
    PersonForComisionLookup,
    PersonLookup,
    FuelPlaceLookup,
    FuelPayerLookup,
    FuelPhaseLookup,
    FuelTypeLookup,
    MedicalExamPlaceLookup,
    MedicalExamResultLookup,
} from './useLookups'
